# -*- coding: utf-8 -*-
"""世界语言插件的语言目录数据。

每种语言一项：
- code:    ISO 639 语言代码（优先两字母码，无两字母码用三字母/常用码）
- autonym: 该语言的自称（该语言本国人民的称呼），始终原样展示
- names:   当前界面语言（zh-CN / zh-TW / en）下对该语言的称呼，由前端按界面语言选取
- region:  区域 key（前端词典翻译展示）：asia-east / asia-south / asia-west /
           europe / africa / americas / oceania / constructed

说明：本数据为插件自包含内容，与宿主核心及任何其它插件解耦；
插件未安装时，宿主不会感知到本数据的任何内容。
"""

LANGUAGES = [
    # ---- 东亚与北亚 ----
    {"code": "zh",  "autonym": "中文",          "names": {"zh-CN": "中文", "zh-TW": "中文", "en": "Chinese"},   "region": "asia-east"},
    {"code": "ja",  "autonym": "日本語",         "names": {"zh-CN": "日语", "zh-TW": "日語", "en": "Japanese"},  "region": "asia-east"},
    {"code": "ko",  "autonym": "한국어",          "names": {"zh-CN": "韩语", "zh-TW": "韓語", "en": "Korean"},    "region": "asia-east"},
    {"code": "mn",  "autonym": "Монгол хэл",     "names": {"zh-CN": "蒙古语", "zh-TW": "蒙古語", "en": "Mongolian"}, "region": "asia-east"},
    {"code": "bo",  "autonym": "བོད་སྐད",        "names": {"zh-CN": "藏语", "zh-TW": "藏語", "en": "Tibetan"},   "region": "asia-east"},
    {"code": "ug",  "autonym": "ئۇيغۇرچە",        "names": {"zh-CN": "维吾尔语", "zh-TW": "維吾爾語", "en": "Uyghur"}, "region": "asia-east"},
    {"code": "ain", "autonym": "アイヌ・イタク",    "names": {"zh-CN": "阿伊努语", "zh-TW": "阿伊努語", "en": "Ainu"}, "region": "asia-east"},
    {"code": "ryu", "autonym": "うちなーぐち",     "names": {"zh-CN": "琉球语", "zh-TW": "琉球語", "en": "Ryukyuan"}, "region": "asia-east"},
    {"code": "tyv", "autonym": "Тыва дыл",        "names": {"zh-CN": "图瓦语", "zh-TW": "圖瓦語", "en": "Tuvan"}, "region": "asia-east"},
    {"code": "sah", "autonym": "Саха тыла",      "names": {"zh-CN": "雅库特语", "zh-TW": "雅庫特語", "en": "Yakut"}, "region": "asia-east"},
    {"code": "bxr", "autonym": "Буряад хэлэн",    "names": {"zh-CN": "布里亚特语", "zh-TW": "布里亞特語", "en": "Buryat"}, "region": "asia-east"},
    {"code": "xal", "autonym": "Хальмг келн",    "names": {"zh-CN": "卡尔梅克语", "zh-TW": "卡爾梅克語", "en": "Kalmyk"}, "region": "asia-east"},
    {"code": "evn", "autonym": "Эвэнкӣ",         "names": {"zh-CN": "埃文基语", "zh-TW": "埃文基語", "en": "Evenki"}, "region": "asia-east"},
    {"code": "niv", "autonym": "Нивхгу дин",     "names": {"zh-CN": "尼夫赫语", "zh-TW": "尼夫赫語", "en": "Nivkh"}, "region": "asia-east"},
    {"code": "ckt", "autonym": "Ԓыгъоравэтԓьэн йиԓыйиԓ", "names": {"zh-CN": "楚科奇语", "zh-TW": "楚科奇語", "en": "Chukchi"}, "region": "asia-east"},

    # ---- 东南亚与南亚 ----
    {"code": "id",  "autonym": "Bahasa Indonesia", "names": {"zh-CN": "印度尼西亚语", "zh-TW": "印尼語", "en": "Indonesian"}, "region": "asia-south"},
    {"code": "ms",  "autonym": "Bahasa Melayu",    "names": {"zh-CN": "马来语", "zh-TW": "馬來語", "en": "Malay"}, "region": "asia-south"},
    {"code": "th",  "autonym": "ไทย",              "names": {"zh-CN": "泰语", "zh-TW": "泰語", "en": "Thai"}, "region": "asia-south"},
    {"code": "vi",  "autonym": "Tiếng Việt",       "names": {"zh-CN": "越南语", "zh-TW": "越南語", "en": "Vietnamese"}, "region": "asia-south"},
    {"code": "fil", "autonym": "Tagalog",          "names": {"zh-CN": "他加禄语", "zh-TW": "他加祿語", "en": "Tagalog"}, "region": "asia-south"},
    {"code": "jv",  "autonym": "Basa Jawa",        "names": {"zh-CN": "爪哇语", "zh-TW": "爪哇語", "en": "Javanese"}, "region": "asia-south"},
    {"code": "su",  "autonym": "Basa Sunda",       "names": {"zh-CN": "巽他语", "zh-TW": "巽他語", "en": "Sundanese"}, "region": "asia-south"},
    {"code": "km",  "autonym": "ខ្មែរ",             "names": {"zh-CN": "高棉语", "zh-TW": "高棉語", "en": "Khmer"}, "region": "asia-south"},
    {"code": "lo",  "autonym": "ລາວ",              "names": {"zh-CN": "老挝语", "zh-TW": "寮語", "en": "Lao"}, "region": "asia-south"},
    {"code": "my",  "autonym": "မြန်မာဘာသာ",       "names": {"zh-CN": "缅甸语", "zh-TW": "緬甸語", "en": "Burmese"}, "region": "asia-south"},
    {"code": "si",  "autonym": "සිංහල",            "names": {"zh-CN": "僧伽罗语", "zh-TW": "僧伽羅語", "en": "Sinhala"}, "region": "asia-south"},
    {"code": "hi",  "autonym": "हिन्दी",           "names": {"zh-CN": "印地语", "zh-TW": "印地語", "en": "Hindi"}, "region": "asia-south"},
    {"code": "bn",  "autonym": "বাংলা",            "names": {"zh-CN": "孟加拉语", "zh-TW": "孟加拉語", "en": "Bengali"}, "region": "asia-south"},
    {"code": "ur",  "autonym": "اردو",             "names": {"zh-CN": "乌尔都语", "zh-TW": "烏爾都語", "en": "Urdu"}, "region": "asia-south"},
    {"code": "ta",  "autonym": "தமிழ்",            "names": {"zh-CN": "泰米尔语", "zh-TW": "坦米爾語", "en": "Tamil"}, "region": "asia-south"},
    {"code": "te",  "autonym": "తెలుగు",           "names": {"zh-CN": "泰卢固语", "zh-TW": "泰盧固語", "en": "Telugu"}, "region": "asia-south"},
    {"code": "mr",  "autonym": "मराठी",            "names": {"zh-CN": "马拉地语", "zh-TW": "馬拉地語", "en": "Marathi"}, "region": "asia-south"},
    {"code": "gu",  "autonym": "ગુજરાતી",          "names": {"zh-CN": "古吉拉特语", "zh-TW": "古吉拉特語", "en": "Gujarati"}, "region": "asia-south"},
    {"code": "kn",  "autonym": "ಕನ್ನಡ",            "names": {"zh-CN": "卡纳达语", "zh-TW": "卡納達語", "en": "Kannada"}, "region": "asia-south"},
    {"code": "ml",  "autonym": "മലയാളം",           "names": {"zh-CN": "马拉雅拉姆语", "zh-TW": "馬拉雅拉姆語", "en": "Malayalam"}, "region": "asia-south"},
    {"code": "pa",  "autonym": "ਪੰਜਾਬੀ",           "names": {"zh-CN": "旁遮普语", "zh-TW": "旁遮普語", "en": "Punjabi"}, "region": "asia-south"},
    {"code": "ne",  "autonym": "नेपाली",           "names": {"zh-CN": "尼泊尔语", "zh-TW": "尼泊爾語", "en": "Nepali"}, "region": "asia-south"},
    {"code": "sa",  "autonym": "संस्कृतम्",        "names": {"zh-CN": "梵语", "zh-TW": "梵語", "en": "Sanskrit"}, "region": "asia-south"},
    {"code": "dz",  "autonym": "རྫོང་ཁ",           "names": {"zh-CN": "宗喀语", "zh-TW": "宗喀語", "en": "Dzongkha"}, "region": "asia-south"},

    # ---- 中亚与西亚 ----
    {"code": "tr",  "autonym": "Türkçe",           "names": {"zh-CN": "土耳其语", "zh-TW": "土耳其語", "en": "Turkish"}, "region": "asia-west"},
    {"code": "az",  "autonym": "Azərbaycanca",     "names": {"zh-CN": "阿塞拜疆语", "zh-TW": "亞塞拜然語", "en": "Azerbaijani"}, "region": "asia-west"},
    {"code": "kk",  "autonym": "Қазақша",          "names": {"zh-CN": "哈萨克语", "zh-TW": "哈薩克語", "en": "Kazakh"}, "region": "asia-west"},
    {"code": "uz",  "autonym": "Oʻzbekcha",        "names": {"zh-CN": "乌兹别克语", "zh-TW": "烏茲別克語", "en": "Uzbek"}, "region": "asia-west"},
    {"code": "ky",  "autonym": "Кыргызча",         "names": {"zh-CN": "吉尔吉斯语", "zh-TW": "吉爾吉斯語", "en": "Kyrgyz"}, "region": "asia-west"},
    {"code": "tg",  "autonym": "Тоҷикӣ",           "names": {"zh-CN": "塔吉克语", "zh-TW": "塔吉克語", "en": "Tajik"}, "region": "asia-west"},
    {"code": "tk",  "autonym": "Türkmençe",        "names": {"zh-CN": "土库曼语", "zh-TW": "土庫曼語", "en": "Turkmen"}, "region": "asia-west"},
    {"code": "fa",  "autonym": "فارسی",            "names": {"zh-CN": "波斯语", "zh-TW": "波斯語", "en": "Persian"}, "region": "asia-west"},
    {"code": "ku",  "autonym": "Kurdî",            "names": {"zh-CN": "库尔德语", "zh-TW": "庫德語", "en": "Kurdish"}, "region": "asia-west"},
    {"code": "ps",  "autonym": "پښتو",             "names": {"zh-CN": "普什图语", "zh-TW": "普什圖語", "en": "Pashto"}, "region": "asia-west"},
    {"code": "ar",  "autonym": "العربية",          "names": {"zh-CN": "阿拉伯语", "zh-TW": "阿拉伯語", "en": "Arabic"}, "region": "asia-west"},
    {"code": "he",  "autonym": "עברית",            "names": {"zh-CN": "希伯来语", "zh-TW": "希伯來語", "en": "Hebrew"}, "region": "asia-west"},
    {"code": "hy",  "autonym": "Հայերեն",          "names": {"zh-CN": "亚美尼亚语", "zh-TW": "亞美尼亞語", "en": "Armenian"}, "region": "asia-west"},
    {"code": "ka",  "autonym": "ქართული",          "names": {"zh-CN": "格鲁吉亚语", "zh-TW": "喬治亞語", "en": "Georgian"}, "region": "asia-west"},
    {"code": "ce",  "autonym": "Нохчийн мотт",     "names": {"zh-CN": "车臣语", "zh-TW": "車臣語", "en": "Chechen"}, "region": "asia-west"},
    {"code": "av",  "autonym": "Магӏарул мацӏ",    "names": {"zh-CN": "阿瓦尔语", "zh-TW": "阿瓦爾語", "en": "Avar"}, "region": "asia-west"},
    {"code": "os",  "autonym": "Ирон æвзаг",       "names": {"zh-CN": "奥塞梯语", "zh-TW": "奧塞梯語", "en": "Ossetian"}, "region": "asia-west"},
    {"code": "ab",  "autonym": "Аԥсуа бызшәа",     "names": {"zh-CN": "阿布哈兹语", "zh-TW": "阿布哈茲語", "en": "Abkhaz"}, "region": "asia-west"},
    {"code": "tt",  "autonym": "Татарча",          "names": {"zh-CN": "鞑靼语", "zh-TW": "韃靼語", "en": "Tatar"}, "region": "asia-west"},
    {"code": "ba",  "autonym": "Башҡортса",        "names": {"zh-CN": "巴什基尔语", "zh-TW": "巴什基爾語", "en": "Bashkir"}, "region": "asia-west"},
    {"code": "cv",  "autonym": "Чӑвашла",          "names": {"zh-CN": "楚瓦什语", "zh-TW": "楚瓦什語", "en": "Chuvash"}, "region": "asia-west"},
    {"code": "udm", "autonym": "Удмурт кыл",       "names": {"zh-CN": "乌德穆尔特语", "zh-TW": "烏德穆爾特語", "en": "Udmurt"}, "region": "asia-west"},
    {"code": "myv", "autonym": "Эрзянь кель",      "names": {"zh-CN": "埃尔齐亚语", "zh-TW": "埃爾齊亞語", "en": "Erzya"}, "region": "asia-west"},
    {"code": "mdf", "autonym": "Мокшень кяль",     "names": {"zh-CN": "莫克沙语", "zh-TW": "莫克沙語", "en": "Moksha"}, "region": "asia-west"},
    {"code": "kv",  "autonym": "Коми кыв",         "names": {"zh-CN": "科米语", "zh-TW": "科米語", "en": "Komi"}, "region": "asia-west"},

    # ---- 欧洲 ----
    {"code": "en",  "autonym": "English",          "names": {"zh-CN": "英语", "zh-TW": "英語", "en": "English"}, "region": "europe"},
    {"code": "fr",  "autonym": "Français",         "names": {"zh-CN": "法语", "zh-TW": "法語", "en": "French"}, "region": "europe"},
    {"code": "de",  "autonym": "Deutsch",          "names": {"zh-CN": "德语", "zh-TW": "德語", "en": "German"}, "region": "europe"},
    {"code": "es",  "autonym": "Español",          "names": {"zh-CN": "西班牙语", "zh-TW": "西班牙語", "en": "Spanish"}, "region": "europe"},
    {"code": "pt",  "autonym": "Português",        "names": {"zh-CN": "葡萄牙语", "zh-TW": "葡萄牙語", "en": "Portuguese"}, "region": "europe"},
    {"code": "it",  "autonym": "Italiano",         "names": {"zh-CN": "意大利语", "zh-TW": "義大利語", "en": "Italian"}, "region": "europe"},
    {"code": "ru",  "autonym": "Русский",          "names": {"zh-CN": "俄语", "zh-TW": "俄語", "en": "Russian"}, "region": "europe"},
    {"code": "nl",  "autonym": "Nederlands",       "names": {"zh-CN": "荷兰语", "zh-TW": "荷蘭語", "en": "Dutch"}, "region": "europe"},
    {"code": "pl",  "autonym": "Polski",           "names": {"zh-CN": "波兰语", "zh-TW": "波蘭語", "en": "Polish"}, "region": "europe"},
    {"code": "sv",  "autonym": "Svenska",          "names": {"zh-CN": "瑞典语", "zh-TW": "瑞典語", "en": "Swedish"}, "region": "europe"},
    {"code": "no",  "autonym": "Norsk",            "names": {"zh-CN": "挪威语", "zh-TW": "挪威語", "en": "Norwegian"}, "region": "europe"},
    {"code": "da",  "autonym": "Dansk",            "names": {"zh-CN": "丹麦语", "zh-TW": "丹麥語", "en": "Danish"}, "region": "europe"},
    {"code": "fi",  "autonym": "Suomi",            "names": {"zh-CN": "芬兰语", "zh-TW": "芬蘭語", "en": "Finnish"}, "region": "europe"},
    {"code": "is",  "autonym": "Íslenska",         "names": {"zh-CN": "冰岛语", "zh-TW": "冰島語", "en": "Icelandic"}, "region": "europe"},
    {"code": "el",  "autonym": "Ελληνικά",         "names": {"zh-CN": "希腊语", "zh-TW": "希臘語", "en": "Greek"}, "region": "europe"},
    {"code": "cs",  "autonym": "Čeština",          "names": {"zh-CN": "捷克语", "zh-TW": "捷克語", "en": "Czech"}, "region": "europe"},
    {"code": "sk",  "autonym": "Slovenčina",       "names": {"zh-CN": "斯洛伐克语", "zh-TW": "斯洛伐克語", "en": "Slovak"}, "region": "europe"},
    {"code": "hu",  "autonym": "Magyar",           "names": {"zh-CN": "匈牙利语", "zh-TW": "匈牙利語", "en": "Hungarian"}, "region": "europe"},
    {"code": "ro",  "autonym": "Română",           "names": {"zh-CN": "罗马尼亚语", "zh-TW": "羅馬尼亞語", "en": "Romanian"}, "region": "europe"},
    {"code": "bg",  "autonym": "Български",        "names": {"zh-CN": "保加利亚语", "zh-TW": "保加利亞語", "en": "Bulgarian"}, "region": "europe"},
    {"code": "uk",  "autonym": "Українська",       "names": {"zh-CN": "乌克兰语", "zh-TW": "烏克蘭語", "en": "Ukrainian"}, "region": "europe"},
    {"code": "sr",  "autonym": "Српски",           "names": {"zh-CN": "塞尔维亚语", "zh-TW": "塞爾維亞語", "en": "Serbian"}, "region": "europe"},
    {"code": "hr",  "autonym": "Hrvatski",         "names": {"zh-CN": "克罗地亚语", "zh-TW": "克羅埃西亞語", "en": "Croatian"}, "region": "europe"},
    {"code": "sl",  "autonym": "Slovenščina",      "names": {"zh-CN": "斯洛文尼亚语", "zh-TW": "斯洛維尼亞語", "en": "Slovenian"}, "region": "europe"},
    {"code": "bs",  "autonym": "Bosanski",         "names": {"zh-CN": "波斯尼亚语", "zh-TW": "波士尼亞語", "en": "Bosnian"}, "region": "europe"},
    {"code": "mk",  "autonym": "Македонски",       "names": {"zh-CN": "马其顿语", "zh-TW": "馬其頓語", "en": "Macedonian"}, "region": "europe"},
    {"code": "sq",  "autonym": "Shqip",            "names": {"zh-CN": "阿尔巴尼亚语", "zh-TW": "阿爾巴尼亞語", "en": "Albanian"}, "region": "europe"},
    {"code": "lt",  "autonym": "Lietuvių",         "names": {"zh-CN": "立陶宛语", "zh-TW": "立陶宛語", "en": "Lithuanian"}, "region": "europe"},
    {"code": "lv",  "autonym": "Latviešu",         "names": {"zh-CN": "拉脱维亚语", "zh-TW": "拉脫維亞語", "en": "Latvian"}, "region": "europe"},
    {"code": "et",  "autonym": "Eesti",            "names": {"zh-CN": "爱沙尼亚语", "zh-TW": "愛沙尼亞語", "en": "Estonian"}, "region": "europe"},
    {"code": "ga",  "autonym": "Gaeilge",          "names": {"zh-CN": "爱尔兰语", "zh-TW": "愛爾蘭語", "en": "Irish"}, "region": "europe"},
    {"code": "cy",  "autonym": "Cymraeg",          "names": {"zh-CN": "威尔士语", "zh-TW": "威爾斯語", "en": "Welsh"}, "region": "europe"},
    {"code": "gd",  "autonym": "Gàidhlig",         "names": {"zh-CN": "苏格兰盖尔语", "zh-TW": "蘇格蘭蓋爾語", "en": "Scottish Gaelic"}, "region": "europe"},
    {"code": "mt",  "autonym": "Malti",            "names": {"zh-CN": "马耳他语", "zh-TW": "馬爾他語", "en": "Maltese"}, "region": "europe"},
    {"code": "ca",  "autonym": "Català",           "names": {"zh-CN": "加泰罗尼亚语", "zh-TW": "加泰隆尼亞語", "en": "Catalan"}, "region": "europe"},
    {"code": "eu",  "autonym": "Euskara",          "names": {"zh-CN": "巴斯克语", "zh-TW": "巴斯克語", "en": "Basque"}, "region": "europe"},
    {"code": "gl",  "autonym": "Galego",           "names": {"zh-CN": "加利西亚语", "zh-TW": "加利西亞語", "en": "Galician"}, "region": "europe"},
    {"code": "be",  "autonym": "Беларуская",       "names": {"zh-CN": "白俄罗斯语", "zh-TW": "白俄羅斯語", "en": "Belarusian"}, "region": "europe"},
    {"code": "yi",  "autonym": "ייִדיש",           "names": {"zh-CN": "意第绪语", "zh-TW": "意第緒語", "en": "Yiddish"}, "region": "europe"},
    {"code": "lad", "autonym": "Judeo-espanyol",   "names": {"zh-CN": "拉迪诺语", "zh-TW": "拉迪諾語", "en": "Ladino"}, "region": "europe"},
    {"code": "rom", "autonym": "Romani čhib",      "names": {"zh-CN": "罗姆语", "zh-TW": "羅姆語", "en": "Romani"}, "region": "europe"},
    {"code": "sc",  "autonym": "Sardu",            "names": {"zh-CN": "撒丁语", "zh-TW": "撒丁語", "en": "Sardinian"}, "region": "europe"},
    {"code": "oc",  "autonym": "Occitan",          "names": {"zh-CN": "奥克语", "zh-TW": "奧克語", "en": "Occitan"}, "region": "europe"},
    {"code": "br",  "autonym": "Brezhoneg",        "names": {"zh-CN": "布列塔尼语", "zh-TW": "布列塔尼語", "en": "Breton"}, "region": "europe"},
    {"code": "co",  "autonym": "Corsu",            "names": {"zh-CN": "科西嘉语", "zh-TW": "科西嘉語", "en": "Corsican"}, "region": "europe"},
    {"code": "rm",  "autonym": "Rumantsch",        "names": {"zh-CN": "罗曼什语", "zh-TW": "羅曼什語", "en": "Romansh"}, "region": "europe"},
    {"code": "fur", "autonym": "Furlan",           "names": {"zh-CN": "弗留利语", "zh-TW": "弗留利語", "en": "Friulian"}, "region": "europe"},
    {"code": "fy",  "autonym": "Frysk",            "names": {"zh-CN": "弗里斯兰语", "zh-TW": "弗里斯蘭語", "en": "Frisian"}, "region": "europe"},
    {"code": "fo",  "autonym": "Føroyskt",         "names": {"zh-CN": "法罗语", "zh-TW": "法羅語", "en": "Faroese"}, "region": "europe"},
    {"code": "se",  "autonym": "Sámegiella",       "names": {"zh-CN": "萨米语", "zh-TW": "薩米語", "en": "Sami"}, "region": "europe"},
    {"code": "nds", "autonym": "Plattdüütsch",     "names": {"zh-CN": "低地德语", "zh-TW": "低地德語", "en": "Low German"}, "region": "europe"},
    {"code": "la",  "autonym": "Latina",           "names": {"zh-CN": "拉丁语", "zh-TW": "拉丁語", "en": "Latin"}, "region": "europe"},

    # ---- 非洲 ----
    {"code": "sw",  "autonym": "Kiswahili",        "names": {"zh-CN": "斯瓦希里语", "zh-TW": "史瓦希利語", "en": "Swahili"}, "region": "africa"},
    {"code": "ha",  "autonym": "Hausa",            "names": {"zh-CN": "豪萨语", "zh-TW": "豪薩語", "en": "Hausa"}, "region": "africa"},
    {"code": "yo",  "autonym": "Yorùbá",           "names": {"zh-CN": "约鲁巴语", "zh-TW": "約魯巴語", "en": "Yoruba"}, "region": "africa"},
    {"code": "ig",  "autonym": "Igbo",             "names": {"zh-CN": "伊博语", "zh-TW": "伊博語", "en": "Igbo"}, "region": "africa"},
    {"code": "am",  "autonym": "አማርኛ",             "names": {"zh-CN": "阿姆哈拉语", "zh-TW": "阿姆哈拉語", "en": "Amharic"}, "region": "africa"},
    {"code": "ti",  "autonym": "ትግርኛ",             "names": {"zh-CN": "提格雷尼亚语", "zh-TW": "提格雷尼亞語", "en": "Tigrinya"}, "region": "africa"},
    {"code": "so",  "autonym": "Soomaali",         "names": {"zh-CN": "索马里语", "zh-TW": "索馬利語", "en": "Somali"}, "region": "africa"},
    {"code": "om",  "autonym": "Afaan Oromoo",     "names": {"zh-CN": "奥罗莫语", "zh-TW": "奧羅莫語", "en": "Oromo"}, "region": "africa"},
    {"code": "zu",  "autonym": "isiZulu",          "names": {"zh-CN": "祖鲁语", "zh-TW": "祖魯語", "en": "Zulu"}, "region": "africa"},
    {"code": "xh",  "autonym": "isiXhosa",         "names": {"zh-CN": "科萨语", "zh-TW": "科薩語", "en": "Xhosa"}, "region": "africa"},
    {"code": "rw",  "autonym": "Kinyarwanda",      "names": {"zh-CN": "卢旺达语", "zh-TW": "盧安達語", "en": "Kinyarwanda"}, "region": "africa"},
    {"code": "rn",  "autonym": "Ikirundi",         "names": {"zh-CN": "基隆迪语", "zh-TW": "基隆迪語", "en": "Kirundi"}, "region": "africa"},
    {"code": "mg",  "autonym": "Malagasy",         "names": {"zh-CN": "马达加斯加语", "zh-TW": "馬達加斯加語", "en": "Malagasy"}, "region": "africa"},
    {"code": "wo",  "autonym": "Wolof",            "names": {"zh-CN": "沃洛夫语", "zh-TW": "沃洛夫語", "en": "Wolof"}, "region": "africa"},
    {"code": "ff",  "autonym": "Fulfulde",         "names": {"zh-CN": "富拉语", "zh-TW": "富拉語", "en": "Fula"}, "region": "africa"},
    {"code": "bm",  "autonym": "Bamanankan",       "names": {"zh-CN": "班巴拉语", "zh-TW": "班巴拉語", "en": "Bambara"}, "region": "africa"},
    {"code": "ee",  "autonym": "Eʋegbe",           "names": {"zh-CN": "埃维语", "zh-TW": "埃維語", "en": "Ewe"}, "region": "africa"},
    {"code": "ak",  "autonym": "Twi",              "names": {"zh-CN": "契维语", "zh-TW": "契維語", "en": "Twi"}, "region": "africa"},
    {"code": "ny",  "autonym": "Chichewa",         "names": {"zh-CN": "齐切瓦语", "zh-TW": "齊切瓦語", "en": "Chichewa"}, "region": "africa"},
    {"code": "sn",  "autonym": "chiShona",         "names": {"zh-CN": "绍纳语", "zh-TW": "紹納語", "en": "Shona"}, "region": "africa"},
    {"code": "st",  "autonym": "Sesotho",          "names": {"zh-CN": "塞索托语", "zh-TW": "塞索托語", "en": "Southern Sotho"}, "region": "africa"},
    {"code": "tn",  "autonym": "Setswana",         "names": {"zh-CN": "茨瓦纳语", "zh-TW": "茨瓦納語", "en": "Tswana"}, "region": "africa"},
    {"code": "nso", "autonym": "Sepedi",           "names": {"zh-CN": "北索托语", "zh-TW": "北索托語", "en": "Northern Sotho"}, "region": "africa"},
    {"code": "ts",  "autonym": "Xitsonga",         "names": {"zh-CN": "聪加语", "zh-TW": "聰加語", "en": "Tsonga"}, "region": "africa"},
    {"code": "ve",  "autonym": "Tshivenḓa",        "names": {"zh-CN": "文达语", "zh-TW": "文達語", "en": "Venda"}, "region": "africa"},
    {"code": "nd",  "autonym": "isiNdebele",       "names": {"zh-CN": "恩德贝莱语", "zh-TW": "恩德貝萊語", "en": "Ndebele"}, "region": "africa"},
    {"code": "ss",  "autonym": "SiSwati",          "names": {"zh-CN": "斯瓦蒂语", "zh-TW": "史瓦帝語", "en": "Swati"}, "region": "africa"},
    {"code": "kg",  "autonym": "Kikongo",          "names": {"zh-CN": "刚果语", "zh-TW": "剛果語", "en": "Kongo"}, "region": "africa"},
    {"code": "ln",  "autonym": "Lingala",          "names": {"zh-CN": "林加拉语", "zh-TW": "林加拉語", "en": "Lingala"}, "region": "africa"},
    {"code": "lu",  "autonym": "Tshiluba",         "names": {"zh-CN": "卢巴语", "zh-TW": "盧巴語", "en": "Luba"}, "region": "africa"},
    {"code": "lg",  "autonym": "Luganda",          "names": {"zh-CN": "卢干达语", "zh-TW": "盧干達語", "en": "Luganda"}, "region": "africa"},
    {"code": "srr", "autonym": "Seereer",          "names": {"zh-CN": "塞雷尔语", "zh-TW": "塞雷爾語", "en": "Serer"}, "region": "africa"},

    # ---- 美洲 ----
    {"code": "qu",  "autonym": "Runasimi",         "names": {"zh-CN": "克丘亚语", "zh-TW": "克丘亞語", "en": "Quechua"}, "region": "americas"},
    {"code": "ay",  "autonym": "Aymar aru",        "names": {"zh-CN": "艾马拉语", "zh-TW": "艾馬拉語", "en": "Aymara"}, "region": "americas"},
    {"code": "gn",  "autonym": "Avañe'ẽ",          "names": {"zh-CN": "瓜拉尼语", "zh-TW": "瓜拉尼語", "en": "Guarani"}, "region": "americas"},
    {"code": "nah", "autonym": "Nāhuatl",          "names": {"zh-CN": "纳瓦特尔语", "zh-TW": "納瓦特爾語", "en": "Nahuatl"}, "region": "americas"},
    {"code": "yua", "autonym": "Maaya t'aan",      "names": {"zh-CN": "尤卡坦玛雅语", "zh-TW": "猶加敦馬雅語", "en": "Yucatec Maya"}, "region": "americas"},
    {"code": "quc", "autonym": "K'iche'",          "names": {"zh-CN": "基切语", "zh-TW": "基切語", "en": "K'iche'"}, "region": "americas"},
    {"code": "ote", "autonym": "Hñähñu",           "names": {"zh-CN": "奥托米语", "zh-TW": "奧托米語", "en": "Otomi"}, "region": "americas"},
    {"code": "pua", "autonym": "P'urhépecha",      "names": {"zh-CN": "普雷佩查语", "zh-TW": "普雷佩查語", "en": "Purépecha"}, "region": "americas"},
    {"code": "arn", "autonym": "Mapudungun",       "names": {"zh-CN": "马普切语", "zh-TW": "馬普切語", "en": "Mapuche"}, "region": "americas"},
    {"code": "iu",  "autonym": "ᐃᓄᒃᑎᑐᑦ",           "names": {"zh-CN": "因纽特语", "zh-TW": "因紐特語", "en": "Inuktitut"}, "region": "americas"},
    {"code": "ik",  "autonym": "Iñupiatun",        "names": {"zh-CN": "伊努皮克语", "zh-TW": "伊努皮克語", "en": "Inupiaq"}, "region": "americas"},
    {"code": "esu", "autonym": "Yugtun",           "names": {"zh-CN": "尤皮克语", "zh-TW": "尤皮克語", "en": "Yup'ik"}, "region": "americas"},
    {"code": "kl",  "autonym": "Kalaallisut",      "names": {"zh-CN": "格陵兰语", "zh-TW": "格陵蘭語", "en": "Greenlandic"}, "region": "americas"},
    {"code": "tli", "autonym": "Lingít",           "names": {"zh-CN": "特林吉特语", "zh-TW": "特林吉特語", "en": "Tlingit"}, "region": "americas"},
    {"code": "oj",  "autonym": "Anishinaabemowin", "names": {"zh-CN": "奥吉布瓦语", "zh-TW": "奧吉布瓦語", "en": "Ojibwe"}, "region": "americas"},
    {"code": "cr",  "autonym": "Nēhiyawēwin",      "names": {"zh-CN": "克里语", "zh-TW": "克里語", "en": "Cree"}, "region": "americas"},
    {"code": "nv",  "autonym": "Diné bizaad",      "names": {"zh-CN": "纳瓦霍语", "zh-TW": "納瓦荷語", "en": "Navajo"}, "region": "americas"},
    {"code": "chr", "autonym": "ᏣᎳᎩ",              "names": {"zh-CN": "切罗基语", "zh-TW": "切羅基語", "en": "Cherokee"}, "region": "americas"},
    {"code": "moh", "autonym": "Kanien'kéha",      "names": {"zh-CN": "莫霍克语", "zh-TW": "莫霍克語", "en": "Mohawk"}, "region": "americas"},
    {"code": "lkt", "autonym": "Lakȟótiyapi",      "names": {"zh-CN": "拉科塔语", "zh-TW": "拉科塔語", "en": "Lakota"}, "region": "americas"},
    {"code": "cho", "autonym": "Chahta",           "names": {"zh-CN": "乔克托语", "zh-TW": "喬克托語", "en": "Choctaw"}, "region": "americas"},
    {"code": "zun", "autonym": "Shiwi'ma",         "names": {"zh-CN": "祖尼语", "zh-TW": "祖尼語", "en": "Zuni"}, "region": "americas"},
    {"code": "hop", "autonym": "Hopilàvayi",       "names": {"zh-CN": "霍皮语", "zh-TW": "霍皮語", "en": "Hopi"}, "region": "americas"},
    {"code": "pap", "autonym": "Papiamentu",       "names": {"zh-CN": "帕皮阿门托语", "zh-TW": "帕皮阿門托語", "en": "Papiamento"}, "region": "americas"},
    {"code": "ht",  "autonym": "Kreyòl ayisyen",   "names": {"zh-CN": "海地克里奥尔语", "zh-TW": "海地克里奧爾語", "en": "Haitian Creole"}, "region": "americas"},
    {"code": "srn", "autonym": "Sranan Tongo",     "names": {"zh-CN": "苏里南汤加语", "zh-TW": "蘇里南湯加語", "en": "Sranan Tongo"}, "region": "americas"},
    {"code": "mfe", "autonym": "Kreol Morisien",   "names": {"zh-CN": "毛里求斯克里奥尔语", "zh-TW": "模里西斯克里奧爾語", "en": "Mauritian Creole"}, "region": "americas"},

    # ---- 大洋洲 ----
    {"code": "haw", "autonym": "ʻŌlelo Hawaiʻi",   "names": {"zh-CN": "夏威夷语", "zh-TW": "夏威夷語", "en": "Hawaiian"}, "region": "oceania"},
    {"code": "mi",  "autonym": "Te Reo Māori",     "names": {"zh-CN": "毛利语", "zh-TW": "毛利語", "en": "Māori"}, "region": "oceania"},
    {"code": "sm",  "autonym": "Gagana Sāmoa",     "names": {"zh-CN": "萨摩亚语", "zh-TW": "薩摩亞語", "en": "Samoan"}, "region": "oceania"},
    {"code": "to",  "autonym": "Lea faka-Tonga",   "names": {"zh-CN": "汤加语", "zh-TW": "東加語", "en": "Tongan"}, "region": "oceania"},
    {"code": "fj",  "autonym": "Na Vosa Vakaviti", "names": {"zh-CN": "斐济语", "zh-TW": "斐濟語", "en": "Fijian"}, "region": "oceania"},
    {"code": "ty",  "autonym": "Reo Tahiti",       "names": {"zh-CN": "塔希提语", "zh-TW": "大溪地語", "en": "Tahitian"}, "region": "oceania"},
    {"code": "gil", "autonym": "Taetae ni Kiribati", "names": {"zh-CN": "基里巴斯语", "zh-TW": "吉里巴斯語", "en": "Gilbertese"}, "region": "oceania"},
    {"code": "mah", "autonym": "Kajin M̧ajeļ",      "names": {"zh-CN": "马绍尔语", "zh-TW": "馬紹爾語", "en": "Marshallese"}, "region": "oceania"},
    {"code": "pau", "autonym": "a tekoi er a Belau", "names": {"zh-CN": "帕劳语", "zh-TW": "帛琉語", "en": "Palauan"}, "region": "oceania"},
    {"code": "cha", "autonym": "Finu' Chamoru",    "names": {"zh-CN": "查莫罗语", "zh-TW": "查莫羅語", "en": "Chamorro"}, "region": "oceania"},
    {"code": "tpi", "autonym": "Tok Pisin",        "names": {"zh-CN": "托克皮辛语", "zh-TW": "托克皮辛語", "en": "Tok Pisin"}, "region": "oceania"},
    {"code": "bi",  "autonym": "Bislama",          "names": {"zh-CN": "比斯拉马语", "zh-TW": "比斯拉馬語", "en": "Bislama"}, "region": "oceania"},
    {"code": "hmo", "autonym": "Hiri Motu",        "names": {"zh-CN": "希里莫图语", "zh-TW": "希里莫圖語", "en": "Hiri Motu"}, "region": "oceania"},

    # ---- 人工语言 ----
    {"code": "eo",  "autonym": "Esperanto",        "names": {"zh-CN": "世界语", "zh-TW": "世界語", "en": "Esperanto"}, "region": "constructed"},
]
