# -*- coding: utf-8 -*-
"""MetaPilot – Deutsches UI-Wörterbuch (de).

Deutsche Übersetzung des MetaPilot-Frontend-Wörterbuchs.
Schlüsselsatz ist identisch mit zh-CN (common / core / course / insight /
symlink / sys, zusammengeführt) – kein Schlüssel fehlt, keiner ist zusätzlich.
Alle {xxx}-Platzhalter werden unverändert beibehalten; ihre Position folgt der
natürlichen deutschen Wortstellung. Deutsche Anführungszeichen werden als
„…“ geschrieben.
"""

UI_DICT: dict[str, str] = {
  # ---- common ----
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.confirm": "Bestätigen",
  "common.delete": "Löschen",
  "common.edit": "Bearbeiten",
  "common.search": "Suchen",
  "common.create": "Erstellen",
  "common.add": "Hinzufügen",
  "common.rename": "Umbenennen",
  "common.close": "Schließen",
  "common.refresh": "Aktualisieren",
  "common.loading": "Wird geladen…",
  "common.empty": "Keine Daten",
  "common.back": "Zurück",
  "common.open": "Öffnen",
  "common.all": "Alle",
  "common.none": "Keine",
  "common.optional": "Optional",
  "common.required": "Erforderlich",
  "common.name": "Name",
  "common.description": "Beschreibung",
  "common.author": "Autor",
  "common.version": "Version",
  "common.size": "Größe",
  "common.path": "Pfad",
  "common.type": "Typ",
  "common.status": "Status",
  "common.success": "Erfolg",
  "common.failed": "Fehlgeschlagen",
  "common.error": "Fehler",
  "common.unknown": "Unbekannt",
  "common.actions": "Aktionen",
  "common.more": "Mehr",
  "common.details": "Details",
  "common.preview": "Vorschau",
  "common.enabled": "Aktiviert",
  "common.disabled": "Deaktiviert",
  "common.yes": "Ja",
  "common.no": "Nein",
  "common.seconds": "Sekunden",
  "common.minutes": "Minuten",
  "common.hours": "Stunden",
  "common.bytes": "Bytes",
  "common.language": "Sprache",

  # ---- Navigation ----
  "nav.library": "Meine Bibliothek",
  "nav.plugins": "Plugins",
  "nav.settings": "Einstellungen",
  "nav.stats": "Statistiken",
  "nav.insight": "KI-Einblicke",

  # ---- Statistik-Widgets ----
  "core.widget.topDocs": "Meistbesuchte Dokumente",
  "core.widget.heatmap": "Zugriffs-Heatmap",
  "core.widget.stayTime": "Verweildauer in Dokumenten",
  "core.widget.wordCount": "Wortanzahl des Inhalts",
  "core.widget.recentDocs": "Zuletzt besucht",

  # ---- Design-Umschaltung ----
  "core.theme.toLight": "Zum Hellmodus wechseln",
  "core.theme.toDark": "Zum Dunkelmodus wechseln",
  "core.theme.selectTheme": "Design wählen",

  # ---- Lernseite ----
  "core.learn.markedCompleted": "Als abgeschlossen markiert",
  "core.learn.unmarkedCompleted": "Markierung aufgehoben",
  "core.learn.courseDisabledWarning": "Dieses Dokument hängt vom Plugin „Kurs“ ab. Fragen und interaktive Blöcke werden als Rohdaten angezeigt. Du kannst es auf der Plugin-Seite aktivieren.",
  "core.learn.completed": "Abgeschlossen",
  "core.learn.markComplete": "Als abgeschlossen markieren",
  "core.learn.readingMode": "Dokument lesen",
  "core.learn.progressKnowledge": "{pos} / {total} Wissenspunkte",
  "core.learn.progressDoc": "{pos} / {total} Dokumente",
  "core.learn.refToDoc": "Dieser Abschnitt verweist auf das Dokument „{name}“",
  "core.learn.gotoRefDoc": "Zum referenzierten Dokument",
  "core.learn.emptySection": "Dieser Wissenspunkt hat noch keinen Inhalt",
  "core.learn.prevKnowledge": "Vorheriger Wissenspunkt",
  "core.learn.unmarkComplete": "Abschluss-Markierung aufheben",
  "core.learn.markCurrentComplete": "Diesen Wissenspunkt als abgeschlossen markieren",
  "core.learn.nextKnowledge": "Nächster Wissenspunkt",
  "core.learn.unsupportedBlock": "Derzeit nicht unterstützter Komponententyp: {type}",
  "core.learn.ref": "Referenz",
  "core.learn.choiceMultiple": "Multiple-Choice-Frage",
  "core.learn.choiceSingle": "Einfachauswahl-Frage",
  "core.learn.multiSelect": "Mehrfachauswahl möglich",
  "core.learn.singleSelect": "Einfachauswahl",
  "core.learn.submit": "Absenden",
  "core.learn.correct": "Richtige Antwort",
  "core.learn.incorrect": "Falsche Antwort",
  "core.learn.explanation": "Lösung: {text}",
  "core.learn.gradeFailed": "Bewertung fehlgeschlagen",
  "core.learn.fillBlank": "Lückentext",
  "core.learn.aiGraded": "KI-Bewertung",
  "core.learn.blankN": "Lücke {n}",
  "core.learn.accuracy": "Genauigkeit {score}%",
  "core.learn.redo": "Erneut versuchen",
  "core.learn.interactiveNoFile": "Dem interaktiven Block fehlt die file-Konfiguration",
  "core.learn.interactiveFallback": "Dynamische Interaktion",
  "core.learn.interactiveTitle": "Interaktive Demo",
  "core.learn.blockDepPrefix": "Diese Komponente (",
  "core.learn.blockDepMid": ") hängt vom Plugin „",
  "core.learn.blockDepPlugin": "“ ab (",
  "core.learn.blockDepSuffix": "), und wird ohne Aktivierung als Rohdaten angezeigt",
  "core.learn.interactiveNotRendered": "Interaktiver Block nicht gerendert",
  "core.learn.quizNotRendered": "Frage nicht gerendert",
  "core.learn.viewRaw": "Rohdaten anzeigen",
  "core.learn.shortAnswer": "Kurzantwort-Frage",
  "core.learn.answerPlaceholder": "Gib deine Antwort ein...",
  "core.learn.keywords": "Schlüsselwörter: {text}",
  "core.learn.submitGrade": "Bewertung absenden",
  "core.learn.aiFeedback": "KI-Feedback:",
  "core.learn.hint": "Hinweis: {text}",
  "core.plugin.unknown": "Unbekanntes Plugin",
  "core.plugin.course": "Kurs",

  # ---- Dokumentbibliothek ----
  "core.library.quiz": "Quiz",
  "core.library.kindCourse": "Kurs",
  "core.library.kindNote": "Notiz",
  "core.library.kindKb": "Wissensbasis",
  "core.library.kindCanvas": "Diagramm",
  "core.library.empty": "Kein Inhalt",
  "core.library.emptyLibrary": "Diese Bibliothek ist leer. Importiere auf der Startseite ein Kurspaket oder erstelle eine neue Dokumentsammlung.",
  "core.library.library": "Bibliothek",
  "core.library.deleteLibTitle": "Bibliothek löschen",
  "core.library.deleteLibDesc": "Diese Bibliothek wirklich löschen? Alle darin enthaltenen Inhalte werden mitgelöscht und können nicht wiederhergestellt werden.",
  "core.library.deletedLib": "Bibliothek gelöscht",
  "core.library.unmountTitle": "Symlink entfernen",
  "core.library.unmountNameFallback": "Dieser Symlink",
  "core.library.unmountDesc": "„{name}“ wird aus der Liste entfernt; die Dateien auf der Festplatte werden nicht gelöscht.",
  "core.library.unmount": "Entfernen",
  "core.library.unmounted": "Entfernt",
  "core.library.singleFile": "(Einzeldatei)",
  "core.library.symlink": "Symlink",
  "core.library.pluginBadge": "Plugin",
  "core.library.emptyLibraries": "Noch keine Bibliotheken. Klicke oben rechts auf „Kurspaket importieren“ oder erstelle eine neue Bibliothek.",
  "core.library.noSymlinks": "Noch keine Symlinks. Klicke rechts, um einen lokalen Ordner oder eine Datei hinzuzufügen",
  "core.library.collectionCount": "{count} Dokumentsammlungen",
  "core.library.searchPlaceholder": "Dokumentsammlungen durchsuchen...",
  "core.library.gridView": "Rasteransicht",
  "core.library.listView": "Listenansicht",
  "core.library.unitChapter": "Kapitel",
  "core.library.unitCanvas": "Canvas",
  "core.library.unitDoc": "Dokument",
  "core.library.noSearchResults": "Keine passenden Dokumentsammlungen.",
  "core.library.emptyCollections": "Diese Bibliothek hat noch keine Dokumentsammlungen. Importiere ein Kurspaket oder erstelle eine neue.",
  "core.library.selectPlaceholder": "Wähle eine Bibliothek oder einen Symlink, um den Inhalt anzusehen.",
  "core.library.newLibTitle": "Neue Bibliothek erstellen",
  "core.library.namePlaceholder": "z. B. Fachstudium",
  "core.library.descriptionOptional": "Beschreibung (optional)",
  "core.library.descPlaceholder": "Was kommt in diese Bibliothek?",
  "core.library.createdLib": "Bibliothek erstellt",
  "core.library.newCanvas": "Neues Diagramm",
  "core.library.newCanvasTitle": "Neues Diagramm",
  "core.library.newCanvasPlaceholder": "Diagrammname",
  "core.library.newCanvasDefault": "Unbenanntes Diagramm",
  "core.library.createdCanvas": "Diagramm erstellt",
  "core.library.newDoc": "Neues Dokument",
  "core.library.newDocTitle": "Neues Dokument",
  "core.library.newDocPlaceholder": "Dokumentname",
  "core.library.newDocDefault": "Unbenanntes Dokument",
  "core.library.createdDoc": "Dokument erstellt",
  "core.library.import": "Importieren",
  "core.library.importFailed": "Import fehlgeschlagen",
  "core.library.importedCourse": "Kurs „{names}“ importiert",
  "core.library.importedNote": "Notiz importiert ({count} Abschnitte)",
  "core.library.importWarning": "Einige Komponenten im importierten Inhalt hängen vom Plugin „{names}“ ab und werden ohne Aktivierung als Rohdaten angezeigt.",
  "core.library.importedCanvas": "Diagramm „{name}“ importiert",
  "core.library.importedContent": "Inhalt importiert",
  "core.library.importTitle": "Inhalt importieren",
  "core.library.importDesc": "Unterstützt MetaPilot-Dateien (.mpf/.canvas, einheitliches Format: doc=Kursinhalt, canvas=Diagramm), Kurspakete (zip) und Markdown-Notizen.",
  "core.library.tabMpf": "MetaPilot-Datei",
  "core.library.tabCourse": "Kurspaket",
  "core.library.mpfLabel": "MetaPilot-Datei (.mpf / .canvas)",
  "core.library.mpfHint": "Der Typ doc wird als Kurs/Dokument geparst; .canvas-Dateien (Obsidian Canvas) werden automatisch in Diagramme konvertiert.",
  "core.library.courseGateHint": "Kurspaket importieren (zip)",
  "core.library.courseFileLabel": "Kurspaket-Datei (.zip, mit manifest.json)",
  "core.library.noteGateHint": "Markdown-Notiz importieren",
  "core.library.noteFileLabel": "Markdown / Obsidian-Datei (.md)",

  # ---- Bearbeitungsseite ----
  "core.edit.block.markdown": "Anzeige (Markdown)",
  "core.edit.block.single_choice": "Einfachauswahl-Frage",
  "core.edit.block.multiple_choice": "Multiple-Choice-Frage",
  "core.edit.block.fill_blank": "Lückentext",
  "core.edit.block.short_answer": "Kurzantwort-Frage",
  "core.edit.block.interactive": "Interaktiver Block",
  "core.edit.block": "Komponente",
  "core.edit.collectionInfo": "Kursinformationen",
  "core.edit.summary": "Einführung",
  "core.edit.newDocName": "Neues Kapitel",
  "core.edit.newSectionName": "Neuer Wissenspunkt",
  "core.edit.deleteDocTitle": "Kapitel löschen",
  "core.edit.deleteDocDesc": "Dieses Kapitel löschen? Alle darin enthaltenen Abschnitte und Inhalte werden gelöscht und können nicht wiederhergestellt werden.",
  "core.edit.deleteSectionTitle": "Abschnitt löschen",
  "core.edit.deleteSectionDesc": "Diesen Abschnitt löschen?",
  "core.edit.deleteBlockTitle": "Komponente löschen",
  "core.edit.deleteBlockDesc": "Diese Komponente löschen?",
  "core.edit.newFolderTitle": "Neuer Ordner",
  "core.edit.newFolderDesc": "Gib den Namen des neuen Ordners ein.",
  "core.edit.newFolderPlaceholder": "z. B. Kapitelnotizen",
  "core.edit.renameFolderTitle": "Ordner umbenennen",
  "core.edit.deleteFolderTitle": "Ordner löschen",
  "core.edit.deleteFolderDesc": "Diesen Ordner löschen? Alle Unterordner und Dokumente darin werden mitgelöscht und können nicht wiederhergestellt werden.",
  "core.edit.createFailed": "Erstellung fehlgeschlagen",
  "core.edit.renameFailed": "Umbenennen fehlgeschlagen",
  "core.edit.deleteFailed": "Löschen fehlgeschlagen",
  "core.edit.moveFailed": "Verschieben fehlgeschlagen",
  "core.edit.docSettings": "Kapitel-Einstellungen",
  "core.edit.docNameLabel": "Kapitelname",
  "core.edit.docTypeStudy": "Lernkapitel",
  "core.edit.docTypeQuiz": "Quiz-Kapitel",
  "core.edit.moveDocLabel": "Zielordner (Dokument verschieben)",
  "core.edit.rootFolder": "Stammverzeichnis",
  "core.edit.docTypeHint": "Lernkapitel und Quiz-Kapitel können frei kombiniert werden, um Lernen und Prüfung zu trennen.",
  "core.edit.sectionSettings": "Wissenspunkt-Einstellungen",
  "core.edit.sectionNameLabel": "Name des Wissenspunkts",
  "core.edit.refDocLabel": "Anderes Dokument referenzieren (Abschnittsreferenz)",
  "core.edit.noRef": "Keine Referenz",
  "core.edit.refDocHint": "Bei einer Referenz zeigt die Lernseite eine Referenzkarte an und springt zum Zieldokument.",
  "core.edit.addBlockLabel": "Komponente hinzufügen",
  "core.edit.backToSection": "Zurück zum Abschnitt",
  "core.edit.blockSaved": "Komponente gespeichert",
  "core.edit.addSectionTitle": "Neuer Abschnitt",
  "core.edit.noBlocks": "Keine Komponenten",
  "core.edit.noSections": "Keine Abschnitte",
  "core.edit.subFolder": "Unterordner",
  "core.edit.emptyFolder": "Leerer Ordner",
  "core.edit.mode": "Bearbeitungsmodus",
  "core.edit.dirty": "Ungespeicherte Änderungen",
  "core.edit.saved": "Gespeichert",
  "core.edit.newDoc": "Kapitel",
  "core.edit.newFolder": "Ordner",
  "core.edit.done": "Fertig",
  "core.edit.markdownContent": "Markdown-Inhalt",
  "core.edit.markdownPlaceholder": "# Titel\n\nTextinhalt, Markdown sowie GFM-Tabellen/Aufgabenlisten werden unterstützt",
  "core.edit.question": "Frage",
  "core.edit.options": "Optionen (eine pro Zeile)",
  "core.edit.optionsPlaceholder": "Option A\nOption B\nOption C",
  "core.edit.correctIndex": "Index der richtigen Option (ab 0)",
  "core.edit.correctIndexes": "Indizes der richtigen Optionen (kommagetrennt)",
  "core.edit.blanksAnswers": "Referenzantworten für jede Lücke (eine Lücke pro Zeile)",
  "core.edit.blanksPlaceholder": "Antwort 1\nAntwort 2",
  "core.edit.reference": "Referenzantwort",
  "core.edit.keywordsLabel": "Schlüsselwörter (kommagetrennt, als Referenz für die KI)",
  "core.edit.keywordsPlaceholder": "Schlüsselwort1,Schlüsselwort2",
  "core.edit.aiGraded": "KI-Bewertung verwenden (subjektive Fragen)",
  "core.edit.title": "Titel",
  "core.edit.assetFile": "Asset-Datei (Pfad relativ zum interactives/-Ordner des Kurspakets)",
  "core.edit.iframeHeight": "iframe-Höhe (px)",
  "core.edit.explanationLabel": "Lösung / Hinweis (optional)",

  # ---- Diagramm-Canvas ----
  "core.canvas.saved": "Canvas gespeichert",
  "core.canvas.saveFailed": "Speichern fehlgeschlagen",
  "core.canvas.doubleClickEdit": "Doppelklick zum Bearbeiten des Texts",
  "core.canvas.notCanvas": "Diese Dokumentsammlung ist kein Diagramm.",
  "core.canvas.backToLibrary": "Zurück zur Bibliothek",
  "core.canvas.badge": "Diagramm-Canvas",
  "core.canvas.dirty": "Ungespeicherte Änderungen",
  "core.canvas.unsavedTitle": "Ungespeicherte Änderungen",
  "core.canvas.unsavedDesc": "Das Diagramm hat ungespeicherte Änderungen. Vor dem Schließen speichern?",
  "core.canvas.discardAndLeave": "Nicht speichern und verlassen",
  "core.canvas.saveAndLeave": "Speichern und verlassen",
  "core.canvas.newTextNode": "Neuer Textknoten",
  "core.canvas.help": "Knoten per Ziehen verschieben, leere Fläche anklicken zum Auswählen, Umschalt für Mehrfachauswahl, Entf zum Löschen, Strg+C/V zum Kopieren/Einfügen, Strg+Z zum Rückgängigmachen; Doppelklick auf Text zum Bearbeiten; von einem Verbindungspunkt am Knotenrand zu einem anderen Knoten ziehen, um eine Verbindung zu erstellen; Mausrad zum Verschieben, Strg+Mausrad zum Zoomen, Leertaste gedrückt halten und ziehen zum Verschieben.",
  "core.canvas.undo": "Rückgängig (Strg+Z)",
  "core.canvas.redo": "Wiederholen (Strg+Umschalt+Z)",
  "core.canvas.zoomOut": "Verkleinern",
  "core.canvas.zoomIn": "Vergrößern",
  "core.canvas.fitView": "An Canvas anpassen",
  "core.canvas.empty": "(leer)",
  "core.canvas.group": "Gruppe",
  "core.canvas.deleteNode": "Knoten löschen",
  "core.canvas.dragLink": "Verbindung ziehen",
  "core.canvas.emptyBoard": "Leeres Canvas. Klicke oben rechts auf „Neuer Textknoten“, um zu beginnen",
  "core.canvas.stats": "{nodes} Knoten · {edges} Verbindungen",
  "core.canvas.exportMpf": ".mpf exportieren",
  "core.canvas.exportCanvas": ".canvas exportieren",
  "core.canvas.export": "Exportieren",
  "core.canvas.center": "Zentrieren",
  "core.canvas.alignLeft": "Linksbündig",
  "core.canvas.alignCenter": "Zentriert",
  "core.canvas.alignRight": "Rechtsbündig",
  "core.canvas.edgePath": "Verbindungsstil",
  "core.canvas.pathSmooth": "Glatte Kurve",
  "core.canvas.pathStraight": "Gerade Linie",
  "core.canvas.pathSquare": "Rechteckiger Pfad",
  "core.canvas.resize": "Größe ändern",
  "core.canvas.groupSelection": "Gruppieren",
  "core.canvas.dragAddCard": "Karte per Ziehen hinzufügen",
  "core.canvas.dragAddNote": "Notiz per Ziehen hinzufügen",
  "core.canvas.dragAddNoteVault": "Notiz aus der Bibliothek per Ziehen hinzufügen",
  "core.canvas.dragAddMediaVault": "Medium aus der Bibliothek per Ziehen hinzufügen",
  "core.canvas.paste": "Einfügen",
  "core.canvas.toggleNav": "Navigation ein-/ausblenden",
  "core.canvas.noCanvases": "Keine Diagramme",
  "core.canvas.edgeStart": "Startpunkt",
  "core.canvas.edgeEnd": "Endpunkt",
  "core.canvas.arrow": "Pfeil",
  "core.canvas.toggleStartArrow": "Startpfeil umschalten",
  "core.canvas.toggleEndArrow": "Endpfeil umschalten",
  "core.canvas.edgeLabel": "Beschriftung",
  "core.canvas.colorTitle": "Farbe {color}",
  "core.canvas.clearColor": "Farbe entfernen",
  "core.canvas.deleteEdge": "Verbindung löschen",
  "core.canvas.addNode": "Neuer Knoten",
  "core.canvas.addNodeText": "Text",
  "core.canvas.addNodeFile": "Datei",
  "core.canvas.addNodeLink": "Link",
  "core.canvas.addNodeGroup": "Gruppe",
  "core.canvas.addFileTitle": "Dateipfad",
  "core.canvas.addFileDesc": "Relativer Pfad innerhalb der Bibliothek, z. B. notes/Beispiel.md, images/Bild.png (Obsidian-kompatibel)",
  "core.canvas.addLinkTitle": "Link-URL",
  "core.canvas.addGroupTitle": "Gruppen-Beschriftung",
  "core.canvas.groupName": "Gruppenname",

  # ---- Statistikseite ----
  "core.stats.intro": "Der offizielle Kern bietet grundlegende Statistik-Widgets; Plugins wie Kurs können weitere Widgets beisteuern. Karten ziehen, um die Position zu ändern, oben rechts die Größe anpassen; in den Einstellungen kannst du „Widget-Quelle markieren“ umschalten.",
  "core.stats.resize": "Größe ändern (aktuell {size})",
  "core.stats.hide": "Widget ausblenden",
  "core.stats.manage": "Widgets verwalten",
  "core.stats.hiddenCount": "{count} ausgeblendet",
  "core.stats.manageDesc": "Blende unter „Sichtbar“ Widgets aus oder stelle sie im Bereich „Ausgeblendet“ jederzeit wieder her; ziehe Karten auf der Statistikseite, um Position und Reihenfolge anzupassen.",
  "core.stats.none": "Derzeit keine Statistik-Widgets verfügbar",
  "core.stats.visibleCount": "Sichtbar ({count})",
  "core.stats.hiddenTab": "Ausgeblendet ({count})",
  "core.stats.noHidden": "Keine ausgeblendeten Widgets, alle werden angezeigt",
  "core.stats.resetLayout": "Standardlayout wiederherstellen",
  "core.stats.showAll": "Alle anzeigen",
  "core.stats.restore": "Wiederherstellen",
  "core.stats.noVisits": "Keine Zugriffsaufzeichnungen",
  "core.stats.noStayTime": "Keine Verweildauer-Aufzeichnungen",
  "core.stats.visits": "{count} Zugriffe",
  "core.stats.wordUnit": "Wörter",
  "core.stats.unknownWidget": "Unbekanntes Widget",
  "core.stats.heatmap3m": "Zugriffs-Heatmap der letzten 3 Monate",
  "core.stats.heatmapTooltip": "{day}.{month}. · {count} Zugriffe",
  "core.stats.heatmapLess": "Wenig",
  "core.stats.heatmapMore": "Viel",
  "core.stats.hourly": "Zugriffsverteilung nach Stunde",
  "core.stats.hourTooltip": "{hour} Uhr · {count} Zugriffe",
  "core.stats.hourLabel": "{hour} Uhr",
  "core.stats.monthLabel": "Monat {month}",
  "core.stats.weekdays": "Mo,Di,Mi,Do,Fr,Sa,So",
  "core.stats.courseDisabled": "Hängt vom Plugin „Kurs“ ab, nicht aktiviert",
  "core.stats.totalStudy": "Gesamtes Lernen",
  "core.stats.chartMinutes": "Minuten",
  "core.stats.noStudyRecords": "Keine Lernaufzeichnungen",
  "core.stats.providedBy": "Bereitgestellt von Plugin „{name}“",
  "core.stats.providedByTooltip": "Von Plugin „{name}“ bereitgestellt",

  # ---- Allgemeine Dialoge / Toasts ----
  "core.dialog.selectPlaceholder": "Bitte auswählen…",
  "core.toast.copied": "In die Zwischenablage kopiert",
  "core.widget.aiUsage": "KI-Nutzung",
  "core.stats.rangeToday": "Heute",
  "core.stats.rangeWeek": "Diese Woche",
  "core.stats.rangeMonth": "Dieser Monat",
  "core.stats.rangeAll": "Alle",
  "core.stats.aiCalls": "Anzahl der Aufrufe",
  "core.stats.aiTokens": "Token-Nutzung",
  "core.stats.aiCost": "Kosten",
  "core.stats.aiTokensDetail": "Eingabe {in} / Cache {cached} / Ausgabe {out}",
  "core.stats.aiCallsShort": "{n} Aufrufe",
  "core.stats.aiTokensShort": "{n} Tokens",
  "core.stats.aiUsageEmpty": "Noch keine KI-Nutzungsdaten (Aufrufe der Plugins über das einheitliche Gateway werden hier aufgezeichnet).",

  # ---- course ----
  "course.exportFailed": "Export fehlgeschlagen",
  "course.pluginDisabledWarning": "Dieses Dokument hängt vom Plugin „Kurs“ ab. Lernfortschritt und Frage-Interaktionen sind nicht verfügbar. Du kannst es auf der Plugin-Seite aktivieren.",
  "course.backToLibrary": "Zurück zur Bibliothek",
  "course.noDescription": "Keine Einführung",
  "course.authorLabel": "Autor: {author}",
  "course.export": "Exportieren",
  "course.continueLearning": "Weiterlernen",
  "course.learningProgress": "Lernfortschritt",
  "course.progressCount": "{completed} / {total} Wissenspunkte",
  "course.lastLearned": "Zuletzt gelernt: {name}",
  "course.progressRequiresPlugin": "Der Lernfortschritt hängt vom Plugin „Kurs“ ab. Nach der Aktivierung kannst du Abschlüsse markieren und die letzte Lernposition wird gespeichert.",
  "course.quiz": "Quiz",
  "course.noSectionsInChapter": "Dieses Kapitel hat noch keine Abschnitte",
  "course.noChapters": "Dieser Kurs hat noch keine Kapitel. Klicke oben rechts auf „Bearbeiten“, um zu beginnen.",
  "course.library.newCourse": "Neuer Kurs",
  "course.library.newCourseTitle": "Neuer Kurs",
  "course.library.newCoursePlaceholder": "Kursname",
  "course.library.newCourseDefault": "Unbenannter Kurs",
  "course.library.createdCourse": "Kurs erstellt",
  "course.library.createCourseFailed": "Kurserstellung fehlgeschlagen",
  "course.library.toCourse": "In Kurs umwandeln",
  "course.library.toCourseTitle": "In Kurs umwandeln",
  "course.library.toCourseDesc": "„{name}“ in einen Kurs umwandeln? Ein Kurs ist ein gepatchtes Dokument, das Lernfortschritt, Bewertung und interaktive Blöcke ermöglicht; ohne aktiviertes Plugin „Kurs“ sind diese Kursfunktionen nicht verfügbar.",
  "course.library.toCourseConfirm": "In Kurs umwandeln",
  "course.library.convertedCourse": "„{name}“ wurde in einen Kurs umgewandelt",
  "course.library.convertCourseFailed": "Umwandlung in Kurs fehlgeschlagen",

  # ---- insight ----
  "insight.pageTitle": "KI-Einblicke",
  "insight.intro": "Wähle eine Reihe von Dokumenten oder Bibliotheken aus, erstelle einen Index und gib sie der KI zum Nachdenken: Sie recherchiert die Zusammenhänge zwischen den Materialien und erzeugt Antworten, Empfehlungen oder Diagramme/Kurse in vier Modi.",
  "insight.introWithSymlink": "Wähle eine Reihe von Dokumenten, Bibliotheken oder lokalen Verzeichnissen aus, erstelle einen Index und gib sie der KI zum Nachdenken: Sie recherchiert die Zusammenhänge zwischen den Materialien und erzeugt Antworten, Empfehlungen oder Diagramme/Kurse in vier Modi.",
  "insight.stepIndex": "Schritt 1 · Index erstellen",
  "insight.stepAsk": "Schritt 2 · KI fragen",
  "insight.stepIndexQuoted": "„Schritt 1 · Index erstellen“",
  "insight.mustIndexBefore": "Erstelle zuerst einen Index und stelle dann Fragen; wenn du direkt fragst, wird der Index automatisch erstellt (mit Fortschrittsanzeige).",
  "insight.noIndexedBefore": "Es gibt noch keine indexierten Datenquellen. Gehe bitte zuerst zu",
  "insight.noIndexedAfter": " und erstelle für die ausgewählten Inhalte einen Vektorindex, bevor du fragst.",
  "insight.noIndexedAfterWithSymlink": " und erstelle für die ausgewählten Dokumente / lokalen Verzeichnisse einen Vektorindex, bevor du fragst.",
  "insight.vectorModelTitle": "Vektormodell und lokaler Dienst",
  "insight.embeddingRunning": "Läuft",
  "insight.embeddingNotReady": "Nicht bereit",
  "insight.selectModelPlaceholder": "Embedding-Modell wählen",
  "insight.stopService": "Dienst beenden",
  "insight.startService": "Dienst starten (das gewählte Modell wird beim ersten Mal automatisch heruntergeladen)",
  "insight.modelDownloadHint": "Der Modell-Download versucht automatisch mehrere Wege; beim ersten Download musst du warten, bis das Modell bereit ist. Die Seite aktualisiert den Status automatisch. Download-Quellen und Modellliste richten sich nach der Backend-Konfiguration.",
  "insight.selectSourcesTitle": "Datenquellen wählen (Mehrfachauswahl möglich)",
  "insight.indexIntro": "Auswahl nach Bibliothek, einzelner Dokumentsammlung oder einzelnem Dokument möglich; Indizes werden pro Datenquelle separat gespeichert.",
  "insight.indexIntroWithSymlink": "Auswahl nach Bibliothek, Dokumentsammlung oder Dokument möglich, auch ein ganzes lokales Verzeichnis oder ein beliebiger Pfad darin; Indizes werden pro Datenquelle separat gespeichert.",
  "insight.indexing": "Wird indexiert...",
  "insight.indexingProgress": "{done}/{total} Abschnitte indexiert",
  "insight.indexQueued": "Indexerstellung gestartet, Fortschritt unten einsehbar",
  "insight.buildVectorIndex": "Vektorindex erstellen",
  "insight.noSources": "Keine Datenquellen verfügbar: Erstelle zuerst in „Meine Bibliothek“ eine Bibliothek.",
  "insight.noSourcesWithSymlink": "Keine Datenquellen verfügbar: Erstelle zuerst in „Meine Bibliothek“ eine Bibliothek oder mounte ein lokales Verzeichnis.",
  "insight.askSourcesTitle": "Datenquellen zum Nachdenken wählen (Mehrfachauswahl möglich, kombinierte Suche)",
  "insight.askTitle": "KI-Nachdenken (Antworten mit Quellenangaben)",
  "insight.askPlaceholder": "Frage die KI, z. B.: „Welche Zusammenhänge gibt es zwischen diesen Materialien?“",
  "insight.refSources": "Referenzquellen",
  "insight.sourceRef": "[Quelle{n}]",
  "insight.asking": "Suche läuft und Antwort wird erzeugt...",
  "insight.inputPlaceholder": "Gib deine Frage oder Denkrichtung ein...",
  "insight.askButton": "Fragen",
  "insight.groupLibrary": "Bibliotheksdokumente (Bibliothek / Dokumentsammlung / Dokument)",
  "insight.groupSymlink": "Lokale Verzeichnis-Mounts",
  "insight.indexedCount": "{count} Abschnitte indexiert",
  "insight.notIndexed": "Nicht indexiert",
  "insight.pluginHint": "KI-Einblicke: Zusammenhänge analysieren und Inhalte erzeugen",
  "insight.loadResourcesFailed": "Laden der Datenquellen fehlgeschlagen",
  "insight.startServiceToast": "Dienst wird gestartet (beim ersten Mal wird das gewählte Modell automatisch heruntergeladen)",
  "insight.startFailed": "Start fehlgeschlagen",
  "insight.serviceStopped": "Dienst beendet",
  "insight.indexDone": "Indexierung abgeschlossen: {ok}/{total} Datenquellen",
  "insight.indexFailed": "Indexierung fehlgeschlagen",
  "insight.askFailed": "Frage fehlgeschlagen",
  "insight.modeTitle": "Denkmodus",
  "insight.modeIntro": "Wähle eine Denkweise; die KI recherchiert nach dieser Weise in den ausgewählten Materialien und erzeugt Inhalte.",
  "insight.modeAssist": "Denkhilfe",
  "insight.modeAssistDesc": "Zusammenhänge zwischen den Materialien finden, Antworten und Empfehlungen geben",
  "insight.modeWander": "Gedankenreise",
  "insight.modeWanderDesc": "Kombiniert Materialien mit deiner Denkrichtung für freies Assoziieren",
  "insight.modeReflect": "Reflexion & Zusammenfassung",
  "insight.modeReflectDesc": "Zusammenhänge und blinde Flecken zusammenfassen, die du vielleicht übersehen hast",
  "insight.modePlan": "Insight-Planung",
  "insight.modePlanDesc": "Mehrstufige Überlegung, Diagramme oder Kurse zur Vermittlung erzeugen",
  "insight.planOutputTitle": "Erzeugungstyp",
  "insight.planOutputCanvas": "Wissensdiagramm (Canvas)",
  "insight.planOutputCourse": "Mikrokurs (Dokument)",
  "insight.planLibraryTitle": "In Bibliothek speichern",
  "insight.planLibraryAuto": "Standardbibliothek (erste)",
  "insight.planGoalPlaceholder": "Gib das Planungsziel ein, z. B.: Ordne die Kernkonzepte und Zusammenhänge dieser Materialien und bring mir bei, sie in kürzester Zeit zu verstehen",
  "insight.planButton": "Insight-Planung starten",
  "insight.planning": "Die KI analysiert die Materialzusammenhänge in mehreren Runden und erzeugt Inhalte; das kann 1–2 Minuten dauern...",
  "insight.planDone": "„{name}“ erzeugt",
  "insight.planOpenCanvas": "Diagramm öffnen",
  "insight.planOpenCourse": "Kurs öffnen",
  "insight.planSummary": "Planungsübersicht",
  "insight.planFailed": "Insight-Planung fehlgeschlagen",
  "insight.planRoadmap": "KI-Ausführungsplan",
  "insight.planThinking": "KI-Denkprozess",
  "insight.planStep.retrieve": "Materialien abrufen",
  "insight.planStep.plan": "Themen- und Zusammenhangsanalyse",
  "insight.planStep.review": "Kritisches Reflektieren",
  "insight.planStep.generateCanvas": "Wissensdiagramm erzeugen",
  "insight.planStep.generateCourse": "Mikrokurs erzeugen",
  "insight.planStep.save": "In Bibliothek speichern",
  "insight.planStepRunning": "Läuft…",
  "insight.planConnecting": "Verbinde mit KI und plane den Ausführungsplan…",
  "insight.autoIndexing": "Die gewählten Datenquellen sind noch nicht indexiert; der Index wird automatisch erstellt ({done}/{total})...",
  "insight.autoIndexDone": "Indexierung abgeschlossen, Erzeugung läuft...",
  "insight.autoIndexFailed": "Automatische Indexierung fehlgeschlagen. Erstelle den Index bitte zuerst manuell in Schritt 1",
  "insight.symlinkBrowse": "Verzeichnis durchsuchen",
  "insight.treeEmpty": "(leer)",
  "insight.kbTitle": "Daten-Retrieval-Bibliothek",
  "insight.goAsk": "Fragen stellen",
  "insight.selectedCount": "{count} ausgewählt",
  "insight.kbIndexed": "{count} Quellen indexiert",
  "insight.collapsePanel": "Daten-Retrieval-Panel einklappen",
  "insight.expandPanel": "Daten-Retrieval-Panel ausklappen",
  "insight.kbHint": "Kreuze Bibliotheken / Dokumentsammlungen / Dokumente als Suchbereich an: Du kannst Indizes erstellen oder direkt fragen; nicht indexierte Quellen werden beim Fragen automatisch indexiert.",
  "insight.kbHintWithSymlink": "Kreuze Bibliotheken / Dokumentsammlungen / Dokumente oder lokale Verzeichnisse als Suchbereich an: Du kannst Indizes erstellen oder direkt fragen; nicht indexierte Quellen werden beim Fragen automatisch indexiert.",
  "insight.buildIndexTitle": "Vektorindex erstellen",
  "insight.buildIndexHint": "{count} Datenquellen ausgewählt (im linken Panel „Daten-Retrieval-Bibliothek“ anpassbar); nicht indexierte werden mit erstellt.",

  # ---- symlink ----
  "symlink.fileBrowser": "Dateibrowser",
  "symlink.symlinkPlugin": "Symlink-Plugin",
  "symlink.pluginHint": "Lokale Verzeichnisse durchsuchen und lesen/schreiben",
  "symlink.linkLocalDoc": "Lokales Dokument verknüpfen (Symlink)",
  "symlink.addMountDesc1": "Verknüpft werden ",
  "symlink.addMountDesc2": " oder ",
  "symlink.addMountDesc3": " auf der lokalen Festplatte; die Originaldateien werden nicht kopiert oder verschoben. Nach der Verknüpfung kannst du sie im Dateibrowser wie Dokumente durchsuchen, lesen und bearbeiten.",
  "symlink.mounts": "Mounts",
  "symlink.mount": "Mounten",
  "symlink.thatMount": "Dieser Mount",
  "symlink.unmount": "Entfernen",
  "symlink.unmountSymlink": "Symlink entfernen",
  "symlink.unmountConfirmDesc": "„{name}“ wird aus der Liste entfernt; die Dateien auf der Festplatte werden nicht gelöscht.",
  "symlink.noMounts": "Noch keine Mounts. Klicke oben rechts, um einen lokalen Ordner oder eine Datei hinzuzufügen",
  "symlink.currentMountRoot": "Aktueller Mount-Stamm: {root}",
  "symlink.pleaseMount": "Bitte zuerst einen lokalen Ordner oder eine Datei mounten",
  "symlink.mountSuccess": "Mount erfolgreich",
  "symlink.mountFailed": "Mount fehlgeschlagen",
  "symlink.displayName": "Anzeigename",
  "symlink.namePlaceholder": "z. B. Meine Notizen",
  "symlink.localPathLabel": "Lokaler Pfad (Ordner oder Datei)",
  "symlink.pathPlaceholder": "Klicke auf „Durchsuchen“ oder gib den Pfad manuell ein (Windows/Linux werden unterstützt)",
  "symlink.collapse": "Einklappen",
  "symlink.browse": "Durchsuchen",
  "symlink.afterMountHint": "Nach dem Mounten kannst du Textdateien im Verzeichnis über den Dateibrowser durchsuchen, lesen und bearbeiten (der Zugriff ist auf den Mount-Stamm beschränkt).",
  "symlink.directory": "Verzeichnis",
  "symlink.folder": "Ordner",
  "symlink.file": "Datei",
  "symlink.singleFile": "Einzeldatei",
  "symlink.singleFileNote": "(Einzeldatei)",
  "symlink.singleFileMount": "(Einzeldatei-Mount)",
  "symlink.rootDir": "(Stammverzeichnis)",
  "symlink.noSubfolders": "Keine Unterordner",
  "symlink.emptyDir": "Leeres Verzeichnis",
  "symlink.expandDir": "Verzeichnis ausklappen",
  "symlink.collapseDir": "Verzeichnis einklappen",
  "symlink.newFolder": "Neuer Ordner",
  "symlink.newFolderDesc": "Gib den Namen des neuen Ordners ein.",
  "symlink.newFolderPlaceholder": "z. B. Kapitelnotizen",
  "symlink.searchPlaceholder": "Suchen…",
  "symlink.gridView": "Rasteransicht",
  "symlink.listView": "Listenansicht",
  "symlink.backToList": "Zurück zur Liste",
  "symlink.reveal": "Anzeigen",
  "symlink.revealInFileManager": "Im Dateimanager anzeigen",
  "symlink.openWithDefault": "Mit Standardanwendung öffnen",
  "symlink.editing": "Bearbeiten: {path}",
  "symlink.saved": "Gespeichert",
  "symlink.saveFailed": "Speichern fehlgeschlagen",
  "symlink.createFailed": "Erstellung fehlgeschlagen",
  "symlink.deleteFile": "Datei löschen",
  "symlink.deleteConfirmDesc": "„{target}“ wirklich löschen?",
  "symlink.deleteDirWarning": "Der Ordner wird rekursiv gelöscht und kann nicht wiederhergestellt werden.",
  "symlink.deleteFailed": "Löschen fehlgeschlagen",
  "symlink.openedWithDefault": "Mit der System-Standardanwendung geöffnet",
  "symlink.openFailed": "Öffnen fehlgeschlagen",
  "symlink.readFailed": "Lesen fehlgeschlagen",
  "symlink.noInlinePreview": "Dieser Dateityp unterstützt keine Inline-Vorschau",
  "symlink.noInlinePreviewHint": "Dieser Dateityp unterstützt keine Inline-Vorschau. Klicke mit der rechten Maustaste und wähle „Mit Standardanwendung öffnen“",
  "symlink.noMatch": "Keine passenden Einträge.",
  "symlink.goUp": "Eine Ebene höher",
  "symlink.myComputer": "Dieser PC",
  "symlink.reading": "Wird gelesen…",
  "symlink.emptyFolder": "Leerer Ordner",
  "symlink.selectedFolder": "Ordner: {path}",
  "symlink.selectedFile": "Datei: {path}",
  "symlink.selectHint": "Klicke einmal, um einen Ordner oder eine Datei auszuwählen; doppelklicke auf einen Ordner, um ihn zu öffnen",
  "symlink.selectThisFolder": "Diesen Ordner wählen",
  "symlink.selectThisFile": "Diese Datei wählen",

  # ---- sys ----
  "sys.title": "Einstellungen",
  "sys.subtitle": "Steuert das Hinweisverhalten rund um Plugins. MetaPilot ist eine Dokumentbibliothek: Dokumente können immer geöffnet und angesehen werden; nicht gerenderte Teile werden als Rohdaten angezeigt. Hinweise dienen nur der Erinnerung und unterbrechen keine Aktionen.",
  "sys.language": "Sprache",
  "sys.languageDesc": "Anzeigesprache der Oberfläche; Änderungen wirken sofort und werden lokal gespeichert (localStorage).",
  "sys.appearance": "Darstellung",
  "sys.appearanceDesc": "Dunkel-/Hellmodus jederzeit umschaltbar; spezielle Designs werden vom Plugin „Designs“ bereitgestellt (nach Aktivierung in der Plugin-Verwaltung installierbar).",
  "sys.pluginWarnings": "Plugin-Warnhinweise",
  "sys.pluginWarningsDesc": "Beim Öffnen eines Dokuments, das von einem deaktivierten Plugin abhängt (z. B. Kurs, Wissensbasis), wird oben ein Warnhinweis angezeigt: „Dieser Inhalt hängt vom Plugin xx ab, einige Komponenten können möglicherweise nicht gerendert werden.“",
  "sys.pluginErrors": "Plugin-Fehlermeldungen",
  "sys.pluginErrorsDesc": "Schlägt eine Aktion fehl, weil ein Plugin nicht aktiviert ist (z. B. KI-Bewertung, Wissensbasis-Fragen), wird oben eine Fehlermeldung angezeigt; nach dem Schließen werden solche Fehler still ignoriert.",
  "sys.componentSource": "Komponentenquelle markieren",
  "sys.componentSourceDesc": "Wenn aktiviert, werden von Plugins bereitgestellte Komponenten/Inhalte auf Bibliotheks- und Statistikseiten mit einem Plugin-Symbol markiert (der Plugin-Name ist bei Hover sichtbar); der offizielle Kern (MetaPilot selbst) wird nicht markiert. Bei Deaktivierung werden keine Quellmarkierungen angezeigt.",
  "sys.localOnly": "Hinweise werden nur lokal im Browser gespeichert (localStorage) und beeinflussen keine anderen Geräte.",
  "sys.plugins.title": "Plugin-Verwaltung",
  "sys.plugins.headerPrefix": "Plugins gliedern sich in benutzerdefinierte, offizielle und Kern-Plugins. Plugins sind eigenständige Funktionspakete im Backend-Verzeichnis ",
  "sys.plugins.headerSuffix": ", die im „Plugin-Shop“ durchsucht und installiert oder als eigene Plugins hochgeladen werden können.",
  "sys.plugins.tabLocal": "Lokale Plugins",
  "sys.plugins.tabStore": "Plugin-Shop",
  "sys.plugins.filterByTag": "Nach Tag filtern:",
  "sys.plugins.sourceUser": "Benutzerdefinierte Plugins",
  "sys.plugins.sourceUserDesc": "Selbst entwickeln, aus dem Plugin-Shop installieren oder per Zip-Upload installieren; deaktivierbar und löschbar.",
  "sys.plugins.sourceOfficial": "Offizielle Plugins",
  "sys.plugins.sourceOfficialDesc": "Von MetaPilot offiziell entwickelte praktische Plugins; optional nutzbar, deaktivierbar, aber nicht löschbar.",
  "sys.plugins.sourceCore": "Offizieller Kern",
  "sys.plugins.sourceCoreDesc": "MetaPilot selbst: Dokumentbibliothek durchsuchen und Markdown lesen. Nicht deaktivierbar oder löschbar.",
  "sys.plugins.enabledToast": "Plugin aktiviert",
  "sys.plugins.disabledToast": "Plugin deaktiviert",
  "sys.plugins.opFailed": "Vorgang fehlgeschlagen",
  "sys.plugins.deleteTitle": "Plugin löschen",
  "sys.plugins.deleteDesc": "Plugin „{name}“ löschen? Das Verzeichnis backend/plugins/{id} wird physisch gelöscht und kann nicht wiederhergestellt werden.",
  "sys.plugins.deletedToast": "Plugin „{name}“ gelöscht",
  "sys.plugins.deleteFailed": "Löschen fehlgeschlagen",
  "sys.plugins.idLabel": "id:",
  "sys.plugins.dependsOn": "Abhängige Plugins:",
  "sys.plugins.missingDeps": "Fehlende Abhängigkeiten (müssen zuerst aktiviert werden):",
  "sys.plugins.featureCourseImport": "Kurspaket-Import / -Export",
  "sys.plugins.featureCourseFlow": "Kapitel-/Wissenspunkt-Lernen (Komponentenfluss)",
  "sys.plugins.featureCourseProgress": "Lernfortschritt und Zeitstatistik",
  "sys.plugins.featureCourseGrading": "KI-Bewertung für subjektive Fragen",
  "sys.plugins.featureCourseInteractive": "Rendern interaktiver Blöcke",
  "sys.plugins.featureInsightIndex": "Mehrstufiger Vektorindex für Datenquellen (Bibliothek/Dokumentsammlung/Dokument/lokales Verzeichnis)",
  "sys.plugins.featureInsightModes": "Vier Denkmodi (Denkhilfe/Gedankenreise/Reflexion & Zusammenfassung/Insight-Planung)",
  "sys.plugins.featureInsightPlan": "Mehrstufige Überlegung erzeugt Diagramme und Mikrokurse (.mpf)",
  "sys.plugins.needEnablePrefix": "Das Plugin „",
  "sys.plugins.needEnableSuffix": "“ muss aktiviert werden, um genutzt zu werden",
  "sys.plugins.thisFeature": "Diese Funktion",
  "sys.plugins.goEnable": "Zur Plugin-Verwaltung, um zu aktivieren",
  "sys.plugins.uploadTitle": "Plugin hochladen (lokale Installation)",
  "sys.plugins.uploadDescPrefix": "Wähle ein gemäß Spezifikation gepacktes Plugin-Zip (mit Stammverzeichnis ",
  "sys.plugins.uploadDescSuffix": ", siehe Plugin-Entwicklungsspezifikation §3); nach der Installation erscheint es sofort in der Liste unten und kann deaktiviert oder gelöscht werden.",
  "sys.plugins.uploadInstall": "Lokal installieren",
  "sys.plugins.uploadSuccess": "Plugin installiert",
  "sys.plugins.uploadFailed": "Installation fehlgeschlagen",
  "sys.store.storeUnavailable": "Plugin-Shop nicht erreichbar",
  "sys.store.installedToast": "Plugin „{name}“ installiert",
  "sys.store.installFailed": "Installation fehlgeschlagen",
  "sys.store.localInstalledToast": "Plugin lokal installiert",
  "sys.store.publishedToast": "Im Plugin-Shop veröffentlicht",
  "sys.store.uploadFailed": "Upload fehlgeschlagen",
  "sys.store.headerPrefix": "Im Plugin-Shop Plugins durchsuchen, filtern und installieren (die Shop-Adresse wird über das Backend ",
  "sys.store.headerSuffix": " konfiguriert).",
  "sys.store.checkUpdates": "Auf Updates prüfen",
  "sys.store.emptyFiltered": "Keine passenden Plugins im Shop.",
  "sys.store.installed": "Installiert",
  "sys.store.install": "Installieren",
  "sys.store.uploadTitle": "Plugin hochladen",
  "sys.store.uploadDescPrefix": "Wähle ein gemäß Spezifikation gepacktes Plugin-Zip (mit Stammverzeichnis ",
  "sys.store.uploadDescSuffix": ", siehe Plugin-Entwicklungsspezifikation §3): lokal installieren oder im Plugin-Shop veröffentlichen.",
  "sys.store.uploadLocal": "Lokal installieren",
  "sys.store.uploadPublish": "Im Shop veröffentlichen",
  "sys.theme.mode": "Dunkel-/Hellmodus",
  "sys.theme.light": "Hell",
  "sys.theme.dark": "Dunkel",
  "sys.theme.featured": "Spezielle Designs",
  "sys.theme.pluginDisabled": "Designs werden vom Plugin „Designs“ bereitgestellt, das derzeit nicht aktiviert ist.",
  "sys.theme.defaultName": "Standard",
  "sys.theme.defaultDesc": "Systemfarbschema folgen",
  "sys.plugins.changelogBtn": "Versionshistorie",
  "sys.plugins.changelogTitle": "{name} · Versionshistorie",
  "sys.plugins.changelogDesc": "Aktuell installierte Version v{version}; die Zeitleiste zeigt die Historie absteigend nach Version.",
  "sys.plugins.changelogEmpty": "Für dieses Plugin gibt es keine Versionshistorie.",
  "sys.plugins.currentVersion": "Aktuelle Version",
  "sys.ai.title": "KI-Dienste (einheitliches Gateway)",
  "sys.ai.desc": "Alle KI-Aufrufe der Plugins laufen über MetaPilot; Schlüssel und Adressen liegen nur in der backend .env-Datei, Plugins und Frontend erhalten keinen Klartext.",
  "sys.ai.loadFailed": "Laden der KI-Konfiguration fehlgeschlagen",
  "sys.ai.provider": "API-Anbieter",
  "sys.ai.providerOpenai": "OpenAI-kompatibel (inkl. MiniMax / DeepSeek u. a.)",
  "sys.ai.providerAnthropic": "Anthropic",
  "sys.ai.providerLocal": "Lokales Modell (integriert)",
  "sys.ai.providerNone": "Cloud-KI deaktivieren",
  "sys.ai.chatModel": "Chat-Modell",
  "sys.ai.baseUrl": "API-Adresse",
  "sys.ai.apiKey": "API-Key",
  "sys.ai.apiKeyPlaceholder": "Konfiguriert (leer lassen, um den aktuellen Wert zu behalten)",
  "sys.ai.embeddingTitle": "Vektorisierung (Embedding)",
  "sys.ai.embeddingProvider": "Vektordienst",
  "sys.ai.embeddingLocal": "Lokal integriert (Download erforderlich)",
  "sys.ai.embeddingOpenai": "Cloud (über die obige API-Adresse)",
  "sys.ai.embeddingNone": "Vektorisierung deaktivieren",
  "sys.ai.embeddingModel": "Vektormodell",
  "sys.ai.embeddingUrl": "Lokale Vektoradresse",
  "sys.ai.prices": "Modellpreise (pro Million Token)",
  "sys.ai.pricesHint": "Für die Kostenschätzung auf der Statistikseite; Einzelpreise für Cache-Treffer / Eingabe / Ausgabe, Währung $ oder ¥",
  "sys.ai.priceModel": "Modell",
  "sys.ai.priceInput": "Eingabe",
  "sys.ai.priceCached": "Cache-Treffer",
  "sys.ai.priceOutput": "Ausgabe",
  "sys.ai.addPrice": "Modellpreis hinzufügen",
  "sys.ai.currency": "Standardwährung",
  "sys.ai.save": "Konfiguration speichern",
  "sys.ai.saved": "KI-Konfiguration gespeichert (in .env geschrieben)",
  "sys.ai.saveFailed": "Speichern fehlgeschlagen",
  "sys.ai.test": "Verbindung testen",
  "sys.ai.testing": "Wird getestet...",
  "sys.ai.testOk": "Verbindung erfolgreich: {model} (Eingabe {in} / Ausgabe {out} Tokens)",
  "sys.ai.testFailed": "Verbindung fehlgeschlagen",
  "sys.ai.localTitle": "Integrierte lokale Modelle",
  "sys.ai.localDesc": "Bei Bedarf mit einem Klick herunterladen (mehrere Spiegel werden automatisch versucht); nach dem Download sofort startbar",
  "sys.ai.downloaded": "Heruntergeladen",
  "sys.ai.notDownloaded": "Nicht heruntergeladen",
  "sys.ai.downloading": "Wird heruntergeladen...",
  "sys.ai.download": "Herunterladen",
  "sys.ai.start": "Starten",
  "sys.ai.startFailed": "Start fehlgeschlagen",
  "sys.ai.stop": "Beenden",
  "sys.ai.running": "Läuft",
  "sys.ai.notRunning": "Läuft nicht",
  "sys.ai.modelKindEmbedding": "Vektor",
  "sys.ai.modelKindLlm": "Chat",
  "sys.ai.modelKindRerank": "Re-Rank",
  "sys.ai.localOnlyHint": "Die obigen Einstellungen werden nur in der lokalen .env-Datei gespeichert und an keinen Dienst übertragen.",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "Symbolischen Link hinzufügen",
    "core.library.defaultLib": "Standard",
    "core.library.defaultSet": "Als Standardbibliothek festgelegt",
    "core.library.menuMore": "Weitere Aktionen",
    "core.library.pin": "Anheften",
    "core.library.pinned": "Angeheftet",
    "core.library.pinnedLib": "Oben angeheftet",
    "core.library.renameLib": "Umbenennen",
    "core.library.renameLibTitle": "Bibliothek umbenennen",
    "core.library.renamedLib": "Bibliothek umbenannt",
    "core.library.setDefault": "Als Standard festlegen",
    "core.library.unpin": "Loslösen",
    "core.library.unpinnedLib": "Losgelöst",
}
