# -*- coding: utf-8 -*-
"""Diccionario de interfaz de MetaPilot en español (es).

Este módulo contiene la traducción al español del diccionario de la interfaz
de MetaPilot. El conjunto de claves es idéntico al de los archivos fuente en
chino simplificado (zh-CN): client/src/i18n/locales/zh-CN/{common,core,course,insight,symlink,sys}.ts.

Convenciones:
  - Se conservan todos los marcadores de posición {xxx} (sin renombrar); su
    posición puede ajustarse libremente a la sintaxis del español.
  - Las comillas españolas « » se usan en lugar de las comillas chinas 「」.
  - AI se traduce como IA (inteligencia artificial).
"""

UI_DICT: dict[str, str] = {
    # ---- common ----
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.create": "Crear",
    "common.add": "Añadir",
    "common.rename": "Renombrar",
    "common.close": "Cerrar",
    "common.refresh": "Actualizar",
    "common.loading": "Cargando…",
    "common.empty": "Sin datos",
    "common.back": "Volver",
    "common.open": "Abrir",
    "common.all": "Todos",
    "common.none": "Ninguno",
    "common.optional": "Opcional",
    "common.required": "Obligatorio",
    "common.name": "Nombre",
    "common.description": "Descripción",
    "common.author": "Autor",
    "common.version": "Versión",
    "common.size": "Tamaño",
    "common.path": "Ruta",
    "common.type": "Tipo",
    "common.status": "Estado",
    "common.success": "Éxito",
    "common.failed": "Fallido",
    "common.error": "Error",
    "common.unknown": "Desconocido",
    "common.actions": "Acciones",
    "common.more": "Más",
    "common.details": "Detalles",
    "common.preview": "Vista previa",
    "common.enabled": "Habilitado",
    "common.disabled": "Deshabilitado",
    "common.yes": "Sí",
    "common.no": "No",
    "common.seconds": "s",
    "common.minutes": "min",
    "common.hours": "h",
    "common.bytes": "bytes",
    "common.language": "Idioma",

    # ---- core / navegación ----
    "nav.library": "Mi biblioteca",
    "nav.plugins": "Plugins",
    "nav.settings": "Ajustes",
    "nav.stats": "Estadísticas",
    "nav.insight": "Insight de IA",

    # ---- core / widgets de estadísticas ----
    "core.widget.topDocs": "Documentos más visitados",
    "core.widget.heatmap": "Mapa de calor de visitas",
    "core.widget.stayTime": "Tiempo en documentos",
    "core.widget.wordCount": "Recuento de palabras",
    "core.widget.recentDocs": "Visitados recientemente",

    # ---- core / tema ----
    "core.theme.toLight": "Cambiar a modo claro",
    "core.theme.toDark": "Cambiar a modo oscuro",
    "core.theme.selectTheme": "Elegir tema",

    # ---- core / página de aprendizaje ----
    "core.learn.markedCompleted": "Marcado como completado",
    "core.learn.unmarkedCompleted": "Marca eliminada",
    "core.learn.courseDisabledWarning": "Este documento depende del plugin «Curso». Las preguntas y los bloques interactivos se mostrarán como datos sin procesar. Puedes habilitarlo en la página «Plugins».",
    "core.learn.completed": "Completado",
    "core.learn.markComplete": "Marcar como completado",
    "core.learn.readingMode": "Modo lectura",
    "core.learn.progressKnowledge": "{pos} / {total} puntos de conocimiento",
    "core.learn.progressDoc": "{pos} / {total} documentos",
    "core.learn.refToDoc": "Esta sección referencia el documento «{name}»",
    "core.learn.gotoRefDoc": "Ir al documento referenciado",
    "core.learn.emptySection": "Este punto de conocimiento aún no tiene contenido",
    "core.learn.prevKnowledge": "Punto anterior",
    "core.learn.unmarkComplete": "Quitar marca de completado",
    "core.learn.markCurrentComplete": "Marcar este punto como completado",
    "core.learn.nextKnowledge": "Siguiente punto",
    "core.learn.unsupportedBlock": "Tipo de componente no compatible: {type}",
    "core.learn.ref": "Referencia",
    "core.learn.choiceMultiple": "Opción múltiple",
    "core.learn.choiceSingle": "Opción única",
    "core.learn.multiSelect": "Respuesta múltiple",
    "core.learn.singleSelect": "Respuesta única",
    "core.learn.submit": "Enviar",
    "core.learn.correct": "Correcto",
    "core.learn.incorrect": "Incorrecto",
    "core.learn.explanation": "Explicación: {text}",
    "core.learn.gradeFailed": "Fallo al calificar",
    "core.learn.fillBlank": "Rellenar espacio en blanco",
    "core.learn.aiGraded": "Calificación con IA",
    "core.learn.blankN": "Espacio {n}",
    "core.learn.accuracy": "Precisión {score}%",
    "core.learn.redo": "Reintentar",
    "core.learn.interactiveNoFile": "Al bloque interactivo le falta la configuración de file",
    "core.learn.interactiveFallback": "Interactivo",
    "core.learn.interactiveTitle": "Demostración interactiva",
    "core.learn.blockDepPrefix": "Este componente (",
    "core.learn.blockDepMid": ") depende del plugin «",
    "core.learn.blockDepPlugin": "» (",
    "core.learn.blockDepSuffix": "); se muestra como datos sin procesar cuando no está habilitado",
    "core.learn.interactiveNotRendered": "El bloque interactivo no se ha renderizado",
    "core.learn.quizNotRendered": "La pregunta no se ha renderizado",
    "core.learn.viewRaw": "Ver datos sin procesar",
    "core.learn.shortAnswer": "Respuesta corta",
    "core.learn.answerPlaceholder": "Escribe tu respuesta...",
    "core.learn.keywords": "Puntos clave: {text}",
    "core.learn.submitGrade": "Enviar para calificar",
    "core.learn.aiFeedback": "Comentario de IA: ",
    "core.learn.hint": "Pista: {text}",
    "core.plugin.unknown": "Plugin desconocido",
    "core.plugin.course": "Curso",

    # ---- core / biblioteca de documentos ----
    "core.library.quiz": "Examen",
    "core.library.kindCourse": "Curso",
    "core.library.kindNote": "Nota",
    "core.library.kindKb": "Base de conocimiento",
    "core.library.kindCanvas": "Lienzo",
    "core.library.empty": "Sin contenido",
    "core.library.emptyLibrary": "Esta biblioteca está vacía. Importa un paquete de curso o crea una nueva colección desde la página principal.",
    "core.library.library": "Bibliotecas",
    "core.library.deleteLibTitle": "Eliminar biblioteca",
    "core.library.deleteLibDesc": "¿Eliminar esta biblioteca? Todo su contenido se eliminará y no se podrá recuperar.",
    "core.library.deletedLib": "Biblioteca eliminada",
    "core.library.unmountTitle": "Desmontar enlace simbólico",
    "core.library.unmountNameFallback": "este enlace simbólico",
    "core.library.unmountDesc": "«{name}» se eliminará de la lista. Los archivos del disco no se borrarán.",
    "core.library.unmount": "Desmontar",
    "core.library.unmounted": "Desmontado",
    "core.library.singleFile": "(archivo único)",
    "core.library.symlink": "Enlaces simbólicos",
    "core.library.pluginBadge": "Plugin",
    "core.library.emptyLibraries": "No hay bibliotecas. Haz clic arriba a la derecha para importar un paquete de curso o crear una biblioteca.",
    "core.library.noSymlinks": "No hay enlaces simbólicos; haz clic a la derecha para añadir una carpeta o archivo local",
    "core.library.collectionCount": "{count} colecciones",
    "core.library.searchPlaceholder": "Buscar colecciones...",
    "core.library.gridView": "Vista de cuadrícula",
    "core.library.listView": "Vista de lista",
    "core.library.unitChapter": "Capítulos",
    "core.library.unitCanvas": "Lienzo",
    "core.library.unitDoc": "Documentos",
    "core.library.noSearchResults": "No hay colecciones que coincidan.",
    "core.library.emptyCollections": "Esta biblioteca aún no tiene colecciones. Puedes importar un paquete de curso o crear una nueva.",
    "core.library.selectPlaceholder": "Selecciona una biblioteca o un enlace simbólico para ver su contenido.",
    "core.library.newLibTitle": "Nueva biblioteca",
    "core.library.namePlaceholder": "p. ej. Curso de especialidad",
    "core.library.descriptionOptional": "Descripción (opcional)",
    "core.library.descPlaceholder": "Qué contiene esta biblioteca",
    "core.library.createdLib": "Biblioteca creada",
    "core.library.newCanvas": "Nuevo lienzo",
    "core.library.newCanvasTitle": "Nuevo lienzo",
    "core.library.newCanvasPlaceholder": "Nombre del lienzo",
    "core.library.newCanvasDefault": "Lienzo sin título",
    "core.library.createdCanvas": "Lienzo creado",
    "core.library.newDoc": "Nuevo documento",
    "core.library.newDocTitle": "Nuevo documento",
    "core.library.newDocPlaceholder": "Nombre del documento",
    "core.library.newDocDefault": "Documento sin título",
    "core.library.createdDoc": "Documento creado",
    "core.library.import": "Importar",
    "core.library.importFailed": "Error al importar",
    "core.library.importedCourse": "Curso importado «{names}»",
    "core.library.importedNote": "Nota importada ({count} secciones)",
    "core.library.importWarning": "Algunos componentes del contenido importado dependen del plugin «{names}». Se mostrarán como datos sin procesar hasta que se habilite.",
    "core.library.importedCanvas": "Lienzo importado «{name}»",
    "core.library.importedContent": "Contenido importado",
    "core.library.importTitle": "Importar contenido",
    "core.library.importDesc": "Admite archivos MetaPilot (.mpf/.canvas, formato unificado: doc=contenido de curso, canvas=lienzo), paquetes de curso (zip) y notas Markdown.",
    "core.library.tabMpf": "Archivo MetaPilot",
    "core.library.tabCourse": "Paquete de curso",
    "core.library.mpfLabel": "Archivo MetaPilot (.mpf / .canvas)",
    "core.library.mpfHint": "El tipo doc se analiza como curso/documento; los archivos .canvas (Obsidian Canvas) se convierten automáticamente en lienzo.",
    "core.library.courseGateHint": "Importar paquete de curso (zip)",
    "core.library.courseFileLabel": "Archivo de paquete de curso (.zip, con manifest.json)",
    "core.library.noteGateHint": "Importar notas Markdown",
    "core.library.noteFileLabel": "Archivo Markdown / Obsidian (.md)",

    # ---- core / editor ----
    "core.edit.block.markdown": "Mostrar (Markdown)",
    "core.edit.block.single_choice": "Opción única",
    "core.edit.block.multiple_choice": "Opción múltiple",
    "core.edit.block.fill_blank": "Rellenar espacio en blanco",
    "core.edit.block.short_answer": "Respuesta corta",
    "core.edit.block.interactive": "Bloque interactivo",
    "core.edit.block": "Componente",
    "core.edit.collectionInfo": "Información del curso",
    "core.edit.summary": "Resumen",
    "core.edit.newDocName": "Nuevo capítulo",
    "core.edit.newSectionName": "Nuevo punto de conocimiento",
    "core.edit.deleteDocTitle": "Eliminar capítulo",
    "core.edit.deleteDocDesc": "¿Eliminar este capítulo? Todas sus secciones y contenido se eliminarán y no se podrán recuperar.",
    "core.edit.deleteSectionTitle": "Eliminar sección",
    "core.edit.deleteSectionDesc": "¿Eliminar esta sección?",
    "core.edit.deleteBlockTitle": "Eliminar componente",
    "core.edit.deleteBlockDesc": "¿Eliminar este componente?",
    "core.edit.newFolderTitle": "Nueva carpeta",
    "core.edit.newFolderDesc": "Introduce el nombre de la nueva carpeta.",
    "core.edit.newFolderPlaceholder": "p. ej. Notas de capítulo",
    "core.edit.renameFolderTitle": "Renombrar carpeta",
    "core.edit.deleteFolderTitle": "Eliminar carpeta",
    "core.edit.deleteFolderDesc": "¿Eliminar esta carpeta? Todas sus subcarpetas y documentos se eliminarán y no se podrán recuperar.",
    "core.edit.createFailed": "Error al crear",
    "core.edit.renameFailed": "Error al renombrar",
    "core.edit.deleteFailed": "Error al eliminar",
    "core.edit.moveFailed": "Error al mover",
    "core.edit.docSettings": "Ajustes del capítulo",
    "core.edit.docNameLabel": "Nombre del capítulo",
    "core.edit.docTypeStudy": "Capítulo de estudio",
    "core.edit.docTypeQuiz": "Capítulo de examen",
    "core.edit.moveDocLabel": "Carpeta de destino (mover documento)",
    "core.edit.rootFolder": "Raíz",
    "core.edit.docTypeHint": "Los capítulos de estudio y de examen se pueden combinar libremente para separar el aprendizaje y las evaluaciones.",
    "core.edit.sectionSettings": "Ajustes del punto de conocimiento",
    "core.edit.sectionNameLabel": "Nombre del punto de conocimiento",
    "core.edit.refDocLabel": "Referenciar otro documento (referencia de sección)",
    "core.edit.noRef": "Sin referencia",
    "core.edit.refDocHint": "Al configurarlo, la página de aprendizaje muestra una tarjeta de referencia y salta al documento de destino.",
    "core.edit.addBlockLabel": "Añadir componente",
    "core.edit.backToSection": "Volver a la sección",
    "core.edit.blockSaved": "Componente guardado",
    "core.edit.addSectionTitle": "Añadir sección",
    "core.edit.noBlocks": "Sin componentes",
    "core.edit.noSections": "Sin secciones",
    "core.edit.subFolder": "Subcarpeta",
    "core.edit.emptyFolder": "Carpeta vacía",
    "core.edit.mode": "Modo de edición",
    "core.edit.dirty": "Cambios sin guardar",
    "core.edit.saved": "Guardado",
    "core.edit.newDoc": "Capítulo",
    "core.edit.newFolder": "Carpeta",
    "core.edit.done": "Hecho",
    "core.edit.markdownContent": "Contenido Markdown",
    "core.edit.markdownPlaceholder": "# Título\n\nContenido del cuerpo; admite Markdown y tablas/listas de tareas GFM",
    "core.edit.question": "Pregunta",
    "core.edit.options": "Opciones (una por línea)",
    "core.edit.optionsPlaceholder": "Opción A\nOpción B\nOpción C",
    "core.edit.correctIndex": "Índice de la opción correcta (desde 0)",
    "core.edit.correctIndexes": "Índices de las opciones correctas (separados por comas)",
    "core.edit.blanksAnswers": "Respuestas de referencia por espacio (una por línea)",
    "core.edit.blanksPlaceholder": "Respuesta 1\nRespuesta 2",
    "core.edit.reference": "Respuesta de referencia",
    "core.edit.keywordsLabel": "Puntos clave (separados por comas, para referencia de IA)",
    "core.edit.keywordsPlaceholder": "palabra1,palabra2",
    "core.edit.aiGraded": "Usar calificación con IA (preguntas subjetivas)",
    "core.edit.title": "Título",
    "core.edit.assetFile": "Archivo de recurso (ruta relativa a interactives/ del paquete de curso)",
    "core.edit.iframeHeight": "Altura del iframe (px)",
    "core.edit.explanationLabel": "Explicación / pista (opcional)",

    # ---- core / lienzo ----
    "core.canvas.saved": "Lienzo guardado",
    "core.canvas.saveFailed": "Error al guardar",
    "core.canvas.doubleClickEdit": "Doble clic para editar el texto",
    "core.canvas.notCanvas": "Esta colección no es un lienzo.",
    "core.canvas.backToLibrary": "Volver a la biblioteca",
    "core.canvas.badge": "Lienzo",
    "core.canvas.dirty": "Hay cambios sin guardar",
    "core.canvas.unsavedTitle": "Hay cambios sin guardar",
    "core.canvas.unsavedDesc": "El lienzo tiene cambios sin guardar. ¿Guardarlos antes de cerrar?",
    "core.canvas.discardAndLeave": "Descartar y salir",
    "core.canvas.saveAndLeave": "Guardar y salir",
    "core.canvas.newTextNode": "Nuevo nodo de texto",
    "core.canvas.help": "Arrastra los nodos para moverlos; arrastra en el espacio vacío para seleccionar, Mayús para multiselección, Supr para eliminar, Ctrl+C/V para copiar y pegar, Ctrl+Z para deshacer; doble clic sobre el texto para editarlo; arrastra desde el punto de conexión del borde de un nodo hasta otro nodo para crear un enlace; la rueda del ratón desplaza, Ctrl+rueda hace zoom, mantén pulsada la barra espaciadora y arrastra para desplazarte.",
    "core.canvas.undo": "Deshacer (Ctrl+Z)",
    "core.canvas.redo": "Rehacer (Ctrl+Shift+Z)",
    "core.canvas.zoomOut": "Alejar",
    "core.canvas.zoomIn": "Acercar",
    "core.canvas.fitView": "Ajustar a la vista",
    "core.canvas.empty": "(vacío)",
    "core.canvas.group": "Agrupar",
    "core.canvas.deleteNode": "Eliminar nodo",
    "core.canvas.dragLink": "Arrastrar para conectar",
    "core.canvas.emptyBoard": "Lienzo vacío. Haz clic en «Nuevo nodo de texto» arriba a la derecha para empezar.",
    "core.canvas.stats": "{nodes} nodos · {edges} enlaces",
    "core.canvas.exportMpf": "Exportar .mpf",
    "core.canvas.exportCanvas": "Exportar .canvas",
    "core.canvas.export": "Exportar",
    "core.canvas.center": "Centrar",
    "core.canvas.alignLeft": "Alinear a la izquierda",
    "core.canvas.alignCenter": "Alinear al centro",
    "core.canvas.alignRight": "Alinear a la derecha",
    "core.canvas.edgePath": "Estilo de la arista",
    "core.canvas.pathSmooth": "Curva suave",
    "core.canvas.pathStraight": "Línea recta",
    "core.canvas.pathSquare": "Ángulo recto",
    "core.canvas.resize": "Cambiar tamaño",
    "core.canvas.groupSelection": "Agrupar selección",
    "core.canvas.dragAddCard": "Arrastrar para añadir tarjeta",
    "core.canvas.dragAddNote": "Arrastrar para añadir nota",
    "core.canvas.dragAddNoteVault": "Arrastrar para añadir nota desde la biblioteca",
    "core.canvas.dragAddMediaVault": "Arrastrar para añadir medios desde la biblioteca",
    "core.canvas.paste": "Pegar",
    "core.canvas.toggleNav": "Mostrar/ocultar navegación",
    "core.canvas.noCanvases": "Aún no hay lienzos",
    "core.canvas.edgeStart": "Inicio",
    "core.canvas.edgeEnd": "Fin",
    "core.canvas.arrow": "Flecha",
    "core.canvas.toggleStartArrow": "Alternar flecha inicial",
    "core.canvas.toggleEndArrow": "Alternar flecha final",
    "core.canvas.edgeLabel": "Etiqueta",
    "core.canvas.colorTitle": "Color {color}",
    "core.canvas.clearColor": "Quitar color",
    "core.canvas.deleteEdge": "Eliminar arista",
    "core.canvas.addNode": "Añadir nodo",
    "core.canvas.addNodeText": "Texto",
    "core.canvas.addNodeFile": "Archivo",
    "core.canvas.addNodeLink": "Enlace",
    "core.canvas.addNodeGroup": "Grupo",
    "core.canvas.addFileTitle": "Ruta del archivo",
    "core.canvas.addFileDesc": "Ruta relativa de la biblioteca, p. ej. notes/ejemplo.md o images/imagen.png (compatible con Obsidian)",
    "core.canvas.addLinkTitle": "URL del enlace",
    "core.canvas.addGroupTitle": "Etiqueta del grupo",
    "core.canvas.groupName": "Nombre del grupo",

    # ---- core / estadísticas ----
    "core.stats.intro": "El núcleo oficial ofrece componentes estadísticos básicos; plugins como Curso pueden aportar más. Arrastra las tarjetas para reordenarlas, ajusta su tamaño desde la esquina superior derecha y activa «Marcar componentes por su origen» en la página de ajustes.",
    "core.stats.resize": "Cambiar tamaño (actual {size})",
    "core.stats.hide": "Ocultar componente",
    "core.stats.manage": "Gestionar componentes",
    "core.stats.hiddenCount": "{count} ocultos",
    "core.stats.manageDesc": "Oculta componentes en «Visibles» o restáuralos cuando quieras desde el panel «Ocultos»; arrastra las tarjetas de la página de estadísticas para cambiar su posición y orden.",
    "core.stats.none": "No hay componentes estadísticos disponibles",
    "core.stats.visibleCount": "Visibles ({count})",
    "core.stats.hiddenTab": "Ocultos ({count})",
    "core.stats.noHidden": "No hay componentes ocultos; todos están visibles",
    "core.stats.resetLayout": "Restablecer diseño",
    "core.stats.showAll": "Mostrar todo",
    "core.stats.restore": "Restaurar",
    "core.stats.noVisits": "Aún no hay visitas",
    "core.stats.noStayTime": "Aún no hay datos de permanencia",
    "core.stats.visits": "{count} visitas",
    "core.stats.wordUnit": "palabras",
    "core.stats.unknownWidget": "Componente desconocido",
    "core.stats.heatmap3m": "Mapa de calor de visitas de los últimos 3 meses",
    "core.stats.heatmapTooltip": "{day}/{month} · {count} visitas",
    "core.stats.heatmapLess": "Menos",
    "core.stats.heatmapMore": "Más",
    "core.stats.hourly": "Visitas por hora",
    "core.stats.hourTooltip": "{hour}:00 · {count} visitas",
    "core.stats.hourLabel": "{hour}:00",
    "core.stats.monthLabel": "{month}",
    "core.stats.weekdays": "L,M,X,J,V,S,D",
    "core.stats.courseDisabled": "Requiere el plugin «Curso», que está deshabilitado",
    "core.stats.totalStudy": "Tiempo total de estudio",
    "core.stats.chartMinutes": "Minutos",
    "core.stats.noStudyRecords": "Aún no hay registros de estudio",
    "core.stats.providedBy": "Proporcionado por el plugin «{name}»",
    "core.stats.providedByTooltip": "Proporcionado por el plugin {name}",

    # ---- core / diálogos y avisos compartidos ----
    "core.dialog.selectPlaceholder": "Selecciona…",
    "core.toast.copied": "Copiado al portapapeles",
    "core.widget.aiUsage": "Uso de IA",
    "core.stats.rangeToday": "Hoy",
    "core.stats.rangeWeek": "Esta semana",
    "core.stats.rangeMonth": "Este mes",
    "core.stats.rangeAll": "Todo",
    "core.stats.aiCalls": "Llamadas",
    "core.stats.aiTokens": "Tokens",
    "core.stats.aiCost": "Coste",
    "core.stats.aiTokensDetail": "entrada {in} / caché {cached} / salida {out}",
    "core.stats.aiCallsShort": "{n} llamadas",
    "core.stats.aiTokensShort": "{n} tokens",
    "core.stats.aiUsageEmpty": "Aún no hay registros de uso de IA (las llamadas de los plugins a través de la pasarela unificada se registran aquí).",

    # ---- course ----
    "course.exportFailed": "Error al exportar",
    "course.pluginDisabledWarning": "Este documento depende del plugin «Curso». El progreso de aprendizaje y las interacciones de preguntas no están disponibles; habilítalo en la página «Plugins».",
    "course.backToLibrary": "Volver a la biblioteca",
    "course.noDescription": "Sin descripción",
    "course.authorLabel": "Autor: {author}",
    "course.export": "Exportar",
    "course.continueLearning": "Continuar aprendiendo",
    "course.learningProgress": "Progreso de aprendizaje",
    "course.progressCount": "{completed} / {total} puntos de conocimiento",
    "course.lastLearned": "Último visto: {name}",
    "course.progressRequiresPlugin": "El progreso de aprendizaje depende del plugin «Curso». Al habilitarlo, podrás marcar lo completado y realizar un seguimiento de tu última posición de aprendizaje.",
    "course.quiz": "Examen",
    "course.noSectionsInChapter": "Este capítulo no tiene secciones",
    "course.noChapters": "Este curso aún no tiene capítulos. Haz clic en «Editar» arriba a la derecha para empezar a crearlos.",
    "course.library.newCourse": "Nuevo curso",
    "course.library.newCourseTitle": "Nuevo curso",
    "course.library.newCoursePlaceholder": "Nombre del curso",
    "course.library.newCourseDefault": "Curso sin título",
    "course.library.createdCourse": "Curso creado",
    "course.library.createCourseFailed": "Error al crear el curso",
    "course.library.toCourse": "Convertir en curso",
    "course.library.toCourseTitle": "Convertir en curso",
    "course.library.toCourseDesc": "¿Convertir «{name}» en un curso? Un curso es un documento parcheado que habilita capacidades como el progreso de aprendizaje, la calificación y los bloques interactivos; si el plugin «Curso» no está habilitado, estas capacidades no están disponibles.",
    "course.library.toCourseConfirm": "Convertir en curso",
    "course.library.convertedCourse": "«{name}» se ha convertido en curso",
    "course.library.convertCourseFailed": "Error al convertir en curso",

    # ---- insight ----
    "insight.pageTitle": "Insight de IA",
    "insight.intro": "Selecciona una serie de documentos o bibliotecas, crea un índice y deja que la IA analice: examina las conexiones entre los materiales y genera respuestas, sugerencias o lienzos/cursos según cuatro modos.",
    "insight.introWithSymlink": "Selecciona una serie de documentos, bibliotecas o directorios locales, crea un índice y deja que la IA analice: examina las conexiones entre los materiales y genera respuestas, sugerencias o lienzos/cursos según cuatro modos.",
    "insight.stepIndex": "Paso 1 · Crear índice",
    "insight.stepAsk": "Paso 2 · Preguntar a la IA",
    "insight.stepIndexQuoted": "«Paso 1 · Crear índice»",
    "insight.mustIndexBefore": "Crea primero el índice y luego pregunta; si preguntas sin índice, se creará automáticamente (se mostrará el progreso).",
    "insight.noIndexedBefore": "Aún no hay fuentes indexadas. Ve a",
    "insight.noIndexedAfter": "y crea un índice vectorial del contenido seleccionado antes de preguntar.",
    "insight.noIndexedAfterWithSymlink": "y crea un índice vectorial de los documentos / directorios locales seleccionados antes de preguntar.",
    "insight.vectorModelTitle": "Modelo de embedding y servicio local",
    "insight.embeddingRunning": "En ejecución",
    "insight.embeddingNotReady": "No listo",
    "insight.selectModelPlaceholder": "Elegir modelo de embedding",
    "insight.stopService": "Detener servicio",
    "insight.startService": "Iniciar servicio (descarga el modelo seleccionado en la primera ejecución)",
    "insight.modelDownloadHint": "La descarga del modelo prueba varios orígenes automáticamente; la primera descarga debe esperar a que el modelo esté listo y la página actualizará el estado sola. Las fuentes de descarga y la lista de modelos concretas dependen de la configuración del backend.",
    "insight.selectSourcesTitle": "Seleccionar fuentes de datos (multiselección)",
    "insight.indexIntro": "Permite seleccionar por biblioteca, colección o documento individual; el índice se almacena de forma independiente por fuente.",
    "insight.indexIntroWithSymlink": "Permite seleccionar por biblioteca, colección o documento, así como un directorio local completo o cualquier ruta dentro de él; el índice se almacena de forma independiente por fuente.",
    "insight.indexing": "Indexando...",
    "insight.indexingProgress": "{done}/{total} fragmentos indexados",
    "insight.indexQueued": "Se ha empezado a crear el índice; consulta el progreso a continuación",
    "insight.buildVectorIndex": "Crear índice vectorial",
    "insight.noSources": "No hay fuentes disponibles: crea primero una biblioteca en «Mi biblioteca».",
    "insight.noSourcesWithSymlink": "No hay fuentes disponibles: crea primero una biblioteca en «Mi biblioteca» o monta un directorio local.",
    "insight.askSourcesTitle": "Seleccionar las fuentes sobre las que pensar (multiselección, recuperación combinada)",
    "insight.askTitle": "Pensamiento de IA (las respuestas citan las fuentes)",
    "insight.askPlaceholder": "Pregunta a la IA, p. ej. «¿Qué conexiones hay entre estos materiales?»",
    "insight.refSources": "Fuentes",
    "insight.sourceRef": "[Fuente {n}]",
    "insight.asking": "Recuperando y generando la respuesta...",
    "insight.inputPlaceholder": "Escribe tu pregunta o dirección de pensamiento...",
    "insight.askButton": "Preguntar",
    "insight.groupLibrary": "Documentos de biblioteca (biblioteca / colección / documento)",
    "insight.groupSymlink": "Montajes de directorios locales",
    "insight.indexedCount": "{count} fragmentos indexados",
    "insight.notIndexed": "Sin indexar",
    "insight.pluginHint": "Insight de IA: analiza las conexiones entre los materiales y genera contenido",
    "insight.loadResourcesFailed": "Error al cargar las fuentes",
    "insight.startServiceToast": "Iniciando el servicio (la primera ejecución descargará automáticamente el modelo seleccionado)",
    "insight.startFailed": "Error al iniciar",
    "insight.serviceStopped": "Servicio detenido",
    "insight.indexDone": "Indexación completada: {ok}/{total} fuentes",
    "insight.indexFailed": "Error de indexación",
    "insight.askFailed": "Error al preguntar",
    "insight.modeTitle": "Modo de pensamiento",
    "insight.modeIntro": "Elige una forma de pensar; la IA consultará los materiales seleccionados y generará contenido según ese modo.",
    "insight.modeAssist": "Pensamiento asistido",
    "insight.modeAssistDesc": "Encuentra las conexiones entre los materiales y ofrece respuestas y sugerencias",
    "insight.modeWander": "Divagar",
    "insight.modeWanderDesc": "Combina los materiales con tu dirección de pensamiento y divaga en asociaciones",
    "insight.modeReflect": "Reflexión y síntesis",
    "insight.modeReflectDesc": "Resume las conexiones y puntos ciegos que quizá no hayas notado",
    "insight.modePlan": "Planificación de insights",
    "insight.modePlanDesc": "Razonamiento en varias rondas para generar un lienzo o un curso que te enseñe",
    "insight.planOutputTitle": "Tipo de salida",
    "insight.planOutputCanvas": "Lienzo de conocimiento",
    "insight.planOutputCourse": "Microcurso (documentos)",
    "insight.planLibraryTitle": "Guardar en la biblioteca",
    "insight.planLibraryAuto": "Biblioteca por defecto (la primera)",
    "insight.planGoalPlaceholder": "Introduce el objetivo del plan, p. ej.: organiza los conceptos y conexiones clave de estos materiales y enséñame a entenderlos en el menor tiempo posible",
    "insight.planButton": "Iniciar planificación",
    "insight.planning": "La IA está analizando las conexiones de los materiales en varias rondas y generando; puede tardar 1-2 minutos...",
    "insight.planDone": "Se ha generado «{name}»",
    "insight.planOpenCanvas": "Abrir lienzo",
    "insight.planOpenCourse": "Abrir curso",
    "insight.planSummary": "Resumen del plan",
    "insight.planFailed": "Error en la planificación de insights",
    "insight.planRoadmap": "Pasos de ejecución de IA",
    "insight.planThinking": "Proceso de pensamiento de IA",
    "insight.planStep.retrieve": "Recuperar materiales",
    "insight.planStep.plan": "Analizar temas y conexiones",
    "insight.planStep.review": "Reflexión crítica",
    "insight.planStep.generateCanvas": "Generar lienzo de conocimiento",
    "insight.planStep.generateCourse": "Generar microcurso",
    "insight.planStep.save": "Guardar en la biblioteca",
    "insight.planStepRunning": "en curso…",
    "insight.planConnecting": "Conectando con la IA y planificando los pasos…",
    "insight.autoIndexing": "Las fuentes seleccionadas aún no tienen índice; se está creando automáticamente ({done}/{total})...",
    "insight.autoIndexDone": "Indexación completada; continúa generando...",
    "insight.autoIndexFailed": "Error al crear el índice automáticamente; ve al paso 1 y créalo manualmente",
    "insight.symlinkBrowse": "Explorar directorio",
    "insight.treeEmpty": "(vacío)",
    "insight.kbTitle": "Biblioteca de fuentes",
    "insight.goAsk": "Preguntar a la IA",
    "insight.selectedCount": "{count} seleccionados",
    "insight.kbIndexed": "{count} fuentes indexadas",
    "insight.collapsePanel": "Contraer el panel de biblioteca de fuentes",
    "insight.expandPanel": "Expandir el panel de biblioteca de fuentes",
    "insight.kbHint": "Marca bibliotecas / colecciones / documentos como ámbito de recuperación: puedes crear un índice o preguntar directamente; las fuentes sin indexar se indexan automáticamente al preguntar.",
    "insight.kbHintWithSymlink": "Marca bibliotecas / colecciones / documentos o directorios locales como ámbito de recuperación: puedes crear un índice o preguntar directamente; las fuentes sin indexar se indexan automáticamente al preguntar.",
    "insight.buildIndexTitle": "Crear índice vectorial",
    "insight.buildIndexHint": "{count} fuentes seleccionadas (ajústalas en la «Biblioteca de fuentes» de la izquierda); las que no tengan índice también se crearán.",

    # ---- symlink ----
    "symlink.fileBrowser": "Explorador de archivos",
    "symlink.symlinkPlugin": "Plugin de enlaces simbólicos",
    "symlink.pluginHint": "Explora y lee/escribe directorios locales",
    "symlink.linkLocalDoc": "Vincular documentos locales (enlace simbólico)",
    "symlink.addMountDesc1": "Enlaza ",
    "symlink.addMountDesc2": " o ",
    "symlink.addMountDesc3": " del disco local; los archivos originales nunca se copian ni se mueven. Una vez vinculado, podrás explorarlo, leerlo y editarlo como un documento en el explorador de archivos.",
    "symlink.mounts": "Montajes",
    "symlink.mount": "Montar",
    "symlink.thatMount": "este montaje",
    "symlink.unmount": "Desmontar",
    "symlink.unmountSymlink": "Desmontar enlace simbólico",
    "symlink.unmountConfirmDesc": "«{name}» se eliminará de la lista. Los archivos del disco no se borrarán.",
    "symlink.noMounts": "No hay montajes; haz clic arriba a la derecha para añadir una carpeta o archivo local",
    "symlink.currentMountRoot": "Raíz del montaje actual: {root}",
    "symlink.pleaseMount": "Monta primero una carpeta o archivo local",
    "symlink.mountSuccess": "Montaje realizado correctamente",
    "symlink.mountFailed": "Error al montar",
    "symlink.displayName": "Nombre mostrado",
    "symlink.namePlaceholder": "p. ej. Mis notas",
    "symlink.localPathLabel": "Ruta local (carpeta o archivo)",
    "symlink.pathPlaceholder": "Haz clic en «Explorar» para elegir, o escríbelo manualmente (compatible con Windows/Linux)",
    "symlink.collapse": "Contraer",
    "symlink.browse": "Explorar",
    "symlink.afterMountHint": "Tras montar, podrás explorar, leer y editar los archivos de texto del directorio desde el explorador de archivos (el acceso está restringido a la raíz del montaje).",
    "symlink.directory": "Directorios",
    "symlink.folder": "Carpeta",
    "symlink.file": "Archivo",
    "symlink.singleFile": "Archivo único",
    "symlink.singleFileNote": "(archivo único)",
    "symlink.singleFileMount": "(montaje de archivo único)",
    "symlink.rootDir": "(raíz)",
    "symlink.noSubfolders": "Sin subcarpetas",
    "symlink.emptyDir": "Directorio vacío",
    "symlink.expandDir": "Expandir directorio",
    "symlink.collapseDir": "Contraer directorio",
    "symlink.newFolder": "Nueva carpeta",
    "symlink.newFolderDesc": "Introduce el nombre de la nueva carpeta.",
    "symlink.newFolderPlaceholder": "p. ej. notas de capítulo",
    "symlink.searchPlaceholder": "Buscar…",
    "symlink.gridView": "Vista de cuadrícula",
    "symlink.listView": "Vista de lista",
    "symlink.backToList": "Volver a la lista",
    "symlink.reveal": "Localizar",
    "symlink.revealInFileManager": "Mostrar en el administrador de archivos",
    "symlink.openWithDefault": "Abrir con la aplicación predeterminada",
    "symlink.editing": "Editando: {path}",
    "symlink.saved": "Guardado",
    "symlink.saveFailed": "Error al guardar",
    "symlink.createFailed": "Error al crear",
    "symlink.deleteFile": "Eliminar archivo",
    "symlink.deleteConfirmDesc": "¿Eliminar «{target}»?",
    "symlink.deleteDirWarning": "La carpeta se eliminará de forma recursiva y no se podrá recuperar.",
    "symlink.deleteFailed": "Error al eliminar",
    "symlink.openedWithDefault": "Se ha abierto con la aplicación predeterminada del sistema",
    "symlink.openFailed": "Error al abrir",
    "symlink.readFailed": "Error al leer",
    "symlink.noInlinePreview": "La vista previa integrada no es compatible con este tipo de archivo",
    "symlink.noInlinePreviewHint": "La vista previa integrada no es compatible con este tipo de archivo; haz clic derecho y elige «Abrir con la aplicación predeterminada»",
    "symlink.noMatch": "No hay elementos que coincidan.",
    "symlink.goUp": "Subir un nivel",
    "symlink.myComputer": "Mi PC",
    "symlink.reading": "Leyendo…",
    "symlink.emptyFolder": "Carpeta vacía",
    "symlink.selectedFolder": "Carpeta: {path}",
    "symlink.selectedFile": "Archivo: {path}",
    "symlink.selectHint": "Haz clic para seleccionar una carpeta o archivo; haz doble clic en una carpeta para entrar",
    "symlink.selectThisFolder": "Seleccionar esta carpeta",
    "symlink.selectThisFile": "Seleccionar este archivo",

    # ---- sys / ajustes ----
    "sys.title": "Ajustes",
    "sys.subtitle": "Controla el comportamiento de los avisos relacionados con plugins. MetaPilot es una biblioteca de documentos: los documentos siempre se pueden abrir y ver, y las partes no renderizadas se muestran como datos sin procesar; los avisos son solo recordatorios y no interrumpen el trabajo.",
    "sys.language": "Idioma",
    "sys.languageDesc": "Idioma de la interfaz. Se aplica de inmediato y se guarda localmente (localStorage).",
    "sys.appearance": "Apariencia",
    "sys.appearanceDesc": "El modo oscuro / claro se puede alternar en cualquier momento; los temas destacados los ofrece el plugin «Temas» (actívalo en la página de gestión de plugins y luego elígelos).",
    "sys.pluginWarnings": "Avisos de plugins",
    "sys.pluginWarningsDesc": "Al abrir un documento que depende de un plugin deshabilitado (p. ej. Curso, Base de conocimiento), aparece un aviso flotante en la parte superior: «Este contenido depende del plugin xx; es posible que algunos componentes no se puedan renderizar».",
    "sys.pluginErrors": "Avisos de errores de plugins",
    "sys.pluginErrorsDesc": "Si una acción falla porque un plugin no está habilitado (p. ej. calificación con IA, preguntas a la base de conocimiento), aparece un aviso de error en la parte superior; al desactivarlo, estos errores se ignoran silenciosamente.",
    "sys.componentSource": "Marcar el origen de los componentes",
    "sys.componentSourceDesc": "Al activarlo, en páginas como la biblioteca o las estadísticas, los componentes/contenidos proporcionados por plugins muestran el icono del plugin (pasa el ratón para ver el nombre); el núcleo oficial (el propio MetaPilot) no se marca. Al desactivarlo, no se muestra la marca de origen.",
    "sys.localOnly": "Estas preferencias solo se guardan localmente en el navegador (localStorage) y no afectan a otros dispositivos.",

    # ---- sys / gestión de plugins ----
    "sys.plugins.title": "Gestión de plugins",
    "sys.plugins.headerPrefix": "Los plugins se dividen en tres categorías: personalizados, oficiales y núcleo oficial. Un plugin es un paquete de funciones independiente en el directorio ",
    "sys.plugins.headerSuffix": " del backend; puedes explorar e instalar desde la «Tienda de plugins» o subir tus propios plugins.",
    "sys.plugins.tabLocal": "Plugins locales",
    "sys.plugins.tabStore": "Tienda de plugins",
    "sys.plugins.filterByTag": "Filtrar por etiqueta:",
    "sys.plugins.sourceUser": "Plugins personalizados",
    "sys.plugins.sourceUserDesc": "Puedes desarrollarlos, instalarlos desde la tienda o subiendo un zip; se pueden deshabilitar o eliminar.",
    "sys.plugins.sourceOfficial": "Plugins oficiales",
    "sys.plugins.sourceOfficialDesc": "Plugins útiles desarrollados por MetaPilot; se pueden habilitar o deshabilitar, pero no eliminar.",
    "sys.plugins.sourceCore": "Núcleo oficial",
    "sys.plugins.sourceCoreDesc": "El propio MetaPilot: navegación por la biblioteca de documentos y lectura de Markdown. No se puede deshabilitar ni eliminar.",
    "sys.plugins.enabledToast": "Plugin habilitado",
    "sys.plugins.disabledToast": "Plugin deshabilitado",
    "sys.plugins.opFailed": "Error en la operación",
    "sys.plugins.deleteTitle": "Eliminar plugin",
    "sys.plugins.deleteDesc": "¿Eliminar el plugin «{name}»? Se borrará físicamente el directorio backend/plugins/{id} y no se podrá recuperar.",
    "sys.plugins.deletedToast": "Se ha eliminado el plugin «{name}»",
    "sys.plugins.deleteFailed": "Error al eliminar el plugin",
    "sys.plugins.idLabel": "id:",
    "sys.plugins.dependsOn": "Depende de los plugins: ",
    "sys.plugins.missingDeps": "Faltan dependencias (hay que habilitarlas primero): ",
    "sys.plugins.featureCourseImport": "Importación / exportación de paquetes de curso",
    "sys.plugins.featureCourseFlow": "Aprendizaje por puntos de conocimiento en capítulos (flujo de componentes)",
    "sys.plugins.featureCourseProgress": "Progreso de aprendizaje y registro de tiempo",
    "sys.plugins.featureCourseGrading": "Calificación con IA de preguntas subjetivas",
    "sys.plugins.featureCourseInteractive": "Renderizado de bloques interactivos dinámicos",
    "sys.plugins.featureInsightIndex": "Indexación vectorial de fuentes con varios niveles de granularidad (biblioteca/colección/documento/directorio local)",
    "sys.plugins.featureInsightModes": "Cuatro modos de pensamiento (asistido / divagar / reflexión y síntesis / planificación de insights)",
    "sys.plugins.featureInsightPlan": "Razonamiento en varias rondas para generar lienzos y microcursos (.mpf)",
    "sys.plugins.needEnablePrefix": "Es necesario habilitar el plugin «",
    "sys.plugins.needEnableSuffix": "» para poder usar ",
    "sys.plugins.thisFeature": "esta función",
    "sys.plugins.goEnable": "Habilitar en la página de gestión de plugins",
    "sys.plugins.uploadTitle": "Subir plugin (instalación local)",
    "sys.plugins.uploadDescPrefix": "Selecciona un zip de plugin empaquetado según la especificación (que contenga el archivo ",
    "sys.plugins.uploadDescSuffix": " en la raíz; consulta la especificación de desarrollo de plugins §3). Tras instalarlo, aparecerá inmediatamente en la lista inferior y podrás deshabilitarlo o eliminarlo.",
    "sys.plugins.uploadInstall": "Instalación local",
    "sys.plugins.uploadSuccess": "Plugin instalado",
    "sys.plugins.uploadFailed": "Error al instalar",

    # ---- sys / tienda de plugins ----
    "sys.store.storeUnavailable": "No se puede acceder a la tienda de plugins",
    "sys.store.installedToast": "Se ha instalado el plugin «{name}»",
    "sys.store.installFailed": "Error en la instalación",
    "sys.store.localInstalledToast": "Plugin instalado localmente",
    "sys.store.publishedToast": "Publicado en la tienda de plugins",
    "sys.store.uploadFailed": "Error al subir",
    "sys.store.headerPrefix": "Explora, filtra e instala plugins desde la tienda (la dirección de la tienda la configura el backend ",
    "sys.store.headerSuffix": ").",
    "sys.store.checkUpdates": "Buscar actualizaciones",
    "sys.store.emptyFiltered": "No hay plugins que coincidan en la tienda.",
    "sys.store.installed": "Instalado",
    "sys.store.install": "Instalar",
    "sys.store.uploadTitle": "Subir plugin",
    "sys.store.uploadDescPrefix": "Selecciona un zip de plugin empaquetado según la especificación (que contenga el archivo ",
    "sys.store.uploadDescSuffix": " en la raíz; consulta la especificación de desarrollo de plugins §3): puedes instalarlo localmente o publicarlo en la tienda.",
    "sys.store.uploadLocal": "Instalación local",
    "sys.store.uploadPublish": "Publicar en la tienda",

    # ---- sys / tema ----
    "sys.theme.mode": "Modo oscuro / claro",
    "sys.theme.light": "Claro",
    "sys.theme.dark": "Oscuro",
    "sys.theme.featured": "Temas destacados",
    "sys.theme.pluginDisabled": "Los temas los ofrece el plugin «Temas», que actualmente está deshabilitado.",
    "sys.theme.defaultName": "Predeterminado",
    "sys.theme.defaultDesc": "Seguir los colores del sistema",
    "sys.plugins.changelogBtn": "Historial de cambios",
    "sys.plugins.changelogTitle": "{name} · Historial de cambios",
    "sys.plugins.changelogDesc": "Versión instalada v{version}; la línea de tiempo muestra las actualizaciones en orden descendente de versión.",
    "sys.plugins.changelogEmpty": "Este plugin no tiene historial de cambios.",
    "sys.plugins.currentVersion": "versión actual",

    # ---- sys / servicios de IA (pasarela unificada) ----
    "sys.ai.title": "Servicios de IA (pasarela unificada)",
    "sys.ai.desc": "Todas las llamadas de IA de los plugins pasan por MetaPilot; las claves y las direcciones solo se guardan en el .env del backend, y ni los plugins ni el frontend pueden verlas en texto plano.",
    "sys.ai.loadFailed": "Error al cargar la configuración de IA",
    "sys.ai.provider": "Proveedor de API",
    "sys.ai.providerOpenai": "Compatible con OpenAI (incluye MiniMax / DeepSeek, etc.)",
    "sys.ai.providerAnthropic": "Anthropic",
    "sys.ai.providerLocal": "Modelos locales (integrados)",
    "sys.ai.providerNone": "Desactivar IA en la nube",
    "sys.ai.chatModel": "Modelo de chat",
    "sys.ai.baseUrl": "Dirección de la API",
    "sys.ai.apiKey": "Clave de API",
    "sys.ai.apiKeyPlaceholder": "Configurada (déjalo vacío para mantener el valor actual)",
    "sys.ai.embeddingTitle": "Embedding (vectores)",
    "sys.ai.embeddingProvider": "Servicio de embedding",
    "sys.ai.embeddingLocal": "Local integrado (requiere descarga)",
    "sys.ai.embeddingOpenai": "Nube (usa la dirección de API anterior)",
    "sys.ai.embeddingNone": "Desactivar embedding",
    "sys.ai.embeddingModel": "Modelo de embedding",
    "sys.ai.embeddingUrl": "Dirección de embedding local",
    "sys.ai.prices": "Precios de los modelos (por millón de tokens)",
    "sys.ai.pricesHint": "Se usan para estimar costes en la página de estadísticas; precios unitarios de caché / entrada / salida, moneda $ o ¥",
    "sys.ai.priceModel": "Modelo",
    "sys.ai.priceInput": "Entrada",
    "sys.ai.priceCached": "Caché",
    "sys.ai.priceOutput": "Salida",
    "sys.ai.addPrice": "Añadir precio de modelo",
    "sys.ai.currency": "Moneda por defecto",
    "sys.ai.save": "Guardar configuración",
    "sys.ai.saved": "Configuración de IA guardada (escrita en .env)",
    "sys.ai.saveFailed": "Error al guardar",
    "sys.ai.test": "Probar conexión",
    "sys.ai.testing": "Probando...",
    "sys.ai.testOk": "Conexión correcta: {model} ({in} de entrada / {out} de salida tokens)",
    "sys.ai.testFailed": "Error de conexión",
    "sys.ai.localTitle": "Modelos locales integrados",
    "sys.ai.localDesc": "Descarga con un clic cuando lo necesites (prueba varios espejos automáticamente); tras descargarlo, podrás iniciarlo y usarlo",
    "sys.ai.downloaded": "Descargado",
    "sys.ai.notDownloaded": "No descargado",
    "sys.ai.downloading": "Descargando...",
    "sys.ai.download": "Descargar",
    "sys.ai.start": "Iniciar",
    "sys.ai.startFailed": "Error al iniciar",
    "sys.ai.stop": "Detener",
    "sys.ai.running": "En ejecución",
    "sys.ai.notRunning": "Detenido",
    "sys.ai.modelKindEmbedding": "Embedding",
    "sys.ai.modelKindLlm": "LLM",
    "sys.ai.modelKindRerank": "Reordenación (rerank)",
    "sys.ai.localOnlyHint": "Esta configuración solo se guarda en el .env local y nunca se sube a ningún servicio.",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "Añadir enlace simbólico",
    "core.library.defaultLib": "Predeterminado",
    "core.library.defaultSet": "Establecido como biblioteca predeterminada",
    "core.library.menuMore": "Más acciones",
    "core.library.pin": "Fijar",
    "core.library.pinned": "Fijado",
    "core.library.pinnedLib": "Fijado arriba",
    "core.library.renameLib": "Renombrar",
    "core.library.renameLibTitle": "Renombrar biblioteca",
    "core.library.renamedLib": "Biblioteca renombrada",
    "core.library.setDefault": "Establecer como predeterminado",
    "core.library.unpin": "Desfijar",
    "core.library.unpinnedLib": "Desfijado",
}
