# -*- coding: utf-8 -*-
"""法语（fr）界面语言词典。

key 集合与 zh-CN 核心词典完全一致（common/core/course/insight/symlink/sys 六个域合并），
value 为法语翻译，保留全部 {xxx} 占位符（名称不变，位置按法语语序调整），
引号使用法语 guillemets « »。由 examples/world-languages-plugin/ui_dicts/__init__.py 聚合。
"""

UI_DICT: dict[str, str] = {
    # ---- 通用词条 common ----
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.confirm": "Confirmer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.search": "Rechercher",
    "common.create": "Créer",
    "common.add": "Ajouter",
    "common.rename": "Renommer",
    "common.close": "Fermer",
    "common.refresh": "Actualiser",
    "common.loading": "Chargement…",
    "common.empty": "Aucune donnée",
    "common.back": "Retour",
    "common.open": "Ouvrir",
    "common.all": "Tout",
    "common.none": "Aucun",
    "common.optional": "Facultatif",
    "common.required": "Obligatoire",
    "common.name": "Nom",
    "common.description": "Description",
    "common.author": "Auteur",
    "common.version": "Version",
    "common.size": "Taille",
    "common.path": "Chemin",
    "common.type": "Type",
    "common.status": "État",
    "common.success": "Succès",
    "common.failed": "Échec",
    "common.error": "Erreur",
    "common.unknown": "Inconnu",
    "common.actions": "Actions",
    "common.more": "Plus",
    "common.details": "Détails",
    "common.preview": "Aperçu",
    "common.enabled": "Activé",
    "common.disabled": "Désactivé",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.seconds": "s",
    "common.minutes": "min",
    "common.hours": "h",
    "common.bytes": "octets",
    "common.language": "Langue",

    # ---- 导航 ----
    "nav.library": "Ma bibliothèque",
    "nav.plugins": "Plugins",
    "nav.settings": "Paramètres",
    "nav.stats": "Statistiques",
    "nav.insight": "Insight IA",

    # ---- 统计组件 ----
    "core.widget.topDocs": "Documents les plus consultés",
    "core.widget.heatmap": "Carte de chaleur des visites",
    "core.widget.stayTime": "Temps passé sur les documents",
    "core.widget.wordCount": "Nombre de mots",
    "core.widget.recentDocs": "Visites récentes",

    # ---- 主题切换 ----
    "core.theme.toLight": "Passer en mode clair",
    "core.theme.toDark": "Passer en mode sombre",
    "core.theme.selectTheme": "Choisir le thème",

    # ---- 学习页 ----
    "core.learn.markedCompleted": "Marqué comme terminé",
    "core.learn.unmarkedCompleted": "Marquage annulé",
    "core.learn.courseDisabledWarning": "Ce document dépend du plugin « Cours ». Les questions et blocs interactifs seront affichés en données brutes. Vous pouvez l'activer dans la page « Plugins ».",
    "core.learn.completed": "Terminé",
    "core.learn.markComplete": "Marquer comme terminé",
    "core.learn.readingMode": "Lecture du document",
    "core.learn.progressKnowledge": "{pos} / {total} points de connaissance",
    "core.learn.progressDoc": "{pos} / {total} documents",
    "core.learn.refToDoc": "Cette section fait référence au document « {name} »",
    "core.learn.gotoRefDoc": "Aller au document référencé",
    "core.learn.emptySection": "Ce point de connaissance n'a pas encore de contenu",
    "core.learn.prevKnowledge": "Point de connaissance précédent",
    "core.learn.unmarkComplete": "Annuler la marque de fin",
    "core.learn.markCurrentComplete": "Marquer ce point de connaissance comme terminé",
    "core.learn.nextKnowledge": "Point de connaissance suivant",
    "core.learn.unsupportedBlock": "Type de composant non pris en charge : {type}",
    "core.learn.ref": "Référence",
    "core.learn.choiceMultiple": "Question à choix multiples",
    "core.learn.choiceSingle": "Question à choix unique",
    "core.learn.multiSelect": "Réponses multiples",
    "core.learn.singleSelect": "Réponse unique",
    "core.learn.submit": "Soumettre",
    "core.learn.correct": "Bonne réponse",
    "core.learn.incorrect": "Mauvaise réponse",
    "core.learn.explanation": "Explication : {text}",
    "core.learn.gradeFailed": "Échec de la correction",
    "core.learn.fillBlank": "Question à compléter",
    "core.learn.aiGraded": "Correction IA",
    "core.learn.blankN": "Trou {n}",
    "core.learn.accuracy": "Précision {score}%",
    "core.learn.redo": "Recommencer",
    "core.learn.interactiveNoFile": "Le bloc interactif manque de configuration file",
    "core.learn.interactiveFallback": "Interactif dynamique",
    "core.learn.interactiveTitle": "Démo interactive",
    "core.learn.blockDepPrefix": "Ce composant (",
    "core.learn.blockDepMid": ") dépend du plugin « ",
    "core.learn.blockDepPlugin": " » (",
    "core.learn.blockDepSuffix": "), il est affiché en données brutes lorsqu'il n'est pas activé",
    "core.learn.interactiveNotRendered": "Bloc interactif non rendu",
    "core.learn.quizNotRendered": "Question non rendue",
    "core.learn.viewRaw": "Voir les données brutes",
    "core.learn.shortAnswer": "Question à réponse courte",
    "core.learn.answerPlaceholder": "Saisissez votre réponse...",
    "core.learn.keywords": "Mots-clés essentiels : {text}",
    "core.learn.submitGrade": "Soumettre pour correction",
    "core.learn.aiFeedback": "Commentaire IA : ",
    "core.learn.hint": "Indice : {text}",
    "core.plugin.unknown": "Plugin inconnu",
    "core.plugin.course": "Cours",

    # ---- 文档库 ----
    "core.library.quiz": "Quiz",
    "core.library.kindCourse": "Cours",
    "core.library.kindNote": "Notes",
    "core.library.kindKb": "Base de connaissances",
    "core.library.kindCanvas": "Canvas",
    "core.library.empty": "Aucun contenu",
    "core.library.emptyLibrary": "Cette bibliothèque est vide. Importez un pack de cours depuis l'accueil ou créez une nouvelle collection.",
    "core.library.library": "Bibliothèques",
    "core.library.deleteLibTitle": "Supprimer la bibliothèque",
    "core.library.deleteLibDesc": "Supprimer cette bibliothèque ? Tout son contenu sera supprimé, sans possibilité de restauration.",
    "core.library.deletedLib": "Bibliothèque supprimée",
    "core.library.unmountTitle": "Démonter le lien symbolique",
    "core.library.unmountNameFallback": "ce lien symbolique",
    "core.library.unmountDesc": "« {name} » sera retiré de la liste. Les fichiers sur le disque ne seront pas supprimés.",
    "core.library.unmount": "Démonter",
    "core.library.unmounted": "Démonté",
    "core.library.singleFile": "(fichier unique)",
    "core.library.symlink": "Liens symboliques",
    "core.library.pluginBadge": "Plugin",
    "core.library.emptyLibraries": "Aucune bibliothèque. Importez un pack de cours depuis le coin supérieur droit, ou créez-en une.",
    "core.library.noSymlinks": "Aucun lien symbolique. Cliquez à droite pour ajouter un dossier ou un fichier local",
    "core.library.collectionCount": "{count} collections",
    "core.library.searchPlaceholder": "Rechercher des collections...",
    "core.library.gridView": "Vue en grille",
    "core.library.listView": "Vue en liste",
    "core.library.unitChapter": "Chapitres",
    "core.library.unitCanvas": "Canvas",
    "core.library.unitDoc": "Documents",
    "core.library.noSearchResults": "Aucune collection correspondante.",
    "core.library.emptyCollections": "Cette bibliothèque n'a pas encore de collection. Importez un pack de cours ou créez-en une.",
    "core.library.selectPlaceholder": "Sélectionnez une bibliothèque ou un lien symbolique pour afficher son contenu.",
    "core.library.newLibTitle": "Nouvelle bibliothèque",
    "core.library.namePlaceholder": "ex. Cours de spécialité",
    "core.library.descriptionOptional": "Description (facultatif)",
    "core.library.descPlaceholder": "Ce que contient cette bibliothèque",
    "core.library.createdLib": "Bibliothèque créée",
    "core.library.newCanvas": "Nouveau canvas",
    "core.library.newCanvasTitle": "Nouveau canvas",
    "core.library.newCanvasPlaceholder": "Nom du canvas",
    "core.library.newCanvasDefault": "Canvas sans titre",
    "core.library.createdCanvas": "Canvas créé",
    "core.library.newDoc": "Nouveau document",
    "core.library.newDocTitle": "Nouveau document",
    "core.library.newDocPlaceholder": "Nom du document",
    "core.library.newDocDefault": "Document sans titre",
    "core.library.createdDoc": "Document créé",
    "core.library.import": "Importer",
    "core.library.importFailed": "Échec de l'importation",
    "core.library.importedCourse": "Cours « {names} » importé",
    "core.library.importedNote": "Notes importées ({count} sections)",
    "core.library.importWarning": "Certains composants du contenu importé dépendent du plugin « {names} » ; ils seront affichés en données brutes tant qu'il n'est pas activé.",
    "core.library.importedCanvas": "Canvas « {name} » importé",
    "core.library.importedContent": "Contenu importé",
    "core.library.importTitle": "Importer du contenu",
    "core.library.importDesc": "Prend en charge les fichiers MetaPilot (.mpf/.canvas, format unifié : doc = contenu de cours, canvas = graphique), les packs de cours (zip) et les notes Markdown.",
    "core.library.tabMpf": "Fichier MetaPilot",
    "core.library.tabCourse": "Pack de cours",
    "core.library.mpfLabel": "Fichier MetaPilot (.mpf / .canvas)",
    "core.library.mpfHint": "Le type doc est analysé comme cours/document ; les fichiers .canvas (Obsidian Canvas) sont automatiquement convertis en canvas.",
    "core.library.courseGateHint": "Importer un pack de cours (zip)",
    "core.library.courseFileLabel": "Fichier de pack de cours (.zip, contenant manifest.json)",
    "core.library.noteGateHint": "Importer des notes Markdown",
    "core.library.noteFileLabel": "Fichier Markdown / Obsidian (.md)",

    # ---- 编辑页 ----
    "core.edit.block.markdown": "Affichage (Markdown)",
    "core.edit.block.single_choice": "Choix unique",
    "core.edit.block.multiple_choice": "Choix multiples",
    "core.edit.block.fill_blank": "À compléter",
    "core.edit.block.short_answer": "Réponse courte",
    "core.edit.block.interactive": "Bloc interactif dynamique",
    "core.edit.block": "Composant",
    "core.edit.collectionInfo": "Informations du cours",
    "core.edit.summary": "Résumé",
    "core.edit.newDocName": "Nouveau chapitre",
    "core.edit.newSectionName": "Nouveau point de connaissance",
    "core.edit.deleteDocTitle": "Supprimer le chapitre",
    "core.edit.deleteDocDesc": "Supprimer ce chapitre ? Toutes ses sections et son contenu seront supprimés, sans possibilité de restauration.",
    "core.edit.deleteSectionTitle": "Supprimer la section",
    "core.edit.deleteSectionDesc": "Supprimer cette section ?",
    "core.edit.deleteBlockTitle": "Supprimer le composant",
    "core.edit.deleteBlockDesc": "Supprimer ce composant ?",
    "core.edit.newFolderTitle": "Nouveau dossier",
    "core.edit.newFolderDesc": "Saisissez le nom du nouveau dossier.",
    "core.edit.newFolderPlaceholder": "ex. Notes de chapitre",
    "core.edit.renameFolderTitle": "Renommer le dossier",
    "core.edit.deleteFolderTitle": "Supprimer le dossier",
    "core.edit.deleteFolderDesc": "Supprimer ce dossier ? Tous ses sous-dossiers et documents seront supprimés, sans possibilité de restauration.",
    "core.edit.createFailed": "Échec de la création",
    "core.edit.renameFailed": "Échec du renommage",
    "core.edit.deleteFailed": "Échec de la suppression",
    "core.edit.moveFailed": "Échec du déplacement",
    "core.edit.docSettings": "Paramètres du chapitre",
    "core.edit.docNameLabel": "Nom du chapitre",
    "core.edit.docTypeStudy": "Chapitre d'apprentissage",
    "core.edit.docTypeQuiz": "Chapitre de quiz",
    "core.edit.moveDocLabel": "Dossier (déplacer le document)",
    "core.edit.rootFolder": "Racine",
    "core.edit.docTypeHint": "Les chapitres d'apprentissage et de quiz peuvent être librement combinés pour séparer apprentissage et examen.",
    "core.edit.sectionSettings": "Paramètres du point de connaissance",
    "core.edit.sectionNameLabel": "Nom du point de connaissance",
    "core.edit.refDocLabel": "Référencer un autre document (référence de section)",
    "core.edit.noRef": "Aucune référence",
    "core.edit.refDocHint": "Une fois définie, la page d'apprentissage affiche une carte de référence et accède au document cible.",
    "core.edit.addBlockLabel": "Ajouter un composant",
    "core.edit.backToSection": "Retour à la section",
    "core.edit.blockSaved": "Composant enregistré",
    "core.edit.addSectionTitle": "Ajouter une section",
    "core.edit.noBlocks": "Aucun composant",
    "core.edit.noSections": "Aucune section",
    "core.edit.subFolder": "Sous-dossier",
    "core.edit.emptyFolder": "Dossier vide",
    "core.edit.mode": "Mode édition",
    "core.edit.dirty": "Modifications non enregistrées",
    "core.edit.saved": "Enregistré",
    "core.edit.newDoc": "Chapitre",
    "core.edit.newFolder": "Dossier",
    "core.edit.done": "Terminé",
    "core.edit.markdownContent": "Contenu Markdown",
    "core.edit.markdownPlaceholder": "# Titre\n\nCorps du texte, avec prise en charge de Markdown et des tableaux/listes de tâches GFM",
    "core.edit.question": "Question",
    "core.edit.options": "Options (une par ligne)",
    "core.edit.optionsPlaceholder": "Option A\nOption B\nOption C",
    "core.edit.correctIndex": "Index de la bonne réponse (à partir de 0)",
    "core.edit.correctIndexes": "Index des bonnes réponses (séparés par des virgules)",
    "core.edit.blanksAnswers": "Réponses de référence par trou (une par ligne)",
    "core.edit.blanksPlaceholder": "Réponse 1\nRéponse 2",
    "core.edit.reference": "Réponse de référence",
    "core.edit.keywordsLabel": "Mots-clés essentiels (séparés par des virgules, pour référence de l'IA)",
    "core.edit.keywordsPlaceholder": "mot-clé1,mot-clé2",
    "core.edit.aiGraded": "Utiliser la correction IA (questions subjectives)",
    "core.edit.title": "Titre",
    "core.edit.assetFile": "Fichier d'actif (chemin relatif à interactives/ du pack de cours)",
    "core.edit.iframeHeight": "Hauteur de l'iframe (px)",
    "core.edit.explanationLabel": "Explication / indice (facultatif)",

    # ---- 图表画布 ----
    "core.canvas.saved": "Canvas enregistré",
    "core.canvas.saveFailed": "Échec de l'enregistrement",
    "core.canvas.doubleClickEdit": "Double-cliquer pour modifier le texte",
    "core.canvas.notCanvas": "Ce recueil n'est pas un canvas.",
    "core.canvas.backToLibrary": "Retour à la bibliothèque",
    "core.canvas.badge": "Canvas",
    "core.canvas.dirty": "Modifications non enregistrées",
    "core.canvas.unsavedTitle": "Modifications non enregistrées",
    "core.canvas.unsavedDesc": "Le canvas contient des modifications non enregistrées. Enregistrer avant de quitter ?",
    "core.canvas.discardAndLeave": "Ne pas enregistrer et quitter",
    "core.canvas.saveAndLeave": "Enregistrer et quitter",
    "core.canvas.newTextNode": "Nouveau nœud de texte",
    "core.canvas.help": "Faites glisser les nœuds pour les déplacer ; sélection par zone sur l'espace vide, Maj pour la sélection multiple, Suppr pour supprimer, Ctrl+C/V pour copier-coller, Ctrl+Z pour annuler ; double-cliquez sur le texte pour le modifier ; faites glisser depuis un point de connexion sur le bord d'un nœud vers un autre nœud pour créer une liaison ; molette pour faire défiler, Ctrl+molette pour zoomer, maintenez la barre d'espace et faites glisser pour vous déplacer.",
    "core.canvas.undo": "Annuler (Ctrl+Z)",
    "core.canvas.redo": "Rétablir (Ctrl+Shift+Z)",
    "core.canvas.zoomOut": "Zoom arrière",
    "core.canvas.zoomIn": "Zoom avant",
    "core.canvas.fitView": "Ajuster au canvas",
    "core.canvas.empty": "(vide)",
    "core.canvas.group": "Grouper",
    "core.canvas.deleteNode": "Supprimer le nœud",
    "core.canvas.dragLink": "Faire glisser pour connecter",
    "core.canvas.emptyBoard": "Canvas vide. Cliquez sur « Nouveau nœud de texte » en haut à droite pour commencer.",
    "core.canvas.stats": "{nodes} nœuds · {edges} liaisons",
    "core.canvas.exportMpf": "Exporter .mpf",
    "core.canvas.exportCanvas": "Exporter .canvas",
    "core.canvas.export": "Exporter",
    "core.canvas.center": "Centrer",
    "core.canvas.alignLeft": "Aligner à gauche",
    "core.canvas.alignCenter": "Aligner au centre",
    "core.canvas.alignRight": "Aligner à droite",
    "core.canvas.edgePath": "Style de liaison",
    "core.canvas.pathSmooth": "Courbe lisse",
    "core.canvas.pathStraight": "Ligne droite",
    "core.canvas.pathSquare": "Ligne à angle droit",
    "core.canvas.resize": "Redimensionner",
    "core.canvas.groupSelection": "Grouper la sélection",
    "core.canvas.dragAddCard": "Faire glisser pour ajouter une carte",
    "core.canvas.dragAddNote": "Faire glisser pour ajouter une note",
    "core.canvas.dragAddNoteVault": "Faire glisser pour ajouter une note depuis la bibliothèque",
    "core.canvas.dragAddMediaVault": "Faire glisser pour ajouter un média depuis la bibliothèque",
    "core.canvas.paste": "Coller",
    "core.canvas.toggleNav": "Déplier/replier la navigation",
    "core.canvas.noCanvases": "Aucun canvas",
    "core.canvas.edgeStart": "Début",
    "core.canvas.edgeEnd": "Fin",
    "core.canvas.arrow": "Flèche",
    "core.canvas.toggleStartArrow": "Basculer la flèche de début",
    "core.canvas.toggleEndArrow": "Basculer la flèche de fin",
    "core.canvas.edgeLabel": "Étiquette",
    "core.canvas.colorTitle": "Couleur {color}",
    "core.canvas.clearColor": "Effacer la couleur",
    "core.canvas.deleteEdge": "Supprimer la liaison",
    "core.canvas.addNode": "Nouveau nœud",
    "core.canvas.addNodeText": "Texte",
    "core.canvas.addNodeFile": "Fichier",
    "core.canvas.addNodeLink": "Lien",
    "core.canvas.addNodeGroup": "Groupe",
    "core.canvas.addFileTitle": "Chemin du fichier",
    "core.canvas.addFileDesc": "Chemin relatif dans la bibliothèque, ex. notes/exemple.md, images/image.png (compatible Obsidian)",
    "core.canvas.addLinkTitle": "URL du lien",
    "core.canvas.addGroupTitle": "Étiquette du groupe",
    "core.canvas.groupName": "Nom du groupe",

    # ---- 统计页 ----
    "core.stats.intro": "Le noyau officiel fournit des composants statistiques de base ; des plugins comme « Cours » peuvent en apporter davantage. Faites glisser les cartes pour les repositionner, redimensionnez depuis le coin supérieur droit, et basculez l'option « Marquer la source des composants » dans les paramètres.",
    "core.stats.resize": "Redimensionner (actuellement {size})",
    "core.stats.hide": "Masquer le composant",
    "core.stats.manage": "Gérer les composants",
    "core.stats.hiddenCount": "{count} masqués",
    "core.stats.manageDesc": "Masquez des composants sous « Affichés », ou restaurez-les à tout moment depuis le panneau « Masqués » ; faites glisser les cartes de la page de statistiques pour ajuster la position et l'ordre.",
    "core.stats.none": "Aucun composant statistique disponible",
    "core.stats.visibleCount": "Affichés ({count})",
    "core.stats.hiddenTab": "Masqués ({count})",
    "core.stats.noHidden": "Aucun composant masqué : tous les composants sont affichés",
    "core.stats.resetLayout": "Restaurer la disposition par défaut",
    "core.stats.showAll": "Tout afficher",
    "core.stats.restore": "Restaurer l'affichage",
    "core.stats.noVisits": "Aucun enregistrement de visite",
    "core.stats.noStayTime": "Aucun enregistrement de temps de présence",
    "core.stats.visits": "{count} visites",
    "core.stats.wordUnit": "mots",
    "core.stats.unknownWidget": "Composant inconnu",
    "core.stats.heatmap3m": "Carte de chaleur des visites des 3 derniers mois",
    "core.stats.heatmapTooltip": "{month}/{day} · {count} visites",
    "core.stats.heatmapLess": "Moins",
    "core.stats.heatmapMore": "Plus",
    "core.stats.hourly": "Répartition des visites par heure",
    "core.stats.hourTooltip": "{hour}:00 · {count} visites",
    "core.stats.hourLabel": "{hour}:00",
    "core.stats.monthLabel": "{month}",
    "core.stats.weekdays": "L,M,M,J,V,S,D",
    "core.stats.courseDisabled": "Dépend du plugin « Cours », non activé",
    "core.stats.totalStudy": "Apprentissage cumulé",
    "core.stats.chartMinutes": "Minutes",
    "core.stats.noStudyRecords": "Aucun enregistrement d'apprentissage",
    "core.stats.providedBy": "Fourni par le plugin « {name} »",
    "core.stats.providedByTooltip": "Fourni par le plugin {name}",

    # ---- 通用弹窗 / toast ----
    "core.dialog.selectPlaceholder": "Veuillez sélectionner…",
    "core.toast.copied": "Copié dans le presse-papiers",
    "core.widget.aiUsage": "Utilisation IA",
    "core.stats.rangeToday": "Aujourd'hui",
    "core.stats.rangeWeek": "Cette semaine",
    "core.stats.rangeMonth": "Ce mois-ci",
    "core.stats.rangeAll": "Tout",
    "core.stats.aiCalls": "Nombre d'appels",
    "core.stats.aiTokens": "Utilisation de tokens",
    "core.stats.aiCost": "Coût",
    "core.stats.aiTokensDetail": "Entrée {in} / cache {cached} / sortie {out}",
    "core.stats.aiCallsShort": "{n} appels",
    "core.stats.aiTokensShort": "{n} tokens",
    "core.stats.aiUsageEmpty": "Aucune utilisation IA pour le moment (les appels passant par la passerelle unifiée sont enregistrés ici).",

    # ---- course ----
    "course.exportFailed": "Échec de l'exportation",
    "course.pluginDisabledWarning": "Ce document dépend du plugin « Cours ». La progression de l'apprentissage et les interactions de quiz ne sont pas disponibles. Vous pouvez l'activer dans la page « Plugins ».",
    "course.backToLibrary": "Retour à la bibliothèque",
    "course.noDescription": "Aucun résumé",
    "course.authorLabel": "Auteur : {author}",
    "course.export": "Exporter",
    "course.continueLearning": "Continuer l'apprentissage",
    "course.learningProgress": "Progression de l'apprentissage",
    "course.progressCount": "{completed} / {total} points de connaissance",
    "course.lastLearned": "Dernier apprentissage : {name}",
    "course.progressRequiresPlugin": "La progression de l'apprentissage dépend du plugin « Cours ». Une fois activé, vous pouvez marquer les sections comme terminées et suivre votre dernière position d'apprentissage.",
    "course.quiz": "Quiz",
    "course.noSectionsInChapter": "Ce chapitre ne contient aucune section",
    "course.noChapters": "Ce cours n'a pas encore de chapitre. Cliquez sur « Modifier » en haut à droite pour commencer la création.",
    "course.library.newCourse": "Nouveau cours",
    "course.library.newCourseTitle": "Nouveau cours",
    "course.library.newCoursePlaceholder": "Nom du cours",
    "course.library.newCourseDefault": "Cours sans titre",
    "course.library.createdCourse": "Cours créé",
    "course.library.createCourseFailed": "Échec de la création du cours",
    "course.library.toCourse": "Convertir en cours",
    "course.library.toCourseTitle": "Convertir en cours",
    "course.library.toCourseDesc": "Convertir « {name} » en cours ? Un cours est un document corrigé qui active la progression de l'apprentissage, la correction et les blocs interactifs ; ces capacités de cours ne sont pas disponibles tant que le plugin « Cours » n'est pas activé.",
    "course.library.toCourseConfirm": "Convertir en cours",
    "course.library.convertedCourse": "« {name} » a été converti en cours",
    "course.library.convertCourseFailed": "Échec de la conversion en cours",

    # ---- insight ----
    "insight.pageTitle": "Insight IA",
    "insight.intro": "Sélectionnez une série de documents ou de bibliothèques, créez un index, puis laissez l'IA réfléchir : elle examine les liens entre les ressources et génère des réponses, suggestions ou graphiques/cours selon quatre modes.",
    "insight.introWithSymlink": "Sélectionnez une série de documents, de bibliothèques ou de dossiers locaux, créez un index, puis laissez l'IA réfléchir : elle examine les liens entre les ressources et génère des réponses, suggestions ou graphiques/cours selon quatre modes.",
    "insight.stepIndex": "Première étape · Créer un index",
    "insight.stepAsk": "Deuxième étape · Interroger l'IA",
    "insight.stepIndexQuoted": "« Première étape · Créer un index »",
    "insight.mustIndexBefore": "Créez d'abord un index avant de poser une question ; si vous interrogez sans index, il sera créé automatiquement (progression affichée).",
    "insight.noIndexedBefore": "Aucune source indexée pour le moment. Allez d'abord à",
    "insight.noIndexedAfter": "et créez un index vectoriel du contenu sélectionné avant d'interroger.",
    "insight.noIndexedAfterWithSymlink": "et créez un index vectoriel des documents / dossiers locaux sélectionnés avant d'interroger.",
    "insight.vectorModelTitle": "Modèle vectoriel et service local",
    "insight.embeddingRunning": "En cours d'exécution",
    "insight.embeddingNotReady": "Non prêt",
    "insight.selectModelPlaceholder": "Choisir un modèle d'embedding",
    "insight.stopService": "Arrêter le service",
    "insight.startService": "Démarrer le service (télécharge le modèle sélectionné au premier lancement)",
    "insight.modelDownloadHint": "Le téléchargement du modèle tente automatiquement plusieurs sources ; au premier téléchargement, attendez que le modèle soit prêt, la page actualisera automatiquement le statut. Les sources de téléchargement et la liste des modèles suivent la configuration du backend.",
    "insight.selectSourcesTitle": "Sélectionner les sources de données (sélection multiple)",
    "insight.indexIntro": "Sélection possible par bibliothèque, recueil unique ou document unique ; l'index est stocké indépendamment pour chaque source.",
    "insight.indexIntroWithSymlink": "Sélection possible par bibliothèque, recueil, document, ou n'importe quel chemin d'un dossier local monté ; l'index est stocké indépendamment pour chaque source.",
    "insight.indexing": "Indexation en cours...",
    "insight.indexingProgress": "{done}/{total} segments indexés",
    "insight.indexQueued": "La création de l'index a commencé, vous pouvez suivre la progression ci-dessous",
    "insight.buildVectorIndex": "Créer un index vectoriel",
    "insight.noSources": "Aucune source disponible : créez d'abord une bibliothèque dans « Ma bibliothèque ».",
    "insight.noSourcesWithSymlink": "Aucune source disponible : créez d'abord une bibliothèque dans « Ma bibliothèque », ou montez un dossier local.",
    "insight.askSourcesTitle": "Sélectionner les sources à analyser (sélection multiple, recherche fusionnée)",
    "insight.askTitle": "Réflexion IA (les réponses citent leurs sources)",
    "insight.askPlaceholder": "Interrogez l'IA, par ex. : « Quels liens existent entre ces documents ? »",
    "insight.refSources": "Sources de référence",
    "insight.sourceRef": "[Source {n}]",
    "insight.asking": "Recherche et génération de la réponse en cours...",
    "insight.inputPlaceholder": "Saisissez votre question ou votre direction de réflexion...",
    "insight.askButton": "Interroger",
    "insight.groupLibrary": "Documents de bibliothèque (bibliothèque / recueil / document)",
    "insight.groupSymlink": "Montages de dossiers locaux",
    "insight.indexedCount": "{count} segments indexés",
    "insight.notIndexed": "Non indexé",
    "insight.pluginHint": "Insight IA : analyser les liens entre les ressources et générer du contenu",
    "insight.loadResourcesFailed": "Échec du chargement des sources de données",
    "insight.startServiceToast": "Démarrage du service (téléchargera automatiquement le modèle sélectionné au premier lancement)",
    "insight.startFailed": "Échec du démarrage",
    "insight.serviceStopped": "Service arrêté",
    "insight.indexDone": "Indexation terminée : {ok}/{total} sources de données",
    "insight.indexFailed": "Échec de l'indexation",
    "insight.askFailed": "Échec de la question",
    "insight.modeTitle": "Mode de réflexion",
    "insight.modeIntro": "Choisissez une façon de penser ; l'IA consultera les ressources sélectionnées selon ce mode et générera du contenu.",
    "insight.modeAssist": "Réflexion assistée",
    "insight.modeAssistDesc": "Trouver les liens entre les ressources, répondre et suggérer",
    "insight.modeWander": "Divagation mentale",
    "insight.modeWanderDesc": "Combiner les ressources et votre direction de réflexion pour des associations libres",
    "insight.modeReflect": "Synthèse réflexive",
    "insight.modeReflectDesc": "Faire ressortir les liens et angles morts que vous n'avez peut-être pas remarqués",
    "insight.modePlan": "Planification d'insight",
    "insight.modePlanDesc": "Raisonnement en plusieurs étapes pour générer un graphique ou un cours qui vous apprend",
    "insight.planOutputTitle": "Type de génération",
    "insight.planOutputCanvas": "Graphique de connaissances (canvas)",
    "insight.planOutputCourse": "Micro-cours (documents)",
    "insight.planLibraryTitle": "Enregistrer dans la bibliothèque",
    "insight.planLibraryAuto": "Bibliothèque par défaut (la première)",
    "insight.planGoalPlaceholder": "Saisissez l'objectif de la planification, par ex. : dégager les concepts clés et les liens de ces ressources pour me les faire comprendre en un minimum de temps",
    "insight.planButton": "Démarrer la planification d'insight",
    "insight.planning": "L'IA analyse les liens entre les ressources en plusieurs étapes et génère le contenu ; cela peut prendre 1 à 2 minutes...",
    "insight.planDone": "« {name} » a été généré",
    "insight.planOpenCanvas": "Ouvrir le graphique",
    "insight.planOpenCourse": "Ouvrir le cours",
    "insight.planSummary": "Résumé de la planification",
    "insight.planFailed": "Échec de la planification d'insight",
    "insight.planRoadmap": "Feuille de route d'exécution de l'IA",
    "insight.planThinking": "Processus de réflexion de l'IA",
    "insight.planStep.retrieve": "Récupérer les ressources",
    "insight.planStep.plan": "Analyse des thèmes et des liens",
    "insight.planStep.review": "Réflexion critique",
    "insight.planStep.generateCanvas": "Générer le graphique de connaissances",
    "insight.planStep.generateCourse": "Générer le micro-cours",
    "insight.planStep.save": "Enregistrer dans la bibliothèque",
    "insight.planStepRunning": "En cours…",
    "insight.planConnecting": "Connexion à l'IA et planification de la feuille de route…",
    "insight.autoIndexing": "Les sources sélectionnées ne sont pas encore indexées, création automatique de l'index ({done}/{total})...",
    "insight.autoIndexDone": "Indexation terminée, poursuite de la génération...",
    "insight.autoIndexFailed": "Échec de la création automatique de l'index ; créez d'abord l'index manuellement à la première étape",
    "insight.symlinkBrowse": "Parcourir le dossier",
    "insight.treeEmpty": "(vide)",
    "insight.kbTitle": "Bibliothèque de recherche de données",
    "insight.goAsk": "Aller aux questions",
    "insight.selectedCount": "{count} éléments sélectionnés",
    "insight.kbIndexed": "{count} sources indexées",
    "insight.collapsePanel": "Replier le panneau de bibliothèque de recherche",
    "insight.expandPanel": "Déplier le panneau de bibliothèque de recherche",
    "insight.kbHint": "Cochez bibliothèques / recueils / documents comme portée de recherche : vous pouvez créer un index ou interroger directement ; les sources non indexées sont indexées automatiquement lors de la question.",
    "insight.kbHintWithSymlink": "Cochez bibliothèques / recueils / documents ou dossiers locaux comme portée de recherche : vous pouvez créer un index ou interroger directement ; les sources non indexées sont indexées automatiquement lors de la question.",
    "insight.buildIndexTitle": "Créer un index vectoriel",
    "insight.buildIndexHint": "{count} sources de données sélectionnées (ajustables dans la « Bibliothèque de recherche de données » à gauche) ; les sources non indexées seront également indexées.",

    # ---- symlink ----
    "symlink.fileBrowser": "Explorateur de fichiers",
    "symlink.symlinkPlugin": "Plugin de liens symboliques",
    "symlink.pluginHint": "Parcourir et lire/écrire les dossiers locaux",
    "symlink.linkLocalDoc": "Lier des documents locaux (lien symbolique)",
    "symlink.addMountDesc1": "Lie un ",
    "symlink.addMountDesc2": " ou ",
    "symlink.addMountDesc3": " sur votre disque local ; les fichiers d'origine ne sont ni copiés ni déplacés. Une fois lié, vous pouvez le parcourir, le lire et le modifier comme un document dans l'explorateur de fichiers.",
    "symlink.mounts": "Montages",
    "symlink.mount": "Monter",
    "symlink.thatMount": "ce montage",
    "symlink.unmount": "Démonter",
    "symlink.unmountSymlink": "Démonter le lien symbolique",
    "symlink.unmountConfirmDesc": "« {name} » sera retiré de la liste. Les fichiers sur le disque ne seront pas supprimés.",
    "symlink.noMounts": "Aucun montage. Cliquez en haut à droite pour ajouter un dossier ou un fichier local",
    "symlink.currentMountRoot": "Racine du montage actuel : {root}",
    "symlink.pleaseMount": "Veuillez d'abord monter un dossier ou un fichier local",
    "symlink.mountSuccess": "Montage réussi",
    "symlink.mountFailed": "Échec du montage",
    "symlink.displayName": "Nom d'affichage",
    "symlink.namePlaceholder": "ex. Mes notes",
    "symlink.localPathLabel": "Chemin local (dossier ou fichier)",
    "symlink.pathPlaceholder": "Cliquez sur « Parcourir » pour choisir, ou saisissez manuellement (Windows/Linux pris en charge)",
    "symlink.collapse": "Replier",
    "symlink.browse": "Parcourir",
    "symlink.afterMountHint": "Après le montage, vous pouvez parcourir, lire et modifier les fichiers texte du dossier dans l'explorateur de fichiers (l'accès est limité à la racine du montage).",
    "symlink.directory": "Répertoires",
    "symlink.folder": "Dossier",
    "symlink.file": "Fichier",
    "symlink.singleFile": "Fichier unique",
    "symlink.singleFileNote": "(fichier unique)",
    "symlink.singleFileMount": "(montage de fichier unique)",
    "symlink.rootDir": "(racine)",
    "symlink.noSubfolders": "Aucun sous-dossier",
    "symlink.emptyDir": "Répertoire vide",
    "symlink.expandDir": "Déplier le répertoire",
    "symlink.collapseDir": "Replier le répertoire",
    "symlink.newFolder": "Nouveau dossier",
    "symlink.newFolderDesc": "Saisissez le nom du nouveau dossier.",
    "symlink.newFolderPlaceholder": "ex. Notes de chapitre",
    "symlink.searchPlaceholder": "Rechercher…",
    "symlink.gridView": "Vue en grille",
    "symlink.listView": "Vue en liste",
    "symlink.backToList": "Retour à la liste",
    "symlink.reveal": "Localiser",
    "symlink.revealInFileManager": "Afficher dans le gestionnaire de fichiers",
    "symlink.openWithDefault": "Ouvrir avec l'application par défaut",
    "symlink.editing": "Édition : {path}",
    "symlink.saved": "Enregistré",
    "symlink.saveFailed": "Échec de l'enregistrement",
    "symlink.createFailed": "Échec de la création",
    "symlink.deleteFile": "Supprimer le fichier",
    "symlink.deleteConfirmDesc": "Supprimer « {target} » ?",
    "symlink.deleteDirWarning": "Le dossier sera supprimé de manière récursive, sans possibilité de restauration.",
    "symlink.deleteFailed": "Échec de la suppression",
    "symlink.openedWithDefault": "Ouvert avec l'application par défaut du système",
    "symlink.openFailed": "Échec de l'ouverture",
    "symlink.readFailed": "Échec de la lecture",
    "symlink.noInlinePreview": "Ce type de fichier ne prend pas en charge l'aperçu intégré",
    "symlink.noInlinePreviewHint": "Ce type de fichier ne prend pas en charge l'aperçu intégré ; clic droit puis « Ouvrir avec l'application par défaut »",
    "symlink.noMatch": "Aucun élément correspondant.",
    "symlink.goUp": "Niveau supérieur",
    "symlink.myComputer": "Poste de travail",
    "symlink.reading": "Lecture en cours…",
    "symlink.emptyFolder": "Dossier vide",
    "symlink.selectedFolder": "Dossier : {path}",
    "symlink.selectedFile": "Fichier : {path}",
    "symlink.selectHint": "Cliquez pour sélectionner un dossier ou un fichier ; double-cliquez sur un dossier pour entrer",
    "symlink.selectThisFolder": "Sélectionner ce dossier",
    "symlink.selectThisFile": "Sélectionner ce fichier",

    # ---- sys ----
    "sys.title": "Paramètres",
    "sys.subtitle": "Contrôlez le comportement des notifications liées aux plugins. MetaPilot est une bibliothèque de documents : les documents peuvent toujours être ouverts pour consultation, les parties non rendues sont affichées en données brutes ; les notifications ne servent qu'à rappeler et n'interrompent jamais vos actions.",
    "sys.language": "Langue",
    "sys.languageDesc": "Langue d'affichage de l'interface ; appliquée immédiatement et enregistrée localement (localStorage).",
    "sys.appearance": "Apparence",
    "sys.appearanceDesc": "Le mode sombre / clair peut être basculé à tout moment ; les thèmes spéciaux sont fournis par le plugin « Thèmes » (à activer dans la page de gestion des plugins).",
    "sys.pluginWarnings": "Alertes de plugins",
    "sys.pluginWarningsDesc": "À l'ouverture d'un document dépendant d'un plugin désactivé (comme Cours, Base de connaissances), affiche une bulle d'alerte en haut : « Ce contenu dépend du plugin xx, certains composants peuvent ne pas être rendus ».",
    "sys.pluginErrors": "Erreurs de plugins",
    "sys.pluginErrorsDesc": "Lorsqu'une action échoue parce qu'un plugin n'est pas activé (par ex. correction IA, questions de base de connaissances), affiche une bulle d'erreur en haut ; une fois désactivé, ces erreurs sont silencieusement ignorées.",
    "sys.componentSource": "Marquer la source des composants",
    "sys.componentSourceDesc": "Lorsqu'il est activé, les composants fournis par des plugins sont marqués avec l'icône du plugin (survolez pour voir le nom) dans les pages bibliothèque, statistiques, etc. ; le noyau officiel (MetaPilot lui-même) n'est pas marqué. Une fois désactivé, aucune marque de source n'est affichée.",
    "sys.localOnly": "Ces préférences ne sont enregistrées que localement dans le navigateur (localStorage) et n'affectent pas les autres appareils.",
    "sys.plugins.title": "Gestion des plugins",
    "sys.plugins.headerPrefix": "Les plugins sont répartis en trois catégories : personnalisés par l'utilisateur, officiels et noyau officiel. Un plugin est un paquet de fonctionnalités indépendant situé dans le répertoire ",
    "sys.plugins.headerSuffix": " du backend ; parcourez et installez depuis la « Boutique de plugins », ou téléversez vos propres plugins.",
    "sys.plugins.tabLocal": "Plugins locaux",
    "sys.plugins.tabStore": "Boutique de plugins",
    "sys.plugins.filterByTag": "Filtrer par étiquette :",
    "sys.plugins.sourceUser": "Plugins personnalisés par l'utilisateur",
    "sys.plugins.sourceUserDesc": "Développez les vôtres, installez depuis la boutique de plugins, ou téléversez un zip ; ils peuvent être désactivés ou supprimés.",
    "sys.plugins.sourceOfficial": "Plugins officiels",
    "sys.plugins.sourceOfficialDesc": "Plugins pratiques développés officiellement par MetaPilot ; activables ou désactivables, mais non supprimables.",
    "sys.plugins.sourceCore": "Noyau officiel",
    "sys.plugins.sourceCoreDesc": "MetaPilot lui-même : navigation dans la bibliothèque de documents et lecture Markdown. Ne peut pas être désactivé ni supprimé.",
    "sys.plugins.enabledToast": "Plugin activé",
    "sys.plugins.disabledToast": "Plugin désactivé",
    "sys.plugins.opFailed": "Échec de l'opération",
    "sys.plugins.deleteTitle": "Supprimer le plugin",
    "sys.plugins.deleteDesc": "Supprimer le plugin « {name} » ? Le répertoire backend/plugins/{id} sera physiquement supprimé, sans possibilité de restauration.",
    "sys.plugins.deletedToast": "Plugin « {name} » supprimé",
    "sys.plugins.deleteFailed": "Échec de la suppression",
    "sys.plugins.idLabel": "id :",
    "sys.plugins.dependsOn": "Plugins dépendants : ",
    "sys.plugins.missingDeps": "Dépendances manquantes (à activer d'abord) : ",
    "sys.plugins.featureCourseImport": "Importation / exportation de packs de cours",
    "sys.plugins.featureCourseFlow": "Apprentissage par chapitres et points de connaissance (flux de composants)",
    "sys.plugins.featureCourseProgress": "Progression de l'apprentissage et statistiques de durée",
    "sys.plugins.featureCourseGrading": "Correction IA des questions subjectives",
    "sys.plugins.featureCourseInteractive": "Rendu des blocs interactifs dynamiques",
    "sys.plugins.featureInsightIndex": "Indexation vectorielle multi-granularité des sources (bibliothèque / recueil / document / dossier local)",
    "sys.plugins.featureInsightModes": "Quatre modes de réflexion (réflexion assistée / divagation mentale / synthèse réflexive / planification d'insight)",
    "sys.plugins.featureInsightPlan": "Raisonnement en plusieurs étapes pour générer des graphiques et micro-cours (.mpf)",
    "sys.plugins.needEnablePrefix": "Veuillez activer le plugin « ",
    "sys.plugins.needEnableSuffix": " » pour utiliser ",
    "sys.plugins.thisFeature": "cette fonctionnalité",
    "sys.plugins.goEnable": "Activer dans la gestion des plugins",
    "sys.plugins.uploadTitle": "Téléverser un plugin (installation locale)",
    "sys.plugins.uploadDescPrefix": "Sélectionnez un zip de plugin empaqueté selon la spécification (contenant le répertoire racine ",
    "sys.plugins.uploadDescSuffix": " ; voir la spécification de développement de plugins §3). Il apparaît immédiatement dans la liste ci-dessous après l'installation, et peut être désactivé ou supprimé.",
    "sys.plugins.uploadInstall": "Installation locale",
    "sys.plugins.uploadSuccess": "Plugin installé",
    "sys.plugins.uploadFailed": "Échec de l'installation",
    "sys.store.storeUnavailable": "Impossible d'accéder à la boutique de plugins",
    "sys.store.installedToast": "Plugin « {name} » installé",
    "sys.store.installFailed": "Échec de l'installation",
    "sys.store.localInstalledToast": "Plugin installé localement",
    "sys.store.publishedToast": "Publié dans la boutique de plugins",
    "sys.store.uploadFailed": "Échec du téléversement",
    "sys.store.headerPrefix": "Parcourez, filtrez et installez des plugins depuis la boutique (l'adresse de la boutique est configurée par le backend ",
    "sys.store.headerSuffix": ").",
    "sys.store.checkUpdates": "Vérifier les mises à jour",
    "sys.store.emptyFiltered": "Aucun plugin correspondant dans la boutique.",
    "sys.store.installed": "Installé",
    "sys.store.install": "Installer",
    "sys.store.uploadTitle": "Téléverser un plugin",
    "sys.store.uploadDescPrefix": "Sélectionnez un zip de plugin empaqueté selon la spécification (contenant le répertoire racine ",
    "sys.store.uploadDescSuffix": " ; voir la spécification de développement de plugins §3) : vous pouvez l'installer localement ou le publier dans la boutique.",
    "sys.store.uploadLocal": "Installation locale",
    "sys.store.uploadPublish": "Publier dans la boutique",
    "sys.theme.mode": "Mode sombre / clair",
    "sys.theme.light": "Clair",
    "sys.theme.dark": "Sombre",
    "sys.theme.featured": "Thèmes spéciaux",
    "sys.theme.pluginDisabled": "Les thèmes sont fournis par le plugin « Thèmes », actuellement non activé.",
    "sys.theme.defaultName": "Par défaut",
    "sys.theme.defaultDesc": "Suivre la palette du système",
    "sys.plugins.changelogBtn": "Historique des versions",
    "sys.plugins.changelogTitle": "{name} · Historique des versions",
    "sys.plugins.changelogDesc": "Version actuellement installée : v{version} ; la chronologie présente l'historique des versions par ordre décroissant.",
    "sys.plugins.changelogEmpty": "Ce plugin n'a pas encore d'historique de versions.",
    "sys.plugins.currentVersion": "Version actuelle",
    "sys.ai.title": "Services IA (passerelle unifiée)",
    "sys.ai.desc": "Tous les appels IA des plugins transitent par MetaPilot ; les clés et adresses ne sont stockées que dans le fichier .env du backend — plugins et frontend n'accèdent jamais au texte en clair.",
    "sys.ai.loadFailed": "Échec du chargement de la configuration IA",
    "sys.ai.provider": "Fournisseur d'API",
    "sys.ai.providerOpenai": "Compatible OpenAI (y compris MiniMax / DeepSeek, etc.)",
    "sys.ai.providerAnthropic": "Anthropic",
    "sys.ai.providerLocal": "Modèles locaux (intégrés)",
    "sys.ai.providerNone": "Désactiver l'IA cloud",
    "sys.ai.chatModel": "Modèle de chat",
    "sys.ai.baseUrl": "Adresse API",
    "sys.ai.apiKey": "Clé API",
    "sys.ai.apiKeyPlaceholder": "Configurée (laisser vide pour conserver la valeur actuelle)",
    "sys.ai.embeddingTitle": "Vecteurs (embedding)",
    "sys.ai.embeddingProvider": "Service vectoriel",
    "sys.ai.embeddingLocal": "Local intégré (à télécharger)",
    "sys.ai.embeddingOpenai": "Cloud (via l'adresse API ci-dessus)",
    "sys.ai.embeddingNone": "Désactiver les vecteurs",
    "sys.ai.embeddingModel": "Modèle vectoriel",
    "sys.ai.embeddingUrl": "Adresse vectorielle locale",
    "sys.ai.prices": "Tarifs des modèles (par million de tokens)",
    "sys.ai.pricesHint": "Utilisés pour l'estimation des coûts de la page de statistiques ; prix unitaires cache / entrée / sortie, devise $ ou ¥",
    "sys.ai.priceModel": "Modèle",
    "sys.ai.priceInput": "Entrée",
    "sys.ai.priceCached": "Cache",
    "sys.ai.priceOutput": "Sortie",
    "sys.ai.addPrice": "Ajouter un tarif de modèle",
    "sys.ai.currency": "Devise par défaut",
    "sys.ai.save": "Enregistrer la configuration",
    "sys.ai.saved": "Configuration IA enregistrée (écrite dans .env)",
    "sys.ai.saveFailed": "Échec de l'enregistrement",
    "sys.ai.test": "Tester la connexion",
    "sys.ai.testing": "Test en cours...",
    "sys.ai.testOk": "Connexion réussie : {model} (entrée {in} / sortie {out} tokens)",
    "sys.ai.testFailed": "Échec de la connexion",
    "sys.ai.localTitle": "Modèles locaux intégrés",
    "sys.ai.localDesc": "Téléchargement en un clic en cas de besoin (plusieurs miroirs essayés automatiquement), puis démarrez et utilisez",
    "sys.ai.downloaded": "Téléchargé",
    "sys.ai.notDownloaded": "Non téléchargé",
    "sys.ai.downloading": "Téléchargement en cours...",
    "sys.ai.download": "Télécharger",
    "sys.ai.start": "Démarrer",
    "sys.ai.startFailed": "Échec du démarrage",
    "sys.ai.stop": "Arrêter",
    "sys.ai.running": "En cours d'exécution",
    "sys.ai.notRunning": "Arrêté",
    "sys.ai.modelKindEmbedding": "Vecteur",
    "sys.ai.modelKindLlm": "Conversation",
    "sys.ai.modelKindRerank": "Reclassement",
    "sys.ai.localOnlyHint": "Ces configurations ne sont stockées que dans le .env local et ne sont jamais envoyées à aucun service.",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "Ajouter un lien symbolique",
    "core.library.defaultLib": "Par défaut",
    "core.library.defaultSet": "Défini comme bibliothèque par défaut",
    "core.library.menuMore": "Plus d'actions",
    "core.library.pin": "Épingler",
    "core.library.pinned": "Épinglé",
    "core.library.pinnedLib": "Épinglé en haut",
    "core.library.renameLib": "Renommer",
    "core.library.renameLibTitle": "Renommer la bibliothèque",
    "core.library.renamedLib": "Bibliothèque renommée",
    "core.library.setDefault": "Définir par défaut",
    "core.library.unpin": "Désépingler",
    "core.library.unpinnedLib": "Désépinglé",
}
