# -*- coding: utf-8 -*-
"""MetaPilot UI 词典（日本語 / Japanese）。

key 集合は client/src/i18n/locales/zh-CN/ 配下 6 ファイル（common / core / course /
insight / symlink / sys）と完全に一致する。{xxx} プレースホルダはそのまま保持。
引用符は日本語の慣例に従い「」を使用。
"""

UI_DICT: dict[str, str] = {
  # ---- common（汎用） ----
  "common.save": "保存",
  "common.cancel": "キャンセル",
  "common.confirm": "確認",
  "common.delete": "削除",
  "common.edit": "編集",
  "common.search": "検索",
  "common.create": "作成",
  "common.add": "追加",
  "common.rename": "名前の変更",
  "common.close": "閉じる",
  "common.refresh": "更新",
  "common.loading": "読み込み中…",
  "common.empty": "データがありません",
  "common.back": "戻る",
  "common.open": "開く",
  "common.all": "すべて",
  "common.none": "なし",
  "common.optional": "任意",
  "common.required": "必須",
  "common.name": "名前",
  "common.description": "説明",
  "common.author": "作成者",
  "common.version": "バージョン",
  "common.size": "サイズ",
  "common.path": "パス",
  "common.type": "タイプ",
  "common.status": "ステータス",
  "common.success": "成功",
  "common.failed": "失敗",
  "common.error": "エラー",
  "common.unknown": "不明",
  "common.actions": "操作",
  "common.more": "もっと見る",
  "common.details": "詳細",
  "common.preview": "プレビュー",
  "common.enabled": "有効",
  "common.disabled": "無効",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.seconds": "秒",
  "common.minutes": "分",
  "common.hours": "時間",
  "common.bytes": "バイト",
  "common.language": "言語",

  # ---- ナビゲーション ----
  "nav.library": "マイライブラリ",
  "nav.plugins": "プラグイン",
  "nav.settings": "設定",
  "nav.stats": "統計",
  "nav.insight": "AI インサイト",

  # ---- 統計ウィジェット ----
  "core.widget.topDocs": "最もよくアクセスされたドキュメント",
  "core.widget.heatmap": "アクセスヒートマップ",
  "core.widget.stayTime": "ドキュメント滞在時間",
  "core.widget.wordCount": "文字数",
  "core.widget.recentDocs": "最近のアクセス",

  # ---- テーマ切り替え ----
  "core.theme.toLight": "ライトモードに切り替え",
  "core.theme.toDark": "ダークモードに切り替え",
  "core.theme.selectTheme": "テーマを選択",

  # ---- 学習ページ ----
  "core.learn.markedCompleted": "学習完了としてマーク済み",
  "core.learn.unmarkedCompleted": "マークを解除しました",
  "core.learn.courseDisabledWarning":
    "このドキュメントは「コース」プラグインに依存しています。問題とインタラクティブブロックは元のデータとして表示されます。「プラグイン」ページで有効にできます。",
  "core.learn.completed": "学習済み",
  "core.learn.markComplete": "学習完了としてマーク",
  "core.learn.readingMode": "ドキュメント閲覧",
  "core.learn.progressKnowledge": "知識ポイント {pos} / {total}",
  "core.learn.progressDoc": "ドキュメント {pos} / {total} 件",
  "core.learn.refToDoc": "この節はドキュメント「{name}」を参照しています",
  "core.learn.gotoRefDoc": "参照ドキュメントへ移動",
  "core.learn.emptySection": "この知識ポイントにはまだコンテンツがありません",
  "core.learn.prevKnowledge": "前の知識ポイント",
  "core.learn.unmarkComplete": "学習完了マークを解除",
  "core.learn.markCurrentComplete": "この知識ポイントを学習完了としてマーク",
  "core.learn.nextKnowledge": "次の知識ポイント",
  "core.learn.unsupportedBlock": "現在サポートされていないブロックタイプ：{type}",
  "core.learn.ref": "参照",
  "core.learn.choiceMultiple": "複数選択問題",
  "core.learn.choiceSingle": "単一選択問題",
  "core.learn.multiSelect": "複数選択可",
  "core.learn.singleSelect": "単一選択",
  "core.learn.submit": "送信",
  "core.learn.correct": "正解です",
  "core.learn.incorrect": "不正解です",
  "core.learn.explanation": "解説：{text}",
  "core.learn.gradeFailed": "採点に失敗しました",
  "core.learn.fillBlank": "穴埋め問題",
  "core.learn.aiGraded": "AI 採点",
  "core.learn.blankN": "空欄 {n}",
  "core.learn.accuracy": "正答率 {score}%",
  "core.learn.redo": "やり直す",
  "core.learn.interactiveNoFile": "インタラクティブブロックに file 設定がありません",
  "core.learn.interactiveFallback": "動的インタラクティブ",
  "core.learn.interactiveTitle": "インタラクティブデモ",
  "core.learn.blockDepPrefix": "このブロック（",
  "core.learn.blockDepMid": "）は「",
  "core.learn.blockDepPlugin": "」プラグイン（",
  "core.learn.blockDepSuffix": "）に依存しています。無効時は元のデータとして表示されます",
  "core.learn.interactiveNotRendered": "インタラクティブブロックがレンダリングされていません",
  "core.learn.quizNotRendered": "問題がレンダリングされていません",
  "core.learn.viewRaw": "元のデータを表示",
  "core.learn.shortAnswer": "記述問題",
  "core.learn.answerPlaceholder": "回答を入力してください...",
  "core.learn.keywords": "要点キーワード：{text}",
  "core.learn.submitGrade": "採点を送信",
  "core.learn.aiFeedback": "AI フィードバック：",
  "core.learn.hint": "ヒント：{text}",
  "core.plugin.unknown": "不明なプラグイン",
  "core.plugin.course": "コース",

  # ---- ドキュメントライブラリ ----
  "core.library.quiz": "テスト",
  "core.library.kindCourse": "コース",
  "core.library.kindNote": "ノート",
  "core.library.kindKb": "ナレッジベース",
  "core.library.kindCanvas": "キャンバス",
  "core.library.empty": "コンテンツがありません",
  "core.library.emptyLibrary": "このライブラリは空です。ホームページでコースパックをインポートするか、新しいドキュメントセットを作成してください。",
  "core.library.library": "ライブラリ",
  "core.library.deleteLibTitle": "ライブラリを削除",
  "core.library.deleteLibDesc": "このライブラリを削除しますか？配下のすべてのコンテンツが削除され、元に戻せません。",
  "core.library.deletedLib": "ライブラリを削除しました",
  "core.library.unmountTitle": "シンボリックリンクをアンマウント",
  "core.library.unmountNameFallback": "このシンボリックリンク",
  "core.library.unmountDesc": "「{name}」をリストから削除します。ディスク上のファイルは削除されません。",
  "core.library.unmount": "アンマウント",
  "core.library.unmounted": "アンマウント済み",
  "core.library.singleFile": "（単一ファイル）",
  "core.library.symlink": "シンボリックリンク",
  "core.library.pluginBadge": "プラグイン",
  "core.library.emptyLibraries": "ライブラリがありません。右上のボタンからコースパックをインポートするか、新しいライブラリを作成してください。",
  "core.library.noSymlinks": "シンボリックリンクがありません。右側からローカルフォルダーまたはファイルを追加してください",
  "core.library.collectionCount": "ドキュメントセット {count} 件",
  "core.library.searchPlaceholder": "ドキュメントセットを検索...",
  "core.library.gridView": "グリッド表示",
  "core.library.listView": "リスト表示",
  "core.library.unitChapter": "章",
  "core.library.unitCanvas": "キャンバス",
  "core.library.unitDoc": "ドキュメント",
  "core.library.noSearchResults": "一致するドキュメントセットがありません。",
  "core.library.emptyCollections": "このライブラリにはまだドキュメントセットがありません。コースパックをインポートするか、新規作成してください。",
  "core.library.selectPlaceholder": "ライブラリまたはシンボリックリンクを選択して内容を表示します。",
  "core.library.newLibTitle": "ライブラリを新規作成",
  "core.library.namePlaceholder": "例：専門科目",
  "core.library.descriptionOptional": "説明（任意）",
  "core.library.descPlaceholder": "このライブラリに入れる内容",
  "core.library.createdLib": "ライブラリを作成しました",
  "core.library.newCanvas": "キャンバスを新規作成",
  "core.library.newCanvasTitle": "キャンバスを新規作成",
  "core.library.newCanvasPlaceholder": "キャンバス名",
  "core.library.newCanvasDefault": "無題のキャンバス",
  "core.library.createdCanvas": "キャンバスを作成しました",
  "core.library.newDoc": "ドキュメントを新規作成",
  "core.library.newDocTitle": "ドキュメントを新規作成",
  "core.library.newDocPlaceholder": "ドキュメント名",
  "core.library.newDocDefault": "無題のドキュメント",
  "core.library.createdDoc": "ドキュメントを作成しました",
  "core.library.import": "インポート",
  "core.library.importFailed": "インポートに失敗しました",
  "core.library.importedCourse": "コース「{names}」をインポートしました",
  "core.library.importedNote": "ノートをインポートしました（{count} 節）",
  "core.library.importWarning":
    "インポートしたコンテンツの一部のブロックは「{names}」プラグインに依存しており、無効時は元のデータとして表示されます。",
  "core.library.importedCanvas": "キャンバス「{name}」をインポートしました",
  "core.library.importedContent": "コンテンツをインポートしました",
  "core.library.importTitle": "コンテンツをインポート",
  "core.library.importDesc":
    "MetaPilot ファイル（.mpf/.canvas、統一形式：doc=コース内容、canvas=キャンバス）、コースパック（zip）、Markdown ノートに対応しています。",
  "core.library.tabMpf": "MetaPilot ファイル",
  "core.library.tabCourse": "コースパック",
  "core.library.mpfLabel": "MetaPilot ファイル（.mpf / .canvas）",
  "core.library.mpfHint": "doc タイプはコース/ドキュメントとして解釈されます；.canvas ファイル（Obsidian Canvas）は自動的にキャンバスへ変換されます。",
  "core.library.courseGateHint": "コースパックをインポート（zip）",
  "core.library.courseFileLabel": "コースパックファイル（.zip、manifest.json を含む）",
  "core.library.noteGateHint": "Markdown ノートをインポート",
  "core.library.noteFileLabel": "Markdown / Obsidian ファイル（.md）",

  # ---- 編集ページ ----
  "core.edit.block.markdown": "表示（Markdown）",
  "core.edit.block.single_choice": "単一選択問題",
  "core.edit.block.multiple_choice": "複数選択問題",
  "core.edit.block.fill_blank": "穴埋め問題",
  "core.edit.block.short_answer": "記述問題",
  "core.edit.block.interactive": "動的インタラクティブブロック",
  "core.edit.block": "ブロック",
  "core.edit.collectionInfo": "コース情報",
  "core.edit.summary": "概要",
  "core.edit.newDocName": "新しい章",
  "core.edit.newSectionName": "新しい知識ポイント",
  "core.edit.deleteDocTitle": "章を削除",
  "core.edit.deleteDocDesc": "この章を削除しますか？配下のすべての節とコンテンツが削除され、元に戻せません。",
  "core.edit.deleteSectionTitle": "節を削除",
  "core.edit.deleteSectionDesc": "この節を削除しますか？",
  "core.edit.deleteBlockTitle": "ブロックを削除",
  "core.edit.deleteBlockDesc": "このブロックを削除しますか？",
  "core.edit.newFolderTitle": "フォルダーを新規作成",
  "core.edit.newFolderDesc": "新しいフォルダーの名前を入力してください。",
  "core.edit.newFolderPlaceholder": "例：章ノート",
  "core.edit.renameFolderTitle": "フォルダー名を変更",
  "core.edit.deleteFolderTitle": "フォルダーを削除",
  "core.edit.deleteFolderDesc": "このフォルダーを削除しますか？配下のすべてのサブフォルダーとドキュメントが一緒に削除され、元に戻せません。",
  "core.edit.createFailed": "作成に失敗しました",
  "core.edit.renameFailed": "名前の変更に失敗しました",
  "core.edit.deleteFailed": "削除に失敗しました",
  "core.edit.moveFailed": "移動に失敗しました",
  "core.edit.docSettings": "章の設定",
  "core.edit.docNameLabel": "章名",
  "core.edit.docTypeStudy": "学習の章",
  "core.edit.docTypeQuiz": "テストの章",
  "core.edit.moveDocLabel": "配置フォルダー（ドキュメントの移動）",
  "core.edit.rootFolder": "ルート",
  "core.edit.docTypeHint": "学習の章とテストの章は自由に組み合わせられ、学習と試験を分離できます。",
  "core.edit.sectionSettings": "知識ポイントの設定",
  "core.edit.sectionNameLabel": "知識ポイント名",
  "core.edit.refDocLabel": "他のドキュメントを参照（節の参照）",
  "core.edit.noRef": "参照なし",
  "core.edit.refDocHint": "参照に設定すると、学習ページに参照カードが表示され、対象ドキュメントへジャンプします。",
  "core.edit.addBlockLabel": "ブロックを追加",
  "core.edit.backToSection": "節に戻る",
  "core.edit.blockSaved": "ブロックを保存しました",
  "core.edit.addSectionTitle": "節を追加",
  "core.edit.noBlocks": "ブロックがありません",
  "core.edit.noSections": "節がありません",
  "core.edit.subFolder": "サブフォルダー",
  "core.edit.emptyFolder": "空のフォルダー",
  "core.edit.mode": "編集モード",
  "core.edit.dirty": "変更あり",
  "core.edit.saved": "保存済み",
  "core.edit.newDoc": "章",
  "core.edit.newFolder": "フォルダー",
  "core.edit.done": "完了",
  "core.edit.markdownContent": "Markdown コンテンツ",
  "core.edit.markdownPlaceholder": "# 見出し\n\n本文。Markdown と GFM のテーブル/タスクリストに対応",
  "core.edit.question": "問題",
  "core.edit.options": "選択肢（1行に1つ）",
  "core.edit.optionsPlaceholder": "選択肢 A\n選択肢 B\n選択肢 C",
  "core.edit.correctIndex": "正解の選択肢インデックス（0 から始まる）",
  "core.edit.correctIndexes": "正解の選択肢インデックス（カンマ区切り）",
  "core.edit.blanksAnswers": "各空欄の解答例（1行に1つの空欄）",
  "core.edit.blanksPlaceholder": "解答1\n解答2",
  "core.edit.reference": "解答例",
  "core.edit.keywordsLabel": "要点キーワード（カンマ区切り、AI の参考用）",
  "core.edit.keywordsPlaceholder": "キーワード1,キーワード2",
  "core.edit.aiGraded": "AI 採点を使用（記述問題）",
  "core.edit.title": "タイトル",
  "core.edit.assetFile": "アセットファイル（コースパックの interactives/ からの相対パス）",
  "core.edit.iframeHeight": "iframe の高さ（px）",
  "core.edit.explanationLabel": "解説 / ヒント（任意）",

  # ---- キャンバス ----
  "core.canvas.saved": "キャンバスを保存しました",
  "core.canvas.saveFailed": "保存に失敗しました",
  "core.canvas.doubleClickEdit": "ダブルクリックでテキストを編集",
  "core.canvas.notCanvas": "このドキュメントセットはキャンバスではありません。",
  "core.canvas.backToLibrary": "ライブラリに戻る",
  "core.canvas.badge": "キャンバス",
  "core.canvas.dirty": "未保存の変更があります",
  "core.canvas.unsavedTitle": "未保存の変更があります",
  "core.canvas.unsavedDesc": "キャンバスに未保存の変更があります。閉じる前に保存しますか？",
  "core.canvas.discardAndLeave": "保存せずに離れる",
  "core.canvas.saveAndLeave": "保存して離れる",
  "core.canvas.newTextNode": "テキストノードを新規作成",
  "core.canvas.help":
    "ノードをドラッグして移動、空白部分のドラッグで範囲選択、Shift で複数選択、Delete で削除、Ctrl+C/V でコピー＆ペースト、Ctrl+Z で元に戻す；テキストはダブルクリックで編集；ノードの端の接続点から別のノードへドラッグして線を作成；ホイールでパン、Ctrl+ホイールでズーム、Space を押しながらドラッグでパン。",
  "core.canvas.undo": "元に戻す (Ctrl+Z)",
  "core.canvas.redo": "やり直す (Ctrl+Shift+Z)",
  "core.canvas.zoomOut": "縮小",
  "core.canvas.zoomIn": "拡大",
  "core.canvas.fitView": "キャンバスにフィット",
  "core.canvas.empty": "（空）",
  "core.canvas.group": "グループ化",
  "core.canvas.deleteNode": "ノードを削除",
  "core.canvas.dragLink": "ドラッグで接続",
  "core.canvas.emptyBoard": "空のキャンバスです。右上の「テキストノードを新規作成」をクリックして開始",
  "core.canvas.stats": "ノード {nodes} 個 · リンク {edges} 本",
  "core.canvas.exportMpf": ".mpf をエクスポート",
  "core.canvas.exportCanvas": ".canvas をエクスポート",
  "core.canvas.export": "エクスポート",
  "core.canvas.center": "中央揃え",
  "core.canvas.alignLeft": "左揃え",
  "core.canvas.alignCenter": "中央揃え",
  "core.canvas.alignRight": "右揃え",
  "core.canvas.edgePath": "線のスタイル",
  "core.canvas.pathSmooth": "滑らかな曲線",
  "core.canvas.pathStraight": "直線",
  "core.canvas.pathSquare": "直角の折れ線",
  "core.canvas.resize": "サイズ変更",
  "core.canvas.groupSelection": "グループ化",
  "core.canvas.dragAddCard": "ドラッグしてカードを追加",
  "core.canvas.dragAddNote": "ドラッグしてノートを追加",
  "core.canvas.dragAddNoteVault": "ドラッグしてライブラリからノートを追加",
  "core.canvas.dragAddMediaVault": "ドラッグしてライブラリからメディアを追加",
  "core.canvas.paste": "貼り付け",
  "core.canvas.toggleNav": "ナビゲーションを開く/閉じる",
  "core.canvas.noCanvases": "キャンバスがありません",
  "core.canvas.edgeStart": "始点",
  "core.canvas.edgeEnd": "終点",
  "core.canvas.arrow": "矢印",
  "core.canvas.toggleStartArrow": "始点の矢印を切り替え",
  "core.canvas.toggleEndArrow": "終点の矢印を切り替え",
  "core.canvas.edgeLabel": "ラベル",
  "core.canvas.colorTitle": "色 {color}",
  "core.canvas.clearColor": "色をクリア",
  "core.canvas.deleteEdge": "線を削除",
  "core.canvas.addNode": "ノードを新規作成",
  "core.canvas.addNodeText": "テキスト",
  "core.canvas.addNodeFile": "ファイル",
  "core.canvas.addNodeLink": "リンク",
  "core.canvas.addNodeGroup": "グループ",
  "core.canvas.addFileTitle": "ファイルパス",
  "core.canvas.addFileDesc": "ライブラリ内の相対パス（例：notes/サンプル.md、images/画像.png）（Obsidian 互換）",
  "core.canvas.addLinkTitle": "リンク URL",
  "core.canvas.addGroupTitle": "グループラベル",
  "core.canvas.groupName": "グループ名",

  # ---- 統計ページ ----
  "core.stats.intro":
    "公式コアは基本的な統計ウィジェットを提供し、コースなどのプラグインがさらに多くのウィジェットを追加できます；カードをドラッグして位置を調整し、右上でサイズを変更します。設定ページで「ウィジェットの出典を表示」を切り替えられます。",
  "core.stats.resize": "サイズ変更（現在 {size}）",
  "core.stats.hide": "ウィジェットを非表示",
  "core.stats.manage": "ウィジェットを管理",
  "core.stats.hiddenCount": "{count} 件を非表示中",
  "core.stats.manageDesc":
    "「表示中」でウィジェットを非表示にするか、「非表示」パネルでいつでも再表示できます；統計ページのカードをドラッグして位置と順序を調整できます。",
  "core.stats.none": "利用可能な統計ウィジェットがありません",
  "core.stats.visibleCount": "表示中（{count}）",
  "core.stats.hiddenTab": "非表示（{count}）",
  "core.stats.noHidden": "非表示のウィジェットはありません。すべてのウィジェットが表示中です",
  "core.stats.resetLayout": "デフォルトレイアウトに戻す",
  "core.stats.showAll": "すべて表示",
  "core.stats.restore": "再表示",
  "core.stats.noVisits": "アクセス記録がありません",
  "core.stats.noStayTime": "滞在記録がありません",
  "core.stats.visits": "{count} 回",
  "core.stats.wordUnit": "文字",
  "core.stats.unknownWidget": "不明なウィジェット",
  "core.stats.heatmap3m": "直近 3 か月のアクセスヒートマップ",
  "core.stats.heatmapTooltip": "{month}月{day}日 · {count} 回のアクセス",
  "core.stats.heatmapLess": "少ない",
  "core.stats.heatmapMore": "多い",
  "core.stats.hourly": "時間ごとのアクセス分布",
  "core.stats.hourTooltip": "{hour}時 · {count} 回",
  "core.stats.hourLabel": "{hour}時",
  "core.stats.monthLabel": "{month}月",
  "core.stats.weekdays": "月,火,水,木,金,土,日",
  "core.stats.courseDisabled": "「コース」プラグインに依存していますが、無効です",
  "core.stats.totalStudy": "累計学習時間",
  "core.stats.chartMinutes": "分",
  "core.stats.noStudyRecords": "学習記録がありません",
  "core.stats.providedBy": "プラグイン「{name}」によって提供されています",
  "core.stats.providedByTooltip": "{name} プラグインが提供",

  # ---- 共通ダイアログ / toast ----
  "core.dialog.selectPlaceholder": "選択してください…",
  "core.toast.copied": "クリップボードにコピーしました",
  "core.widget.aiUsage": "AI 使用量",
  "core.stats.rangeToday": "今日",
  "core.stats.rangeWeek": "今週",
  "core.stats.rangeMonth": "今月",
  "core.stats.rangeAll": "すべて",
  "core.stats.aiCalls": "呼び出し回数",
  "core.stats.aiTokens": "Token 使用量",
  "core.stats.aiCost": "コスト",
  "core.stats.aiTokensDetail": "入力 {in} / キャッシュ {cached} / 出力 {out}",
  "core.stats.aiCallsShort": "呼び出し {n} 回",
  "core.stats.aiTokensShort": "{n} tokens",
  "core.stats.aiUsageEmpty": "AI 使用量の記録はまだありません（各プラグインが統一ゲートウェイを通じて行った呼び出しがここに記録されます）。",

  # ---- course（コースプラグイン） ----
  "course.exportFailed": "エクスポートに失敗しました",
  "course.pluginDisabledWarning": "このドキュメントは「コース」プラグインに依存しています。学習進捗と問題のインタラクションは利用できません。「プラグイン」ページで有効にできます。",
  "course.backToLibrary": "ライブラリに戻る",
  "course.noDescription": "概要がありません",
  "course.authorLabel": "作成者：{author}",
  "course.export": "エクスポート",
  "course.continueLearning": "学習を続ける",
  "course.learningProgress": "学習進捗",
  "course.progressCount": "知識ポイント {completed} / {total}",
  "course.lastLearned": "前回の学習：{name}",
  "course.progressRequiresPlugin": "学習進捗は「コース」プラグインに依存しています。有効にすると学習完了をマークでき、前回の学習位置を追跡できます。",
  "course.quiz": "テスト",
  "course.noSectionsInChapter": "この章には節がありません",
  "course.noChapters": "このコースにはまだ章がありません。右上の「編集」をクリックして作成を始めてください。",
  # ライブラリページのコレクション作成/変換操作（コース=パッチ適用済みドキュメント）
  "course.library.newCourse": "コースを新規作成",
  "course.library.newCourseTitle": "コースを新規作成",
  "course.library.newCoursePlaceholder": "コース名",
  "course.library.newCourseDefault": "無題のコース",
  "course.library.createdCourse": "コースを作成しました",
  "course.library.createCourseFailed": "コースの作成に失敗しました",
  "course.library.toCourse": "コースに変換",
  "course.library.toCourseTitle": "コースに変換",
  "course.library.toCourseDesc": "「{name}」をコースに変換しますか？コースはパッチ適用済みのドキュメントで、学習進捗、採点、インタラクティブブロックなどのコース機能を有効にできます；「コース」プラグインが無効の間はコース機能は利用できません。",
  "course.library.toCourseConfirm": "コースに変換",
  "course.library.convertedCourse": "「{name}」をコースに変換しました",
  "course.library.convertCourseFailed": "コースへの変換に失敗しました",

  # ---- insight（AI インサイト） ----
  "insight.pageTitle": "AI インサイト",
  "insight.intro": "ドキュメントやライブラリを選択し、インデックスを作成して AI に考えさせます：資料間のつながりを調べ、4 つのモードで回答、提案、またはキャンバス/コースを生成します。",
  "insight.introWithSymlink": "ドキュメント、ライブラリ、またはローカルディレクトリを選択し、インデックスを作成して AI に考えさせます：資料間のつながりを調べ、4 つのモードで回答、提案、またはキャンバス/コースを生成します。",
  "insight.stepIndex": "ステップ 1 · インデックス作成",
  "insight.stepAsk": "ステップ 2 · AI に質問",
  "insight.stepIndexQuoted": "「ステップ 1 · インデックス作成」",
  "insight.mustIndexBefore": "先にインデックスを作成してから質問してください；作成せずに質問すると自動で作成されます（進捗が表示されます）。",
  "insight.noIndexedBefore": "インデックス済みのデータソースがまだありません。まず",
  "insight.noIndexedAfter": "で選択したコンテンツのベクトルインデックスを作成してから質問してください。",
  "insight.noIndexedAfterWithSymlink": "で選択したドキュメント / ローカルディレクトリのベクトルインデックスを作成してから質問してください。",
  "insight.vectorModelTitle": "ベクトルモデルとローカルサービス",
  "insight.embeddingRunning": "実行中",
  "insight.embeddingNotReady": "未準備",
  "insight.selectModelPlaceholder": "embedding モデルを選択",
  "insight.stopService": "サービスを停止",
  "insight.startService": "サービスを開始（初回は選択したモデルを自動ダウンロード）",
  "insight.modelDownloadHint": "モデルのダウンロードは複数のソースから自動的に試行され、初回はモデルが準備できるまで待つ必要があります。ページは自動的にステータスを更新します。具体的なダウンロード元とモデル一覧はバックエンド設定に従います。",
  "insight.selectSourcesTitle": "データソースを選択（複数選択可）",
  "insight.indexIntro": "ライブラリ、単一のドキュメントセット、単一のドキュメント単位で選択できます；インデックスはデータソースごとに独立して保存されます。",
  "insight.indexIntroWithSymlink": "ライブラリ、ドキュメントセット、ドキュメント単位で選択でき、ローカルディレクトリ全体やディレクトリ内の任意のパスも選択できます；インデックスはデータソースごとに独立して保存されます。",
  "insight.indexing": "インデックス作成中...",
  "insight.indexingProgress": "セグメント {done}/{total} をインデックス済み",
  "insight.indexQueued": "インデックスの作成を開始しました。下で進捗を確認できます",
  "insight.buildVectorIndex": "ベクトルインデックスを作成",
  "insight.noSources": "利用可能なデータソースがありません：「マイライブラリ」でライブラリを作成してください。",
  "insight.noSourcesWithSymlink": "利用可能なデータソースがありません：「マイライブラリ」でライブラリを作成するか、ローカルディレクトリをマウントしてください。",
  "insight.askSourcesTitle": "思考対象のデータソースを選択（複数選択可、結合検索）",
  "insight.askTitle": "AI 思考（回答には出典が表示されます）",
  "insight.askPlaceholder": "AI に質問します。例：「これらの資料の間にはどのようなつながりがありますか？」",
  "insight.refSources": "参考出典",
  "insight.sourceRef": "[出典{n}]",
  "insight.asking": "検索して回答を生成しています...",
  "insight.inputPlaceholder": "質問や思考の方向性を入力...",
  "insight.askButton": "質問する",
  "insight.groupLibrary": "ライブラリのドキュメント（ライブラリ / ドキュメントセット / ドキュメント）",
  "insight.groupSymlink": "ローカルディレクトリのマウント",
  "insight.indexedCount": "セグメント {count} をインデックス済み",
  "insight.notIndexed": "未インデックス",
  "insight.pluginHint": "AI インサイト：資料のつながりを分析してコンテンツを生成",
  "insight.loadResourcesFailed": "データソースの読み込みに失敗しました",
  "insight.startServiceToast": "サービスを起動中です（初回実行時は選択したモデルを自動ダウンロードします）",
  "insight.startFailed": "起動に失敗しました",
  "insight.serviceStopped": "サービスを停止しました",
  "insight.indexDone": "インデックス完了：データソース {ok}/{total}",
  "insight.indexFailed": "インデックス作成に失敗しました",
  "insight.askFailed": "質問に失敗しました",
  # ---- 思考モード ----
  "insight.modeTitle": "思考モード",
  "insight.modeIntro": "思考方法を選択すると、AI はその方法で選択した資料を調べてコンテンツを生成します。",
  "insight.modeAssist": "補助思考",
  "insight.modeAssistDesc": "資料間のつながりを見つけ、回答と提案を示します",
  "insight.modeWander": "思考の散策",
  "insight.modeWanderDesc": "資料とあなたの思考の方向性を組み合わせて、発散的に連想します",
  "insight.modeReflect": "振り返りと総括",
  "insight.modeReflectDesc": "気づいていないつながりや盲点を整理します",
  "insight.modePlan": "インサイトプランニング",
  "insight.modePlanDesc": "複数回の推論でキャンバスやコースを生成し、あなたを教えます",
  # ---- インサイトプランニング ----
  "insight.planOutputTitle": "生成タイプ",
  "insight.planOutputCanvas": "知識キャンバス（キャンバス）",
  "insight.planOutputCourse": "マイクロコース（ドキュメント）",
  "insight.planLibraryTitle": "ライブラリに保存",
  "insight.planLibraryAuto": "デフォルトライブラリ（最初のもの）",
  "insight.planGoalPlaceholder": "計画目標を入力します。例：これらの資料の核となる概念とつながりを整理し、最短時間で理解できるように教えてください",
  "insight.planButton": "インサイトプランニングを開始",
  "insight.planning": "AI が複数回にわたり資料のつながりを分析して生成しています。1〜2 分かかる場合があります...",
  "insight.planDone": "「{name}」を生成しました",
  "insight.planOpenCanvas": "キャンバスを開く",
  "insight.planOpenCourse": "コースを開く",
  "insight.planSummary": "プラン概要",
  "insight.planFailed": "インサイトプランニングに失敗しました",
  # ---- インサイトプランニング実行ステップ（SSE リアルタイム） ----
  "insight.planRoadmap": "AI 実行ステップ",
  "insight.planThinking": "AI の思考プロセス",
  "insight.planStep.retrieve": "資料を検索",
  "insight.planStep.plan": "テーマとつながりの分析",
  "insight.planStep.review": "批判的振り返り",
  "insight.planStep.generateCanvas": "知識キャンバスを生成",
  "insight.planStep.generateCourse": "マイクロコースを生成",
  "insight.planStep.save": "ライブラリに保存",
  "insight.planStepRunning": "実行中…",
  "insight.planConnecting": "AI に接続して実行ステップを計画しています…",
  # ---- 自動インデックス作成 ----
  "insight.autoIndexing": "選択したデータソースはまだインデックスが作成されていないため、自動で作成しています（{done}/{total}）...",
  "insight.autoIndexDone": "インデックス完了。生成を続行します...",
  "insight.autoIndexFailed": "自動インデックス作成に失敗しました。まずステップ 1 で手動でインデックスを作成してください",
  "insight.symlinkBrowse": "ディレクトリを参照",
  "insight.treeEmpty": "（空）",
  # ---- データ検索ライブラリ（左パネル） ----
  "insight.kbTitle": "データ検索ライブラリ",
  "insight.goAsk": "質問へ",
  "insight.selectedCount": "{count} 件を選択中",
  "insight.kbIndexed": "{count} 件のソースをインデックス済み",
  "insight.collapsePanel": "データ検索ライブラリのパネルを閉じる",
  "insight.expandPanel": "データ検索ライブラリのパネルを開く",
  "insight.kbHint": "ライブラリ / ドキュメントセット / ドキュメントを検索範囲として選択：インデックスを作成したり、直接質問したりできます；未インデックスのソースは質問時に自動でインデックスが作成されます。",
  "insight.kbHintWithSymlink": "ライブラリ / ドキュメントセット / ドキュメントまたはローカルディレクトリを検索範囲として選択：インデックスを作成したり、直接質問したりできます；未インデックスのソースは質問時に自動でインデックスが作成されます。",
  "insight.buildIndexTitle": "ベクトルインデックスを作成",
  "insight.buildIndexHint": "{count} 件のデータソースを選択中（左の「データ検索ライブラリ」で調整できます）。未インデックスのものもまとめて作成します。",

  # ---- symlink（ソフトリンクプラグイン） ----
  "symlink.fileBrowser": "ファイルブラウザ",
  "symlink.symlinkPlugin": "シンボリックリンクプラグイン",
  "symlink.pluginHint": "ローカルディレクトリを参照・読み書き",
  "symlink.linkLocalDoc": "ローカルドキュメントをリンク（シンボリックリンク）",
  "symlink.addMountDesc1": "リンクするのはローカルディスク上の",
  "symlink.addMountDesc2": "または",
  "symlink.addMountDesc3": "です。元のファイルをコピー・移動することはありません；リンク後はファイルブラウザでドキュメントのように参照、閲覧、編集できます。",
  "symlink.mounts": "マウント",
  "symlink.mount": "マウント",
  "symlink.thatMount": "このマウント",
  "symlink.unmount": "アンマウント",
  "symlink.unmountSymlink": "シンボリックリンクをアンマウント",
  "symlink.unmountConfirmDesc": "「{name}」をリストから削除します。ディスク上のファイルは削除されません。",
  "symlink.noMounts": "マウントがありません。右上からローカルフォルダーまたはファイルを追加してください",
  "symlink.currentMountRoot": "現在のマウントルート：{root}",
  "symlink.pleaseMount": "最初にローカルフォルダーまたはファイルをマウントしてください",
  "symlink.mountSuccess": "マウントに成功しました",
  "symlink.mountFailed": "マウントに失敗しました",
  "symlink.displayName": "表示名",
  "symlink.namePlaceholder": "例：私のノート",
  "symlink.localPathLabel": "ローカルパス（フォルダーまたはファイル）",
  "symlink.pathPlaceholder": "「参照」をクリックして選択するか、手動で入力してください（Windows/Linux 対応）",
  "symlink.collapse": "閉じる",
  "symlink.browse": "参照",
  "symlink.afterMountHint": "マウント後はファイルブラウザでディレクトリ内のテキストファイルを参照、閲覧、編集できます（アクセス権限はマウントルート内に制限されます）。",
  "symlink.directory": "ディレクトリ",
  "symlink.folder": "フォルダー",
  "symlink.file": "ファイル",
  "symlink.singleFile": "単一ファイル",
  "symlink.singleFileNote": "（単一ファイル）",
  "symlink.singleFileMount": "（単一ファイルマウント）",
  "symlink.rootDir": "（ルートディレクトリ）",
  "symlink.noSubfolders": "サブフォルダーなし",
  "symlink.emptyDir": "空のディレクトリ",
  "symlink.expandDir": "ディレクトリを展開",
  "symlink.collapseDir": "ディレクトリを閉じる",
  "symlink.newFolder": "フォルダーを新規作成",
  "symlink.newFolderDesc": "新しいフォルダーの名前を入力してください。",
  "symlink.newFolderPlaceholder": "例：章ノート",
  "symlink.searchPlaceholder": "検索…",
  "symlink.gridView": "グリッド表示",
  "symlink.listView": "リスト表示",
  "symlink.backToList": "リストに戻る",
  "symlink.reveal": "場所を表示",
  "symlink.revealInFileManager": "ファイルマネージャーで表示",
  "symlink.openWithDefault": "既定のアプリで開く",
  "symlink.editing": "編集中：{path}",
  "symlink.saved": "保存しました",
  "symlink.saveFailed": "保存に失敗しました",
  "symlink.createFailed": "作成に失敗しました",
  "symlink.deleteFile": "ファイルを削除",
  "symlink.deleteConfirmDesc": "「{target}」を削除しますか？",
  "symlink.deleteDirWarning": "フォルダーは再帰的に削除され、元に戻せません。",
  "symlink.deleteFailed": "削除に失敗しました",
  "symlink.openedWithDefault": "システムの既定アプリで開きました",
  "symlink.openFailed": "開くのに失敗しました",
  "symlink.readFailed": "読み込みに失敗しました",
  "symlink.noInlinePreview": "このファイルタイプはインラインプレビューに対応していません",
  "symlink.noInlinePreviewHint": "このファイルタイプはインラインプレビューに対応していません。右クリックで「既定のアプリで開く」を選択できます",
  "symlink.noMatch": "一致する項目がありません。",
  "symlink.goUp": "上の階層",
  "symlink.myComputer": "マイコンピュータ",
  "symlink.reading": "読み込み中…",
  "symlink.emptyFolder": "空のフォルダー",
  "symlink.selectedFolder": "フォルダー：{path}",
  "symlink.selectedFile": "ファイル：{path}",
  "symlink.selectHint": "クリックでフォルダーまたはファイルを選択、フォルダーをダブルクリックで入ります",
  "symlink.selectThisFolder": "このフォルダーを選択",
  "symlink.selectThisFile": "このファイルを選択",

  # ---- sys（システム設定 / プラグイン管理 / テーマ） ----
  "sys.title": "設定",
  "sys.subtitle": "プラグイン関連の通知の動作を制御します。MetaPilot はドキュメントライブラリです：ドキュメントは常に開いて表示でき、レンダリングされない部分は元のデータとして表示されます；通知はあくまで注意喚起であり、操作を中断しません。",
  "sys.language": "言語",
  "sys.languageDesc": "インターフェースの表示言語です。切り替えるとすぐに反映され、ローカル（localStorage）に保存されます。",
  "sys.appearance": "外観",
  "sys.appearanceDesc": "ダーク / ライトモードはいつでも切り替えられます；特色テーマは「テーマ」プラグインが提供します（プラグイン管理ページで有効にしてから選択できます）。",
  "sys.pluginWarnings": "プラグイン警告の通知",
  "sys.pluginWarningsDesc": "無効化されたプラグインに依存するドキュメント（コース、ナレッジベースなど）を開くと、上部に警告バブルが表示され、「このコンテンツは xx プラグインに依存しており、一部のブロックがレンダリングされない場合があります」と通知します。",
  "sys.pluginErrors": "プラグインエラーの通知",
  "sys.pluginErrorsDesc": "プラグインが有効でないために操作が失敗した場合（例：AI 採点、ナレッジベースの Q&A）、上部にエラーバブルが表示されます；オフにすると、この種のエラーは静かに無視されます。",
  "sys.componentSource": "ブロックの出典を表示",
  "sys.componentSourceDesc": "有効にすると、ライブラリや統計などのページで、プラグインが提供するブロック/コンテンツにそのプラグインのアイコンが表示されます（ホバーでプラグイン名を確認できます）；公式コア（MetaPilot 本体）には表示されません。オフにすると出典マークは表示されません。",
  "sys.localOnly": "この設定はブラウザのローカル（localStorage）にのみ保存され、他のデバイスには影響しません。",

  # プラグイン管理ページ
  "sys.plugins.title": "プラグイン管理",
  "sys.plugins.headerPrefix": "プラグインはユーザー定義、公式プラグイン、公式コアの 3 種類に分かれます。プラグインはバックエンドの",
  "sys.plugins.headerSuffix": "ディレクトリにある独立した機能パッケージです。「プラグインストア」で閲覧・インストールするか、自作プラグインをアップロードできます。",
  "sys.plugins.tabLocal": "ローカルプラグイン",
  "sys.plugins.tabStore": "プラグインストア",
  "sys.plugins.filterByTag": "タグで絞り込み：",
  "sys.plugins.sourceUser": "ユーザー定義プラグイン",
  "sys.plugins.sourceUserDesc": "自分で開発したり、プラグインストアからインストールしたり、zip をアップロードしてインストールできます；無効化または削除できます。",
  "sys.plugins.sourceOfficial": "公式プラグイン",
  "sys.plugins.sourceOfficialDesc": "MetaPilot 公式が開発した実用的なプラグインで、有効化・無効化はできますが、削除はできません。",
  "sys.plugins.sourceCore": "公式コア",
  "sys.plugins.sourceCoreDesc": "MetaPilot 本体：ドキュメントライブラリの閲覧と Markdown の読み取りです。無効化・削除はできません。",
  "sys.plugins.enabledToast": "プラグインを有効にしました",
  "sys.plugins.disabledToast": "プラグインを無効にしました",
  "sys.plugins.opFailed": "操作に失敗しました",
  "sys.plugins.deleteTitle": "プラグインを削除",
  "sys.plugins.deleteDesc": "プラグイン「{name}」を削除しますか？backend/plugins/{id} ディレクトリが物理的に削除され、元に戻せません。",
  "sys.plugins.deletedToast": "プラグイン「{name}」を削除しました",
  "sys.plugins.deleteFailed": "削除に失敗しました",
  "sys.plugins.idLabel": "id:",
  "sys.plugins.dependsOn": "依存プラグイン：",
  "sys.plugins.missingDeps": "不足している依存（先に有効にする必要があります）：",
  "sys.plugins.featureCourseImport": "コースパックのインポート / エクスポート",
  "sys.plugins.featureCourseFlow": "章の知識ポイント学習（ブロックフロー）",
  "sys.plugins.featureCourseProgress": "学習進捗と時間の統計",
  "sys.plugins.featureCourseGrading": "記述問題の AI 採点",
  "sys.plugins.featureCourseInteractive": "動的インタラクティブブロックのレンダリング",
  "sys.plugins.featureInsightIndex": "多粒度のデータソースベクトルインデックス（ライブラリ/ドキュメントセット/ドキュメント/ローカルディレクトリ）",
  "sys.plugins.featureInsightModes": "4 つの思考モード（補助思考/思考の散策/振り返りと総括/インサイトプランニング）",
  "sys.plugins.featureInsightPlan": "複数回の推論でキャンバスとマイクロコースを生成（.mpf）",
  "sys.plugins.needEnablePrefix": "「",
  "sys.plugins.needEnableSuffix": "」プラグインを有効にすると使用できます",
  "sys.plugins.thisFeature": "この機能",
  "sys.plugins.goEnable": "プラグイン管理ページで有効にする",
  "sys.plugins.uploadTitle": "プラグインをアップロード（ローカルインストール）",
  "sys.plugins.uploadDescPrefix": "規約に沿ってパッケージ化されたプラグイン zip を選択してください（ルートの",
  "sys.plugins.uploadDescSuffix": "ファイルを含む。プラグイン開発規約 §3 を参照）；インストール後すぐに下のリストに表示され、無効化または削除できます。",
  "sys.plugins.uploadInstall": "ローカルにインストール",
  "sys.plugins.uploadSuccess": "プラグインをインストールしました",
  "sys.plugins.uploadFailed": "インストールに失敗しました",

  # プラグインストア
  "sys.store.storeUnavailable": "プラグインストアにアクセスできません",
  "sys.store.installedToast": "プラグイン「{name}」をインストールしました",
  "sys.store.installFailed": "インストールに失敗しました",
  "sys.store.localInstalledToast": "プラグインをローカルにインストールしました",
  "sys.store.publishedToast": "プラグインストアに公開しました",
  "sys.store.uploadFailed": "アップロードに失敗しました",
  "sys.store.headerPrefix": "プラグインストアでプラグインを閲覧、絞り込み、インストールできます（ストアの URL はバックエンドの",
  "sys.store.headerSuffix": "設定で指定されます）。",
  "sys.store.checkUpdates": "更新を確認",
  "sys.store.emptyFiltered": "ストアに一致するプラグインがありません。",
  "sys.store.installed": "インストール済み",
  "sys.store.install": "インストール",
  "sys.store.uploadTitle": "プラグインをアップロード",
  "sys.store.uploadDescPrefix": "規約に沿ってパッケージ化されたプラグイン zip を選択してください（ルートの",
  "sys.store.uploadDescSuffix": "ファイルを含む。プラグイン開発規約 §3 を参照）：ローカルにインストールするか、プラグインストアに公開できます。",
  "sys.store.uploadLocal": "ローカルにインストール",
  "sys.store.uploadPublish": "ストアに公開",

  # テーマ
  "sys.theme.mode": "ダーク / ライトモード",
  "sys.theme.light": "ライト",
  "sys.theme.dark": "ダーク",
  "sys.theme.featured": "特色テーマ",
  "sys.theme.pluginDisabled": "テーマは「テーマ」プラグインが提供していますが、現在は無効です。",
  "sys.theme.defaultName": "デフォルト",
  "sys.theme.defaultDesc": "システムの配色に従う",
  "sys.plugins.changelogBtn": "更新履歴",
  "sys.plugins.changelogTitle": "{name} · 更新履歴",
  "sys.plugins.changelogDesc": "現在インストールされているバージョンは v{version} です；タイムラインはバージョンの新しい順に更新履歴を表示します。",
  "sys.plugins.changelogEmpty": "このプラグインにはまだ更新履歴がありません。",
  "sys.plugins.currentVersion": "現在のバージョン",
  # AI 統一ゲートウェイ（コア 1.1.1）
  "sys.ai.title": "AI サービス（統一ゲートウェイ）",
  "sys.ai.desc": "すべてのプラグインの AI 呼び出しは MetaPilot を経由します。API キーとアドレスはバックエンドの .env にのみ保存され、プラグインとフロントエンドは平文を取得できません。",
  "sys.ai.loadFailed": "AI 設定の読み込みに失敗しました",
  "sys.ai.provider": "API プロバイダー",
  "sys.ai.providerOpenai": "OpenAI 互換（MiniMax / DeepSeek などを含む）",
  "sys.ai.providerAnthropic": "Anthropic",
  "sys.ai.providerLocal": "ローカルモデル（内蔵）",
  "sys.ai.providerNone": "クラウド AI をオフ",
  "sys.ai.chatModel": "チャットモデル",
  "sys.ai.baseUrl": "API ベース URL",
  "sys.ai.apiKey": "API キー",
  "sys.ai.apiKeyPlaceholder": "設定済み（空欄の場合は現在の値を保持）",
  "sys.ai.embeddingTitle": "ベクトル（embedding）",
  "sys.ai.embeddingProvider": "ベクトルサービス",
  "sys.ai.embeddingLocal": "ローカル内蔵（要ダウンロード）",
  "sys.ai.embeddingOpenai": "クラウド（上記の API アドレスを使用）",
  "sys.ai.embeddingNone": "ベクトルをオフ",
  "sys.ai.embeddingModel": "ベクトルモデル",
  "sys.ai.embeddingUrl": "ローカルベクトルアドレス",
  "sys.ai.prices": "モデル価格（100 万 token あたり）",
  "sys.ai.pricesHint": "統計ページのコスト見積もりに使用します；キャッシュヒット / 入力 / 出力の単価。通貨は $ または ¥",
  "sys.ai.priceModel": "モデル",
  "sys.ai.priceInput": "入力",
  "sys.ai.priceCached": "キャッシュヒット",
  "sys.ai.priceOutput": "出力",
  "sys.ai.addPrice": "モデル価格を追加",
  "sys.ai.currency": "デフォルト通貨",
  "sys.ai.save": "設定を保存",
  "sys.ai.saved": "AI 設定を保存しました（.env に書き込み）",
  "sys.ai.saveFailed": "保存に失敗しました",
  "sys.ai.test": "接続テスト",
  "sys.ai.testing": "テスト中...",
  "sys.ai.testOk": "接続に成功しました：{model}（入力 {in} / 出力 {out} tokens）",
  "sys.ai.testFailed": "接続に失敗しました",
  "sys.ai.localTitle": "内蔵ローカルモデル",
  "sys.ai.localDesc": "必要なときにワンクリックでダウンロード（複数のミラーを自動で試行）。ダウンロード後すぐに起動して使用できます",
  "sys.ai.downloaded": "ダウンロード済み",
  "sys.ai.notDownloaded": "未ダウンロード",
  "sys.ai.downloading": "ダウンロード中...",
  "sys.ai.download": "ダウンロード",
  "sys.ai.start": "起動",
  "sys.ai.startFailed": "起動に失敗しました",
  "sys.ai.stop": "停止",
  "sys.ai.running": "実行中",
  "sys.ai.notRunning": "未実行",
  "sys.ai.modelKindEmbedding": "ベクトル",
  "sys.ai.modelKindLlm": "対話",
  "sys.ai.modelKindRerank": "リランク",
  "sys.ai.localOnlyHint": "上記の設定はローカルの .env にのみ保存され、いかなるサービスにもアップロードされません。",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "シンボリックリンクを追加",
    "core.library.defaultLib": "デフォルト",
    "core.library.defaultSet": "デフォルトのライブラリに設定しました",
    "core.library.menuMore": "その他の操作",
    "core.library.pin": "ピン留め",
    "core.library.pinned": "ピン留め済み",
    "core.library.pinnedLib": "上部にピン留めしました",
    "core.library.renameLib": "名前を変更",
    "core.library.renameLibTitle": "ライブラリ名を変更",
    "core.library.renamedLib": "ライブラリ名を変更しました",
    "core.library.setDefault": "デフォルトに設定",
    "core.library.unpin": "ピン留めを外す",
    "core.library.unpinnedLib": "ピン留めを外しました",
}
