# -*- coding: utf-8 -*-
"""한국어 UI 사전 (MetaPilot 프런트엔드).

zh-CN(중국어) 소스 사전의 모든 key를 한국어로 번역한 파일입니다.
key는 client/src/i18n/locales/zh-CN 의 common/core/course/insight/symlink/sys
여섯 도메인과 완전히 일치하며, {xxx} 플레이스홀더는 원래 이름을 유지합니다.
인용 부호는 한국어 관용에 맞춰 ' ' 또는 " " 를 사용합니다.
"""
UI_DICT: dict[str, str] = {
  # ---- common (공통) ----
  "common.save": "저장",
  "common.cancel": "취소",
  "common.confirm": "확인",
  "common.delete": "삭제",
  "common.edit": "편집",
  "common.search": "검색",
  "common.create": "만들기",
  "common.add": "추가",
  "common.rename": "이름 바꾸기",
  "common.close": "닫기",
  "common.refresh": "새로고침",
  "common.loading": "불러오는 중…",
  "common.empty": "데이터 없음",
  "common.back": "뒤로",
  "common.open": "열기",
  "common.all": "전체",
  "common.none": "없음",
  "common.optional": "선택 사항",
  "common.required": "필수",
  "common.name": "이름",
  "common.description": "설명",
  "common.author": "작성자",
  "common.version": "버전",
  "common.size": "크기",
  "common.path": "경로",
  "common.type": "유형",
  "common.status": "상태",
  "common.success": "성공",
  "common.failed": "실패",
  "common.error": "오류",
  "common.unknown": "알 수 없음",
  "common.actions": "작업",
  "common.more": "더 보기",
  "common.details": "상세",
  "common.preview": "미리보기",
  "common.enabled": "사용 중",
  "common.disabled": "사용 안 함",
  "common.yes": "예",
  "common.no": "아니요",
  "common.seconds": "초",
  "common.minutes": "분",
  "common.hours": "시간",
  "common.bytes": "바이트",
  "common.language": "언어",

  # ---- 네비게이션 ----
  "nav.library": "내 라이브러리",
  "nav.plugins": "플러그인",
  "nav.settings": "설정",
  "nav.stats": "통계",
  "nav.insight": "AI 인사이트",

  # ---- 통계 컴포넌트 (백엔드 widget id → 제목) ----
  "core.widget.topDocs": "가장 많이 방문한 문서",
  "core.widget.heatmap": "방문 히트맵",
  "core.widget.stayTime": "문서 체류 시간",
  "core.widget.wordCount": "콘텐츠 글자 수",
  "core.widget.recentDocs": "최근 방문",

  # ---- 테마 전환 ----
  "core.theme.toLight": "라이트 모드로 전환",
  "core.theme.toDark": "다크 모드로 전환",
  "core.theme.selectTheme": "테마 선택",

  # ---- 학습 페이지 ----
  "core.learn.markedCompleted": "학습 완료로 표시됨",
  "core.learn.unmarkedCompleted": "완료 표시가 취소됨",
  "core.learn.courseDisabledWarning":
    "이 문서는 '과정' 플러그인에 의존합니다. 문제와 인터랙티브 블록은 원시 데이터로 표시되며, '플러그인' 페이지에서 활성화할 수 있습니다.",
  "core.learn.completed": "학습 완료",
  "core.learn.markComplete": "학습 완료로 표시",
  "core.learn.readingMode": "문서 읽기",
  "core.learn.progressKnowledge": "지식 포인트 {pos} / {total}",
  "core.learn.progressDoc": "문서 {pos} / {total}",
  "core.learn.refToDoc": "이 소절은 문서 '{name}'을(를) 참조합니다",
  "core.learn.gotoRefDoc": "참조 문서로 이동",
  "core.learn.emptySection": "이 지식 포인트에는 아직 내용이 없습니다",
  "core.learn.prevKnowledge": "이전 지식 포인트",
  "core.learn.unmarkComplete": "학습 완료 표시 취소",
  "core.learn.markCurrentComplete": "현재 지식 포인트를 학습 완료로 표시",
  "core.learn.nextKnowledge": "다음 지식 포인트",
  "core.learn.unsupportedBlock": "아직 지원되지 않는 컴포넌트 유형: {type}",
  "core.learn.ref": "참조",
  "core.learn.choiceMultiple": "객관식(다중 선택)",
  "core.learn.choiceSingle": "객관식(단일 선택)",
  "core.learn.multiSelect": "다중 선택 가능",
  "core.learn.singleSelect": "단일 선택",
  "core.learn.submit": "제출",
  "core.learn.correct": "정답입니다",
  "core.learn.incorrect": "오답입니다",
  "core.learn.explanation": "해설: {text}",
  "core.learn.gradeFailed": "채점 실패",
  "core.learn.fillBlank": "빈칸 채우기",
  "core.learn.aiGraded": "AI 채점",
  "core.learn.blankN": "빈칸 {n}",
  "core.learn.accuracy": "정확도 {score}%",
  "core.learn.redo": "다시 풀기",
  "core.learn.interactiveNoFile": "인터랙티브 블록에 file 구성이 없습니다",
  "core.learn.interactiveFallback": "동적 인터랙션",
  "core.learn.interactiveTitle": "인터랙티브 데모",
  "core.learn.blockDepPrefix": "이 컴포넌트(",
  "core.learn.blockDepMid": ")는 '",
  "core.learn.blockDepPlugin": "' 플러그인(",
  "core.learn.blockDepSuffix": ")에 의존하며, 활성화되지 않으면 원시 데이터로 표시됩니다",
  "core.learn.interactiveNotRendered": "인터랙티브 블록이 렌더링되지 않음",
  "core.learn.quizNotRendered": "문제가 렌더링되지 않음",
  "core.learn.viewRaw": "원시 데이터 보기",
  "core.learn.shortAnswer": "주관식 단답형",
  "core.learn.answerPlaceholder": "답변을 입력하세요...",
  "core.learn.keywords": "핵심 키워드: {text}",
  "core.learn.submitGrade": "제출 및 채점",
  "core.learn.aiFeedback": "AI 평가: ",
  "core.learn.hint": "힌트: {text}",
  "core.plugin.unknown": "알 수 없는 플러그인",
  "core.plugin.course": "과정",

  # ---- 문서 라이브러리 ----
  "core.library.quiz": "퀴즈",
  "core.library.kindCourse": "과정",
  "core.library.kindNote": "노트",
  "core.library.kindKb": "지식 베이스",
  "core.library.kindCanvas": "다이어그램",
  "core.library.empty": "내용 없음",
  "core.library.emptyLibrary": "이 라이브러리는 비어 있습니다. 홈페이지에서 과정 패키지를 가져오거나 새 문서 컬렉션을 만드세요.",
  "core.library.library": "라이브러리",
  "core.library.deleteLibTitle": "라이브러리 삭제",
  "core.library.deleteLibDesc": "이 라이브러리를 삭제할까요? 그 아래의 모든 내용이 함께 삭제되며 복구할 수 없습니다.",
  "core.library.deletedLib": "라이브러리가 삭제되었습니다",
  "core.library.unmountTitle": "심볼릭 링크 해제",
  "core.library.unmountNameFallback": "해당 심볼릭 링크",
  "core.library.unmountDesc": "'{name}'이(가) 목록에서 제거됩니다. 디스크의 파일은 삭제되지 않습니다.",
  "core.library.unmount": "해제",
  "core.library.unmounted": "해제됨",
  "core.library.singleFile": "(단일 파일)",
  "core.library.symlink": "심볼릭 링크",
  "core.library.pluginBadge": "플러그인",
  "core.library.emptyLibraries": "라이브러리가 없습니다. 오른쪽 위에서 과정 패키지를 가져오거나 새 라이브러리를 만드세요.",
  "core.library.noSymlinks": "심볼릭 링크가 없습니다. 오른쪽에서 로컬 폴더나 파일을 추가하세요",
  "core.library.collectionCount": "문서 컬렉션 {count}개",
  "core.library.searchPlaceholder": "문서 컬렉션 검색...",
  "core.library.gridView": "그리드 보기",
  "core.library.listView": "목록 보기",
  "core.library.unitChapter": "챕터",
  "core.library.unitCanvas": "캔버스",
  "core.library.unitDoc": "문서",
  "core.library.noSearchResults": "일치하는 문서 컬렉션이 없습니다.",
  "core.library.emptyCollections": "이 라이브러리에는 아직 문서 컬렉션이 없습니다. 과정 패키지를 가져오거나 새로 만들 수 있습니다.",
  "core.library.selectPlaceholder": "라이브러리 또는 심볼릭 링크를 선택해 내용을 확인하세요.",
  "core.library.newLibTitle": "새 라이브러리",
  "core.library.namePlaceholder": "예: 전공 과목",
  "core.library.descriptionOptional": "설명(선택)",
  "core.library.descPlaceholder": "이 라이브러리에 무엇을 넣을까요",
  "core.library.createdLib": "라이브러리가 생성되었습니다",
  "core.library.newCanvas": "새 다이어그램",
  "core.library.newCanvasTitle": "새 다이어그램",
  "core.library.newCanvasPlaceholder": "다이어그램 이름",
  "core.library.newCanvasDefault": "이름 없는 다이어그램",
  "core.library.createdCanvas": "다이어그램이 생성되었습니다",
  "core.library.newDoc": "새 문서",
  "core.library.newDocTitle": "새 문서",
  "core.library.newDocPlaceholder": "문서 이름",
  "core.library.newDocDefault": "이름 없는 문서",
  "core.library.createdDoc": "문서가 생성되었습니다",
  "core.library.import": "가져오기",
  "core.library.importFailed": "가져오기 실패",
  "core.library.importedCourse": "과정 '{names}'이(가) 가져와졌습니다",
  "core.library.importedNote": "노트가 가져와졌습니다({count}개 소절)",
  "core.library.importWarning":
    "가져온 내용의 일부 컴포넌트는 '{names}' 플러그인에 의존하며, 활성화하지 않으면 원시 데이터로 표시됩니다.",
  "core.library.importedCanvas": "다이어그램 '{name}'이(가) 가져와졌습니다",
  "core.library.importedContent": "내용이 가져와졌습니다",
  "core.library.importTitle": "내용 가져오기",
  "core.library.importDesc":
    "MetaPilot 파일(.mpf/.canvas, 통일 형식: doc=과정 내용, canvas=다이어그램), 과정 패키지(zip) 및 Markdown 노트를 지원합니다.",
  "core.library.tabMpf": "MetaPilot 파일",
  "core.library.tabCourse": "과정 패키지",
  "core.library.mpfLabel": "MetaPilot 파일(.mpf / .canvas)",
  "core.library.mpfHint": "doc 유형은 과정/문서로, .canvas 파일(Obsidian Canvas)은 다이어그램으로 자동 변환됩니다.",
  "core.library.courseGateHint": "과정 패키지(zip) 가져오기",
  "core.library.courseFileLabel": "과정 패키지 파일(.zip, manifest.json 포함)",
  "core.library.noteGateHint": "Markdown 노트 가져오기",
  "core.library.noteFileLabel": "Markdown / Obsidian 파일(.md)",

  # ---- 편집 페이지 ----
  "core.edit.block.markdown": "표시(Markdown)",
  "core.edit.block.single_choice": "객관식(단일 선택)",
  "core.edit.block.multiple_choice": "객관식(다중 선택)",
  "core.edit.block.fill_blank": "빈칸 채우기",
  "core.edit.block.short_answer": "주관식 단답형",
  "core.edit.block.interactive": "동적 인터랙티브 블록",
  "core.edit.block": "컴포넌트",
  "core.edit.collectionInfo": "과정 정보",
  "core.edit.summary": "소개",
  "core.edit.newDocName": "새 챕터",
  "core.edit.newSectionName": "새 지식 포인트",
  "core.edit.deleteDocTitle": "챕터 삭제",
  "core.edit.deleteDocDesc": "이 챕터를 삭제할까요? 그 아래의 모든 소절과 내용이 삭제되며 복구할 수 없습니다.",
  "core.edit.deleteSectionTitle": "소절 삭제",
  "core.edit.deleteSectionDesc": "이 소절을 삭제할까요?",
  "core.edit.deleteBlockTitle": "컴포넌트 삭제",
  "core.edit.deleteBlockDesc": "이 컴포넌트를 삭제할까요?",
  "core.edit.newFolderTitle": "새 폴더",
  "core.edit.newFolderDesc": "새 폴더의 이름을 입력하세요.",
  "core.edit.newFolderPlaceholder": "예: 챕터 노트",
  "core.edit.renameFolderTitle": "폴더 이름 바꾸기",
  "core.edit.deleteFolderTitle": "폴더 삭제",
  "core.edit.deleteFolderDesc": "이 폴더를 삭제할까요? 그 아래의 모든 하위 폴더와 문서가 함께 삭제되며 복구할 수 없습니다.",
  "core.edit.createFailed": "만들기 실패",
  "core.edit.renameFailed": "이름 바꾸기 실패",
  "core.edit.deleteFailed": "삭제 실패",
  "core.edit.moveFailed": "이동 실패",
  "core.edit.docSettings": "챕터 설정",
  "core.edit.docNameLabel": "챕터 이름",
  "core.edit.docTypeStudy": "학습 챕터",
  "core.edit.docTypeQuiz": "퀴즈 챕터",
  "core.edit.moveDocLabel": "위치한 폴더(문서 이동)",
  "core.edit.rootFolder": "루트 디렉터리",
  "core.edit.docTypeHint": "학습 챕터와 퀴즈 챕터를 자유롭게 조합하여 학습과 시험을 분리할 수 있습니다.",
  "core.edit.sectionSettings": "지식 포인트 설정",
  "core.edit.sectionNameLabel": "지식 포인트 이름",
  "core.edit.refDocLabel": "다른 문서 참조(소절 참조)",
  "core.edit.noRef": "참조 없음",
  "core.edit.refDocHint": "참조로 설정하면 학습 페이지에 참조 카드가 표시되고 대상 문서로 이동합니다.",
  "core.edit.addBlockLabel": "컴포넌트 추가",
  "core.edit.backToSection": "소절로 돌아가기",
  "core.edit.blockSaved": "컴포넌트가 저장되었습니다",
  "core.edit.addSectionTitle": "소절 추가",
  "core.edit.noBlocks": "컴포넌트 없음",
  "core.edit.noSections": "소절 없음",
  "core.edit.subFolder": "하위 폴더",
  "core.edit.emptyFolder": "빈 폴더",
  "core.edit.mode": "편집 모드",
  "core.edit.dirty": "변경 사항 있음",
  "core.edit.saved": "저장됨",
  "core.edit.newDoc": "챕터",
  "core.edit.newFolder": "폴더",
  "core.edit.done": "완료",
  "core.edit.markdownContent": "Markdown 내용",
  "core.edit.markdownPlaceholder": "# 제목\n\n본문 내용입니다. Markdown 및 GFM 표/작업 목록을 지원합니다",
  "core.edit.question": "문제",
  "core.edit.options": "옵션(줄마다 하나)",
  "core.edit.optionsPlaceholder": "옵션 A\n옵션 B\n옵션 C",
  "core.edit.correctIndex": "정답 인덱스(0부터 시작)",
  "core.edit.correctIndexes": "정답 인덱스(쉼표로 구분)",
  "core.edit.blanksAnswers": "빈칸별 참고 답안(줄마다 하나의 빈칸)",
  "core.edit.blanksPlaceholder": "답안 1\n답안 2",
  "core.edit.reference": "참고 답안",
  "core.edit.keywordsLabel": "핵심 키워드(쉼표로 구분, AI 참고용)",
  "core.edit.keywordsPlaceholder": "키워드1,키워드2",
  "core.edit.aiGraded": "AI 채점 사용(주관식)",
  "core.edit.title": "제목",
  "core.edit.assetFile": "에셋 파일(과정 패키지 interactives/ 기준 상대 경로)",
  "core.edit.iframeHeight": "iframe 높이(px)",
  "core.edit.explanationLabel": "해설 / 힌트(선택)",

  # ---- 다이어그램 캔버스 ----
  "core.canvas.saved": "캔버스가 저장되었습니다",
  "core.canvas.saveFailed": "저장 실패",
  "core.canvas.doubleClickEdit": "더블클릭하여 텍스트 편집",
  "core.canvas.notCanvas": "이 문서 컬렉션은 다이어그램이 아닙니다.",
  "core.canvas.backToLibrary": "라이브러리로 돌아가기",
  "core.canvas.badge": "다이어그램 캔버스",
  "core.canvas.dirty": "저장되지 않은 수정 사항 있음",
  "core.canvas.unsavedTitle": "저장되지 않은 수정 사항이 있습니다",
  "core.canvas.unsavedDesc": "다이어그램에 저장되지 않은 수정 사항이 있습니다. 닫기 전에 저장하시겠습니까?",
  "core.canvas.discardAndLeave": "저장하지 않고 나가기",
  "core.canvas.saveAndLeave": "저장하고 나가기",
  "core.canvas.newTextNode": "새 텍스트 노드",
  "core.canvas.help":
    "노드를 드래그하여 이동, 빈 곳을 선택하여 영역 선택, Shift 다중 선택, Delete 삭제, Ctrl+C/V 복사·붙여넣기, Ctrl+Z 실행 취소; 텍스트 더블클릭으로 편집; 노드 가장자리 연결점을 다른 노드로 드래그하여 연결선 생성; 휠로 이동, Ctrl+휠로 확대·축소, 스페이스를 누른 채 드래그로 이동.",
  "core.canvas.undo": "실행 취소(Ctrl+Z)",
  "core.canvas.redo": "다시 실행(Ctrl+Shift+Z)",
  "core.canvas.zoomOut": "축소",
  "core.canvas.zoomIn": "확대",
  "core.canvas.fitView": "캔버스에 맞추기",
  "core.canvas.empty": "(비어 있음)",
  "core.canvas.group": "그룹",
  "core.canvas.deleteNode": "노드 삭제",
  "core.canvas.dragLink": "연결선 드래그",
  "core.canvas.emptyBoard": "빈 캔버스입니다. 오른쪽 위의 '새 텍스트 노드'를 클릭해 시작하세요",
  "core.canvas.stats": "노드 {nodes}개 · 연결선 {edges}개",
  "core.canvas.exportMpf": ".mpf 내보내기",
  "core.canvas.exportCanvas": ".canvas 내보내기",
  "core.canvas.export": "내보내기",
  "core.canvas.center": "가운데 정렬",
  "core.canvas.alignLeft": "왼쪽 정렬",
  "core.canvas.alignCenter": "가운데 정렬",
  "core.canvas.alignRight": "오른쪽 정렬",
  "core.canvas.edgePath": "연결선 스타일",
  "core.canvas.pathSmooth": "부드러운 곡선",
  "core.canvas.pathStraight": "직선",
  "core.canvas.pathSquare": "직각 꺾은선",
  "core.canvas.resize": "크기 조정",
  "core.canvas.groupSelection": "그룹 묶기",
  "core.canvas.dragAddCard": "카드 드래그하여 추가",
  "core.canvas.dragAddNote": "노트 드래그하여 추가",
  "core.canvas.dragAddNoteVault": "라이브러리에서 노트 드래그하여 추가",
  "core.canvas.dragAddMediaVault": "라이브러리에서 미디어 드래그하여 추가",
  "core.canvas.paste": "붙여넣기",
  "core.canvas.toggleNav": "탐색 펼치기/접기",
  "core.canvas.noCanvases": "다이어그램 없음",
  "core.canvas.edgeStart": "시작점",
  "core.canvas.edgeEnd": "끝점",
  "core.canvas.arrow": "화살표",
  "core.canvas.toggleStartArrow": "시작 화살표 전환",
  "core.canvas.toggleEndArrow": "끝 화살표 전환",
  "core.canvas.edgeLabel": "레이블",
  "core.canvas.colorTitle": "색상 {color}",
  "core.canvas.clearColor": "색상 지우기",
  "core.canvas.deleteEdge": "연결선 삭제",
  "core.canvas.addNode": "새 노드",
  "core.canvas.addNodeText": "텍스트",
  "core.canvas.addNodeFile": "파일",
  "core.canvas.addNodeLink": "링크",
  "core.canvas.addNodeGroup": "그룹",
  "core.canvas.addFileTitle": "파일 경로",
  "core.canvas.addFileDesc": "라이브러리 내 상대 경로입니다. 예: notes/예시.md, images/그림.png(Obsidian 호환)",
  "core.canvas.addLinkTitle": "링크 URL",
  "core.canvas.addGroupTitle": "그룹 레이블",
  "core.canvas.groupName": "그룹 이름",

  # ---- 통계 페이지 ----
  "core.stats.intro":
    "공식 코어가 기본 통계 컴포넌트를 제공하며, 과정 등 플러그인이 더 많은 컴포넌트를 추가할 수 있습니다. 카드를 드래그하여 위치를 조정하고, 오른쪽 위에서 크기를 조정하며, 설정 페이지에서 '컴포넌트 출처 표시'를 켜고 끌 수 있습니다.",
  "core.stats.resize": "크기 조정(현재 {size})",
  "core.stats.hide": "컴포넌트 숨기기",
  "core.stats.manage": "컴포넌트 관리",
  "core.stats.hiddenCount": "숨김 {count}개",
  "core.stats.manageDesc":
    "'표시 중'에서 컴포넌트를 숨기거나 '숨김' 패널에서 언제든 복원할 수 있습니다. 통계 페이지 카드를 드래그하여 위치와 순서를 조정할 수 있습니다.",
  "core.stats.none": "사용 가능한 통계 컴포넌트가 없습니다",
  "core.stats.visibleCount": "표시 중({count})",
  "core.stats.hiddenTab": "숨김({count})",
  "core.stats.noHidden": "숨겨진 컴포넌트가 없으며, 모든 컴포넌트가 표시 중입니다",
  "core.stats.resetLayout": "기본 레이아웃 복원",
  "core.stats.showAll": "모두 표시",
  "core.stats.restore": "표시 복원",
  "core.stats.noVisits": "방문 기록 없음",
  "core.stats.noStayTime": "체류 기록 없음",
  "core.stats.visits": "{count}회",
  "core.stats.wordUnit": "자",
  "core.stats.unknownWidget": "알 수 없는 컴포넌트",
  "core.stats.heatmap3m": "최근 3개월 방문 히트맵",
  "core.stats.heatmapTooltip": "{month}월 {day}일 · 방문 {count}회",
  "core.stats.heatmapLess": "적음",
  "core.stats.heatmapMore": "많음",
  "core.stats.hourly": "시간대별 방문 분포",
  "core.stats.hourTooltip": "{hour}시 · {count}회",
  "core.stats.hourLabel": "{hour}시",
  "core.stats.monthLabel": "{month}월",
  "core.stats.weekdays": "월,화,수,목,금,토,일",
  "core.stats.courseDisabled": "'과정' 플러그인에 의존하며 활성화되지 않음",
  "core.stats.totalStudy": "누적 학습",
  "core.stats.chartMinutes": "분",
  "core.stats.noStudyRecords": "학습 기록 없음",
  "core.stats.providedBy": "'{name}' 플러그인 제공",
  "core.stats.providedByTooltip": "{name} 플러그인 제공",

  # ---- 공통 다이얼로그 / 토스트 ----
  "core.dialog.selectPlaceholder": "선택하세요…",
  "core.toast.copied": "클립보드에 복사되었습니다",
  "core.widget.aiUsage": "AI 사용량",
  "core.stats.rangeToday": "오늘",
  "core.stats.rangeWeek": "이번 주",
  "core.stats.rangeMonth": "이번 달",
  "core.stats.rangeAll": "전체",
  "core.stats.aiCalls": "호출 횟수",
  "core.stats.aiTokens": "토큰 사용량",
  "core.stats.aiCost": "비용",
  "core.stats.aiTokensDetail": "입력 {in} / 캐시 {cached} / 출력 {out}",
  "core.stats.aiCallsShort": "호출 {n}회",
  "core.stats.aiTokensShort": "{n} tokens",
  "core.stats.aiUsageEmpty": "AI 사용량 기록이 없습니다(각 플러그인의 통합 게이트웨이 호출이 여기에 기록됩니다).",

  # ---- course (과정 플러그인) ----
  "course.exportFailed": "내보내기 실패",
  "course.pluginDisabledWarning": "이 문서는 '과정' 플러그인에 의존합니다. 학습 진행도와 문제 인터랙션이 불가하며, '플러그인' 페이지에서 활성화할 수 있습니다.",
  "course.backToLibrary": "라이브러리로 돌아가기",
  "course.noDescription": "소개 없음",
  "course.authorLabel": "작성자: {author}",
  "course.export": "내보내기",
  "course.continueLearning": "학습 계속하기",
  "course.learningProgress": "학습 진행도",
  "course.progressCount": "지식 포인트 {completed} / {total}",
  "course.lastLearned": "마지막 학습: {name}",
  "course.progressRequiresPlugin": "학습 진행도는 '과정' 플러그인에 의존합니다. 활성화하면 완료 표시와 마지막 학습 위치 추적이 가능합니다.",
  "course.quiz": "퀴즈",
  "course.noSectionsInChapter": "이 챕터에는 소절이 없습니다",
  "course.noChapters": "이 과정에는 아직 챕터가 없습니다. 오른쪽 위의 '편집'을 클릭해 만들어 보세요.",
  "course.library.newCourse": "새 과정",
  "course.library.newCourseTitle": "새 과정",
  "course.library.newCoursePlaceholder": "과정 이름",
  "course.library.newCourseDefault": "이름 없는 과정",
  "course.library.createdCourse": "과정이 생성되었습니다",
  "course.library.createCourseFailed": "과정 만들기 실패",
  "course.library.toCourse": "과정으로 전환",
  "course.library.toCourseTitle": "과정으로 전환",
  "course.library.toCourseDesc": "'{name}'을(를) 과정으로 전환할까요? 과정은 패치된 문서로, 학습 진행도, 채점, 인터랙티브 블록 등 과정 기능을 사용할 수 있습니다. '과정' 플러그인이 활성화되지 않으면 과정 패치 기능을 사용할 수 없습니다.",
  "course.library.toCourseConfirm": "과정으로 전환",
  "course.library.convertedCourse": "'{name}'이(가) 과정으로 전환되었습니다",
  "course.library.convertCourseFailed": "과정 전환 실패",

  # ---- insight (AI 인사이트) ----
  "insight.pageTitle": "AI 인사이트",
  "insight.intro": "문서나 라이브러리 모음을 선택하고, 인덱스를 만든 뒤 AI에게 맡겨 생각하게 하세요: 자료 간의 연관성을 조사하여 네 가지 모드로 답변, 제안 또는 다이어그램/과정을 생성합니다.",
  "insight.introWithSymlink": "문서, 라이브러리 또는 로컬 디렉터리 모음을 선택하고, 인덱스를 만든 뒤 AI에게 맡겨 생각하게 하세요: 자료 간의 연관성을 조사하여 네 가지 모드로 답변, 제안 또는 다이어그램/과정을 생성합니다.",
  "insight.stepIndex": "1단계 · 인덱스 만들기",
  "insight.stepAsk": "2단계 · AI에게 묻기",
  "insight.stepIndexQuoted": "'1단계 · 인덱스 만들기'",
  "insight.mustIndexBefore": "인덱스를 먼저 만든 뒤 질문하세요. 만들지 않고 바로 질문하면 자동으로 만들어집니다(진행 상황 표시).",
  "insight.noIndexedBefore": "아직 인덱스가 만들어진 데이터 소스가 없습니다. 먼저",
  "insight.noIndexedAfter": "에서 선택한 내용에 대해 벡터 인덱스를 만든 뒤 질문하세요.",
  "insight.noIndexedAfterWithSymlink": "에서 선택한 문서 / 로컬 디렉터리에 대해 벡터 인덱스를 만든 뒤 질문하세요.",
  "insight.vectorModelTitle": "벡터 모델과 로컬 서비스",
  "insight.embeddingRunning": "실행 중",
  "insight.embeddingNotReady": "준비 안 됨",
  "insight.selectModelPlaceholder": "embedding 모델 선택",
  "insight.stopService": "서비스 중지",
  "insight.startService": "서비스 시작(처음에는 선택한 모델을 자동 다운로드)",
  "insight.modelDownloadHint": "모델 다운로드는 여러 경로로 자동 시도되며, 처음 다운로드할 때는 모델이 준비될 때까지 기다려야 하고 페이지가 자동으로 상태를 새로고침합니다. 구체적인 다운로드 소스와 모델 목록은 백엔드 구성에 따릅니다.",
  "insight.selectSourcesTitle": "데이터 소스 선택(다중 선택 가능)",
  "insight.indexIntro": "라이브러리, 개별 문서 컬렉션, 개별 문서 단위로 선택할 수 있습니다. 인덱스는 데이터 소스별로 독립적으로 저장됩니다.",
  "insight.indexIntroWithSymlink": "라이브러리, 문서 컬렉션, 문서 단위로 선택하거나 전체 로컬 디렉터리 또는 디렉터리 내 임의 경로를 선택할 수 있습니다. 인덱스는 데이터 소스별로 독립적으로 저장됩니다.",
  "insight.indexing": "인덱스 생성 중...",
  "insight.indexingProgress": "{done}/{total} 구간 인덱스 완료",
  "insight.indexQueued": "인덱스 생성을 시작했습니다. 아래에서 진행 상황을 확인할 수 있습니다",
  "insight.buildVectorIndex": "벡터 인덱스 만들기",
  "insight.noSources": "사용 가능한 데이터 소스가 없습니다. 먼저 '내 라이브러리'에서 라이브러리를 만드세요.",
  "insight.noSourcesWithSymlink": "사용 가능한 데이터 소스가 없습니다. 먼저 '내 라이브러리'에서 라이브러리를 만들거나 로컬 디렉터리를 마운트하세요.",
  "insight.askSourcesTitle": "생각에 사용할 데이터 소스 선택(다중 선택, 통합 검색)",
  "insight.askTitle": "AI 생각(답변에 출처 표시)",
  "insight.askPlaceholder": "AI에게 질문하세요. 예: \"이 자료들 사이에 어떤 연관성이 있을까요?\"",
  "insight.refSources": "참조 출처",
  "insight.sourceRef": "[출처{n}]",
  "insight.asking": "검색하고 답변을 생성하는 중...",
  "insight.inputPlaceholder": "질문이나 생각 방향을 입력하세요...",
  "insight.askButton": "질문",
  "insight.groupLibrary": "라이브러리 문서(라이브러리 / 문서 컬렉션 / 문서)",
  "insight.groupSymlink": "로컬 디렉터리 마운트",
  "insight.indexedCount": "인덱스 {count}개 구간 완료",
  "insight.notIndexed": "인덱스 안 됨",
  "insight.pluginHint": "AI 인사이트: 자료 연관성을 분석하고 내용을 생성합니다",
  "insight.loadResourcesFailed": "데이터 소스 불러오기 실패",
  "insight.startServiceToast": "서비스 시작 중(처음 실행 시 선택한 모델을 자동 다운로드)",
  "insight.startFailed": "시작 실패",
  "insight.serviceStopped": "서비스가 중지되었습니다",
  "insight.indexDone": "인덱스 완료: 데이터 소스 {ok}/{total}",
  "insight.indexFailed": "인덱스 실패",
  "insight.askFailed": "질문/답변 실패",
  "insight.modeTitle": "생각 모드",
  "insight.modeIntro": "생각 방식을 하나 선택하면 AI가 해당 방식으로 선택한 자료를 조사하고 내용을 생성합니다.",
  "insight.modeAssist": "보조 사고",
  "insight.modeAssistDesc": "자료 간의 연관성을 찾아 답변과 제안을 제공합니다",
  "insight.modeWander": "사고의 유랑",
  "insight.modeWanderDesc": "자료와 당신의 생각 방향을 결합해 발산적 연상을 펼칩니다",
  "insight.modeReflect": "반성적 정리",
  "insight.modeReflectDesc": "당신이 놓쳤을 수 있는 연관성과 맹점을 정리합니다",
  "insight.modePlan": "인사이트 플래닝",
  "insight.modePlanDesc": "다중 라운드 추론으로 다이어그램이나 과정을 생성해 가르쳐줍니다",
  "insight.planOutputTitle": "생성 유형",
  "insight.planOutputCanvas": "지식 다이어그램(캔버스)",
  "insight.planOutputCourse": "마이크로 과정(문서)",
  "insight.planLibraryTitle": "저장할 라이브러리",
  "insight.planLibraryAuto": "기본 라이브러리(첫 번째)",
  "insight.planGoalPlaceholder": "계획 목표를 입력하세요. 예: 이 자료들의 핵심 개념과 연관성을 정리해서 가장 짧은 시간에 이해할 수 있게 가르쳐줘",
  "insight.planButton": "인사이트 플래닝 시작",
  "insight.planning": "AI가 다중 라운드로 자료 연관성을 분석하고 생성하고 있습니다. 1-2분 걸릴 수 있습니다...",
  "insight.planDone": "'{name}'이(가) 생성되었습니다",
  "insight.planOpenCanvas": "다이어그램 열기",
  "insight.planOpenCourse": "과정 열기",
  "insight.planSummary": "계획 요약",
  "insight.planFailed": "인사이트 플래닝 실패",
  "insight.planRoadmap": "AI 실행 경로",
  "insight.planThinking": "AI 사고 과정",
  "insight.planStep.retrieve": "자료 검색",
  "insight.planStep.plan": "주제 및 연관성 분석",
  "insight.planStep.review": "비판적 반성",
  "insight.planStep.generateCanvas": "지식 다이어그램 생성",
  "insight.planStep.generateCourse": "마이크로 과정 생성",
  "insight.planStep.save": "라이브러리에 저장",
  "insight.planStepRunning": "진행 중…",
  "insight.planConnecting": "AI에 연결하고 실행 경로를 계획하는 중…",
  "insight.autoIndexing": "선택한 데이터 소스에 아직 인덱스가 없어 자동으로 만드는 중입니다({done}/{total})...",
  "insight.autoIndexDone": "인덱스 완료, 생성 계속 진행 중...",
  "insight.autoIndexFailed": "자동 인덱스 생성에 실패했습니다. 먼저 1단계에서 수동으로 인덱스를 만드세요",
  "insight.symlinkBrowse": "디렉터리 탐색",
  "insight.treeEmpty": "(비어 있음)",
  "insight.kbTitle": "데이터 검색 라이브러리",
  "insight.goAsk": "질문하러 가기",
  "insight.selectedCount": "선택 {count}개",
  "insight.kbIndexed": "인덱스 {count}개 소스 완료",
  "insight.collapsePanel": "데이터 검색 라이브러리 패널 접기",
  "insight.expandPanel": "데이터 검색 라이브러리 패널 펼치기",
  "insight.kbHint": "라이브러리 / 문서 컬렉션 / 문서를 검색 범위로 선택할 수 있습니다: 인덱스를 만들거나 바로 질문할 수 있으며, 인덱스가 없는 소스는 질문 시 자동으로 만들어집니다.",
  "insight.kbHintWithSymlink": "라이브러리 / 문서 컬렉션 / 문서 또는 로컬 디렉터리를 검색 범위로 선택할 수 있습니다: 인덱스를 만들거나 바로 질문할 수 있으며, 인덱스가 없는 소스는 질문 시 자동으로 만들어집니다.",
  "insight.buildIndexTitle": "벡터 인덱스 만들기",
  "insight.buildIndexHint": "선택한 데이터 소스 {count}개(왼쪽 '데이터 검색 라이브러리'에서 조정 가능). 인덱스가 없는 것도 함께 만들어집니다.",

  # ---- symlink (심볼릭 링크 플러그인) ----
  "symlink.fileBrowser": "파일 브라우저",
  "symlink.symlinkPlugin": "심볼릭 링크 플러그인",
  "symlink.pluginHint": "로컬 디렉터리 탐색 및 읽기·쓰기",
  "symlink.linkLocalDoc": "로컬 문서 연결(심볼릭 링크)",
  "symlink.addMountDesc1": "연결하는 대상은 로컬 디스크의",
  "symlink.addMountDesc2": "또는",
  "symlink.addMountDesc3": "이며, 원본 파일은 복사되거나 이동되지 않습니다. 연결 후 파일 브라우저에서 문서처럼 탐색, 읽기, 편집할 수 있습니다.",
  "symlink.mounts": "마운트",
  "symlink.mount": "마운트",
  "symlink.thatMount": "해당 마운트",
  "symlink.unmount": "해제",
  "symlink.unmountSymlink": "심볼릭 링크 해제",
  "symlink.unmountConfirmDesc": "'{name}'이(가) 목록에서 제거됩니다. 디스크의 파일은 삭제되지 않습니다.",
  "symlink.noMounts": "마운트가 없습니다. 오른쪽 위에서 로컬 폴더나 파일을 추가하세요",
  "symlink.currentMountRoot": "현재 마운트 루트: {root}",
  "symlink.pleaseMount": "먼저 로컬 폴더나 파일을 마운트하세요",
  "symlink.mountSuccess": "마운트 성공",
  "symlink.mountFailed": "마운트 실패",
  "symlink.displayName": "표시 이름",
  "symlink.namePlaceholder": "예: 내 노트",
  "symlink.localPathLabel": "로컬 경로(폴더 또는 파일)",
  "symlink.pathPlaceholder": "'탐색'을 클릭해 선택하거나 직접 입력하세요(Windows/Linux 모두 지원)",
  "symlink.collapse": "접기",
  "symlink.browse": "탐색",
  "symlink.afterMountHint": "마운트 후 파일 브라우저에서 디렉터리 내 텍스트 파일을 탐색, 읽기, 편집할 수 있습니다(권한은 마운트 루트 내로 제한).",
  "symlink.directory": "디렉터리",
  "symlink.folder": "폴더",
  "symlink.file": "파일",
  "symlink.singleFile": "단일 파일",
  "symlink.singleFileNote": "(단일 파일)",
  "symlink.singleFileMount": "(단일 파일 마운트)",
  "symlink.rootDir": "(루트 디렉터리)",
  "symlink.noSubfolders": "하위 폴더 없음",
  "symlink.emptyDir": "빈 디렉터리",
  "symlink.expandDir": "디렉터리 펼치기",
  "symlink.collapseDir": "디렉터리 접기",
  "symlink.newFolder": "새 폴더",
  "symlink.newFolderDesc": "새 폴더의 이름을 입력하세요.",
  "symlink.newFolderPlaceholder": "예: 챕터 노트",
  "symlink.searchPlaceholder": "검색…",
  "symlink.gridView": "그리드 보기",
  "symlink.listView": "목록 보기",
  "symlink.backToList": "목록으로 돌아가기",
  "symlink.reveal": "위치 열기",
  "symlink.revealInFileManager": "파일 관리자에서 표시",
  "symlink.openWithDefault": "기본 방식으로 열기",
  "symlink.editing": "편집 중: {path}",
  "symlink.saved": "저장되었습니다",
  "symlink.saveFailed": "저장 실패",
  "symlink.createFailed": "만들기 실패",
  "symlink.deleteFile": "파일 삭제",
  "symlink.deleteConfirmDesc": "'{target}'을(를) 삭제할까요?",
  "symlink.deleteDirWarning": "폴더는 재귀적으로 삭제되며 복구할 수 없습니다.",
  "symlink.deleteFailed": "삭제 실패",
  "symlink.openedWithDefault": "시스템 기본 방식으로 열었습니다",
  "symlink.openFailed": "열기 실패",
  "symlink.readFailed": "읽기 실패",
  "symlink.noInlinePreview": "이 파일 형식은 인라인 미리보기를 지원하지 않습니다",
  "symlink.noInlinePreviewHint": "이 파일 형식은 인라인 미리보기를 지원하지 않습니다. 오른쪽 클릭 후 '기본 방식으로 열기'를 선택하세요",
  "symlink.noMatch": "일치하는 항목이 없습니다.",
  "symlink.goUp": "상위 폴더",
  "symlink.myComputer": "내 컴퓨터",
  "symlink.reading": "읽는 중…",
  "symlink.emptyFolder": "빈 폴더",
  "symlink.selectedFolder": "폴더: {path}",
  "symlink.selectedFile": "파일: {path}",
  "symlink.selectHint": "클릭하여 폴더나 파일을 선택하고, 더블클릭하면 폴더에 들어갑니다",
  "symlink.selectThisFolder": "이 폴더 선택",
  "symlink.selectThisFile": "이 파일 선택",

  # ---- sys (시스템 설정 / 플러그인 관리 / 테마) ----
  "sys.title": "설정",
  "sys.subtitle": "플러그인 관련 안내 동작을 제어합니다. MetaPilot은 문서 라이브러리입니다: 문서는 항상 열어 볼 수 있으며, 렌더링되지 않은 부분은 원시 데이터로 표시됩니다. 안내는 알림일 뿐 작업을 방해하지 않습니다.",
  "sys.language": "언어",
  "sys.languageDesc": "인터페이스 표시 언어. 전환 즉시 적용되며 로컬(localStorage)에 저장됩니다.",
  "sys.appearance": "외관",
  "sys.appearanceDesc": "다크 / 라이트 모드는 언제든 전환할 수 있습니다. 특별 테마는 '테마' 플러그인이 제공합니다(플러그인 관리 페이지에서 활성화한 뒤 선택 설치).",
  "sys.pluginWarnings": "플러그인 경고 알림",
  "sys.pluginWarningsDesc": "비활성화된 플러그인에 의존하는 문서(예: 과정, 지식 베이스)를 열면 상단에 경고 버블이 표시되며, \"이 내용은 xx 플러그인에 의존하며 일부 컴포넌트가 렌더링되지 않을 수 있습니다\"라고 알립니다.",
  "sys.pluginErrors": "플러그인 오류 알림",
  "sys.pluginErrorsDesc": "작업 시 플러그인이 활성화되지 않아 실패하면(예: AI 채점, 지식 베이스 질문) 상단에 오류 버블이 표시됩니다. 닫으면 이러한 오류는 조용히 무시됩니다.",
  "sys.componentSource": "컴포넌트 출처 표시",
  "sys.componentSourceDesc": "켜면 라이브러리, 통계 등의 페이지에서 플러그인이 제공하는 컴포넌트/콘텐츠에 해당 플러그인의 아이콘이 표시됩니다(마우스를 올리면 플러그인 이름 확인 가능). 공식 코어(MetaPilot 자체)는 표시하지 않습니다. 끄면 출처 표시가 나타나지 않습니다.",
  "sys.localOnly": "안내는 브라우저 로컬(localStorage)에만 저장되며 다른 기기에 영향을 주지 않습니다.",
  "sys.plugins.title": "플러그인 관리",
  "sys.plugins.headerPrefix": "플러그인은 사용자 정의, 공식 플러그인, 공식 코어의 세 가지로 나뉩니다. 플러그인은 백엔드 ",
  "sys.plugins.headerSuffix": " 디렉터리 아래의 독립 기능 패키지이며, '플러그인 스토어'에서 탐색 설치하거나 직접 만든 플러그인을 업로드할 수 있습니다.",
  "sys.plugins.tabLocal": "로컬 플러그인",
  "sys.plugins.tabStore": "플러그인 스토어",
  "sys.plugins.filterByTag": "태그로 필터링:",
  "sys.plugins.sourceUser": "사용자 정의 플러그인",
  "sys.plugins.sourceUserDesc": "직접 개발하거나, 플러그인 스토어에서 설치하거나, zip을 업로드하여 설치할 수 있습니다. 비활성화하거나 삭제할 수 있습니다.",
  "sys.plugins.sourceOfficial": "공식 플러그인",
  "sys.plugins.sourceOfficialDesc": "MetaPilot이 공식 개발한 실용 플러그인입니다. 선택해서 사용하거나 비활성화할 수 있으며 삭제할 수 없습니다.",
  "sys.plugins.sourceCore": "공식 코어",
  "sys.plugins.sourceCoreDesc": "MetaPilot 자체: 문서 라이브러리 탐색과 Markdown 읽기입니다. 비활성화하거나 삭제할 수 없습니다.",
  "sys.plugins.enabledToast": "플러그인이 활성화되었습니다",
  "sys.plugins.disabledToast": "플러그인이 비활성화되었습니다",
  "sys.plugins.opFailed": "작업 실패",
  "sys.plugins.deleteTitle": "플러그인 삭제",
  "sys.plugins.deleteDesc": "플러그인 '{name}'을(를) 삭제할까요? backend/plugins/{id} 디렉터리가 물리적으로 삭제되며 복구할 수 없습니다.",
  "sys.plugins.deletedToast": "플러그인 '{name}'이(가) 삭제되었습니다",
  "sys.plugins.deleteFailed": "삭제 실패",
  "sys.plugins.idLabel": "id:",
  "sys.plugins.dependsOn": "의존 플러그인:",
  "sys.plugins.missingDeps": "누락된 의존성(먼저 활성화 필요):",
  "sys.plugins.featureCourseImport": "과정 패키지 가져오기 / 내보내기",
  "sys.plugins.featureCourseFlow": "챕터 지식 포인트 학습(컴포넌트 흐름)",
  "sys.plugins.featureCourseProgress": "학습 진행도 및 시간 통계",
  "sys.plugins.featureCourseGrading": "주관식 AI 채점",
  "sys.plugins.featureCourseInteractive": "동적 인터랙티브 블록 렌더링",
  "sys.plugins.featureInsightIndex": "다중 세분화 데이터 소스 벡터 인덱스(라이브러리/문서 컬렉션/문서/로컬 디렉터리)",
  "sys.plugins.featureInsightModes": "네 가지 생각 모드(보조 사고/사고의 유랑/반성적 정리/인사이트 플래닝)",
  "sys.plugins.featureInsightPlan": "다중 라운드 추론으로 다이어그램과 마이크로 과정(.mpf) 생성",
  "sys.plugins.needEnablePrefix": "'",
  "sys.plugins.needEnableSuffix": "' 플러그인을 활성화해야 사용할 수 있습니다",
  "sys.plugins.thisFeature": "이 기능",
  "sys.plugins.goEnable": "플러그인 관리 페이지에서 활성화",
  "sys.plugins.uploadTitle": "플러그인 업로드(로컬 설치)",
  "sys.plugins.uploadDescPrefix": "규격에 따라 패키징된 플러그인 zip을 선택하세요(루트 디렉터리 ",
  "sys.plugins.uploadDescSuffix": " 포함, 플러그인 개발 규격 §3 참조). 설치하면 바로 아래 목록에 나타나며 비활성화하거나 삭제할 수 있습니다.",
  "sys.plugins.uploadInstall": "로컬 설치",
  "sys.plugins.uploadSuccess": "플러그인이 설치되었습니다",
  "sys.plugins.uploadFailed": "설치 실패",
  "sys.store.storeUnavailable": "플러그인 스토어에 접근할 수 없습니다",
  "sys.store.installedToast": "플러그인 '{name}'이(가) 설치되었습니다",
  "sys.store.installFailed": "설치 실패",
  "sys.store.localInstalledToast": "플러그인이 로컬에 설치되었습니다",
  "sys.store.publishedToast": "플러그인 스토어에 게시되었습니다",
  "sys.store.uploadFailed": "업로드 실패",
  "sys.store.headerPrefix": "플러그인 스토어에서 플러그인을 탐색, 필터링, 설치합니다(스토어 주소는 백엔드 ",
  "sys.store.headerSuffix": " 구성).",
  "sys.store.checkUpdates": "업데이트 확인",
  "sys.store.emptyFiltered": "스토어에 일치하는 플러그인이 없습니다.",
  "sys.store.installed": "설치됨",
  "sys.store.install": "설치",
  "sys.store.uploadTitle": "플러그인 업로드",
  "sys.store.uploadDescPrefix": "규격에 따라 패키징된 플러그인 zip을 선택하세요(루트 디렉터리 ",
  "sys.store.uploadDescSuffix": " 포함, 플러그인 개발 규격 §3 참조): 로컬 설치하거나 플러그인 스토어에 게시할 수 있습니다.",
  "sys.store.uploadLocal": "로컬 설치",
  "sys.store.uploadPublish": "스토어에 게시",
  "sys.theme.mode": "다크 / 라이트 모드",
  "sys.theme.light": "라이트",
  "sys.theme.dark": "다크",
  "sys.theme.featured": "특별 테마",
  "sys.theme.pluginDisabled": "테마는 '테마' 플러그인이 제공하며 현재 활성화되지 않았습니다.",
  "sys.theme.defaultName": "기본",
  "sys.theme.defaultDesc": "시스템 색상 따르기",
  "sys.plugins.changelogBtn": "업데이트 내역",
  "sys.plugins.changelogTitle": "{name} · 업데이트 내역",
  "sys.plugins.changelogDesc": "현재 설치 버전 v{version}. 타임라인은 버전 내림차순으로 업데이트 내역을 보여줍니다.",
  "sys.plugins.changelogEmpty": "이 플러그인에는 업데이트 내역이 없습니다.",
  "sys.plugins.currentVersion": "현재 버전",
  "sys.ai.title": "AI 서비스(통합 게이트웨이)",
  "sys.ai.desc": "모든 플러그인의 AI 호출은 MetaPilot을 경유합니다. 키와 주소는 백엔드 .env에만 저장되며 플러그인과 프런트엔드는 평문을 얻을 수 없습니다.",
  "sys.ai.loadFailed": "AI 구성 불러오기 실패",
  "sys.ai.provider": "API 제공업체",
  "sys.ai.providerOpenai": "OpenAI 호환(MiniMax / DeepSeek 등 포함)",
  "sys.ai.providerAnthropic": "Anthropic",
  "sys.ai.providerLocal": "로컬 모델(내장)",
  "sys.ai.providerNone": "클라우드 AI 끄기",
  "sys.ai.chatModel": "채팅 모델",
  "sys.ai.baseUrl": "API 주소",
  "sys.ai.apiKey": "API Key",
  "sys.ai.apiKeyPlaceholder": "구성됨(비워두면 기존 값 유지)",
  "sys.ai.embeddingTitle": "벡터(embedding)",
  "sys.ai.embeddingProvider": "벡터 서비스",
  "sys.ai.embeddingLocal": "로컬 내장(다운로드 필요)",
  "sys.ai.embeddingOpenai": "클라우드(위 API 주소 사용)",
  "sys.ai.embeddingNone": "벡터 끄기",
  "sys.ai.embeddingModel": "벡터 모델",
  "sys.ai.embeddingUrl": "로컬 벡터 주소",
  "sys.ai.prices": "모델 가격(백만 토큰당)",
  "sys.ai.pricesHint": "통계 페이지의 비용 추정에 사용됩니다. 캐시 적중 / 입력 / 출력 단가, 통화 $ 또는 ¥",
  "sys.ai.priceModel": "모델",
  "sys.ai.priceInput": "입력",
  "sys.ai.priceCached": "캐시 적중",
  "sys.ai.priceOutput": "출력",
  "sys.ai.addPrice": "모델 가격 추가",
  "sys.ai.currency": "기본 통화",
  "sys.ai.save": "구성 저장",
  "sys.ai.saved": "AI 구성이 저장되었습니다(.env에 기록)",
  "sys.ai.saveFailed": "저장 실패",
  "sys.ai.test": "연결 테스트",
  "sys.ai.testing": "테스트 중...",
  "sys.ai.testOk": "연결 성공: {model}(입력 {in} / 출력 {out} tokens)",
  "sys.ai.testFailed": "연결 실패",
  "sys.ai.localTitle": "내장 로컬 모델",
  "sys.ai.localDesc": "필요할 때 원클릭 다운로드(다중 미러 자동 시도). 다운로드 후 바로 시작하여 사용할 수 있습니다",
  "sys.ai.downloaded": "다운로드됨",
  "sys.ai.notDownloaded": "다운로드 안 됨",
  "sys.ai.downloading": "다운로드 중...",
  "sys.ai.download": "다운로드",
  "sys.ai.start": "시작",
  "sys.ai.startFailed": "시작 실패",
  "sys.ai.stop": "중지",
  "sys.ai.running": "실행 중",
  "sys.ai.notRunning": "실행 안 됨",
  "sys.ai.modelKindEmbedding": "벡터",
  "sys.ai.modelKindLlm": "대화",
  "sys.ai.modelKindRerank": "재정렬",
  "sys.ai.localOnlyHint": "위 구성은 로컬 .env에만 저장되며 어떤 서비스에도 업로드되지 않습니다.",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "심볼릭 링크 추가",
    "core.library.defaultLib": "기본",
    "core.library.defaultSet": "기본 라이브러리로 설정됨",
    "core.library.menuMore": "추가 작업",
    "core.library.pin": "상단 고정",
    "core.library.pinned": "고정됨",
    "core.library.pinnedLib": "상단에 고정됨",
    "core.library.renameLib": "이름 바꾸기",
    "core.library.renameLibTitle": "라이브러리 이름 바꾸기",
    "core.library.renamedLib": "라이브러리 이름이 변경됨",
    "core.library.setDefault": "기본으로 설정",
    "core.library.unpin": "상단 고정 해제",
    "core.library.unpinnedLib": "고정 해제됨",
}
