# -*- coding: utf-8 -*-
"""俄语（ru）界面语言词典。

key 集合与 zh-CN 核心词典完全一致（common/core/course/insight/symlink/sys 六个域合并），
value 为俄语翻译，保留全部 {xxx} 占位符（名称不变，位置按俄语语序调整），
引号使用俄语 кавычки « »。由 examples/world-languages-plugin/ui_dicts/__init__.py 聚合。
"""

UI_DICT: dict[str, str] = {
    # ---- 通用词条 common ----
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.confirm": "Подтвердить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.search": "Поиск",
    "common.create": "Создать",
    "common.add": "Добавить",
    "common.rename": "Переименовать",
    "common.close": "Закрыть",
    "common.refresh": "Обновить",
    "common.loading": "Загрузка…",
    "common.empty": "Нет данных",
    "common.back": "Назад",
    "common.open": "Открыть",
    "common.all": "Все",
    "common.none": "Нет",
    "common.optional": "Необязательно",
    "common.required": "Обязательно",
    "common.name": "Название",
    "common.description": "Описание",
    "common.author": "Автор",
    "common.version": "Версия",
    "common.size": "Размер",
    "common.path": "Путь",
    "common.type": "Тип",
    "common.status": "Статус",
    "common.success": "Успешно",
    "common.failed": "Не удалось",
    "common.error": "Ошибка",
    "common.unknown": "Неизвестно",
    "common.actions": "Действия",
    "common.more": "Ещё",
    "common.details": "Подробнее",
    "common.preview": "Предпросмотр",
    "common.enabled": "Включено",
    "common.disabled": "Отключено",
    "common.yes": "Да",
    "common.no": "Нет",
    "common.seconds": "сек.",
    "common.minutes": "мин.",
    "common.hours": "ч",
    "common.bytes": "Б",
    "common.language": "Язык",

    # ---- 导航 ----
    "nav.library": "Моя библиотека",
    "nav.plugins": "Плагины",
    "nav.settings": "Настройки",
    "nav.stats": "Статистика",
    "nav.insight": "AI-аналитика",

    # ---- 统计组件 ----
    "core.widget.topDocs": "Самые посещаемые документы",
    "core.widget.heatmap": "Тепловая карта посещений",
    "core.widget.stayTime": "Время на документе",
    "core.widget.wordCount": "Количество слов",
    "core.widget.recentDocs": "Недавние",

    # ---- 主题切换 ----
    "core.theme.toLight": "Переключить на светлый режим",
    "core.theme.toDark": "Переключить на тёмный режим",
    "core.theme.selectTheme": "Выбрать тему",

    # ---- 学习页 ----
    "core.learn.markedCompleted": "Отмечено как изученное",
    "core.learn.unmarkedCompleted": "Отметка снята",
    "core.learn.courseDisabledWarning": "Этот документ зависит от плагина «Курс»: задания и интерактивные блоки будут показаны как исходные данные. Включите плагин на странице «Плагины».",
    "core.learn.completed": "Изучено",
    "core.learn.markComplete": "Отметить как изученное",
    "core.learn.readingMode": "Чтение документа",
    "core.learn.progressKnowledge": "{pos} / {total} пунктов знаний",
    "core.learn.progressDoc": "{pos} / {total} документов",
    "core.learn.refToDoc": "В этом разделе цитируется документ «{name}»",
    "core.learn.gotoRefDoc": "Перейти к цитируемому документу",
    "core.learn.emptySection": "В этом пункте знаний пока нет содержимого",
    "core.learn.prevKnowledge": "Предыдущий пункт знаний",
    "core.learn.unmarkComplete": "Снять отметку об изучении",
    "core.learn.markCurrentComplete": "Отметить этот пункт как изученный",
    "core.learn.nextKnowledge": "Следующий пункт знаний",
    "core.learn.unsupportedBlock": "Неподдерживаемый тип блока: {type}",
    "core.learn.ref": "Цитата",
    "core.learn.choiceMultiple": "Множественный выбор",
    "core.learn.choiceSingle": "Одиночный выбор",
    "core.learn.multiSelect": "Можно выбрать несколько",
    "core.learn.singleSelect": "Одиночный выбор",
    "core.learn.submit": "Отправить",
    "core.learn.correct": "Верно",
    "core.learn.incorrect": "Неверно",
    "core.learn.explanation": "Разбор: {text}",
    "core.learn.gradeFailed": "Не удалось оценить",
    "core.learn.fillBlank": "Заполнение пропусков",
    "core.learn.aiGraded": "Оценка ИИ",
    "core.learn.blankN": "Пропуск {n}",
    "core.learn.accuracy": "Точность {score}%",
    "core.learn.redo": "Повторить",
    "core.learn.interactiveNoFile": "В интерактивном блоке отсутствует конфигурация file",
    "core.learn.interactiveFallback": "Динамическое взаимодействие",
    "core.learn.interactiveTitle": "Интерактивная демонстрация",
    "core.learn.blockDepPrefix": "Блок (",
    "core.learn.blockDepMid": ") зависит от плагина «",
    "core.learn.blockDepPlugin": "» (",
    "core.learn.blockDepSuffix": "); при отключении плагина данные показываются в исходном виде",
    "core.learn.interactiveNotRendered": "Интерактивный блок не отрендерен",
    "core.learn.quizNotRendered": "Задание не отрендерено",
    "core.learn.viewRaw": "Показать исходные данные",
    "core.learn.shortAnswer": "Краткий ответ",
    "core.learn.answerPlaceholder": "Введите ваш ответ...",
    "core.learn.keywords": "Ключевые слова: {text}",
    "core.learn.submitGrade": "Отправить на оценку",
    "core.learn.aiFeedback": "Комментарий ИИ: ",
    "core.learn.hint": "Подсказка: {text}",

    # ---- 插件 ----
    "core.plugin.unknown": "Неизвестный плагин",
    "core.plugin.course": "Курс",

    # ---- 文档库 ----
    "core.library.quiz": "Тест",
    "core.library.kindCourse": "Курс",
    "core.library.kindNote": "Заметка",
    "core.library.kindKb": "База знаний",
    "core.library.kindCanvas": "Канвас",
    "core.library.empty": "Нет содержимого",
    "core.library.emptyLibrary": "Эта библиотека пуста: импортируйте пакет курса на главной странице или создайте новый набор документов.",
    "core.library.library": "Библиотека",
    "core.library.deleteLibTitle": "Удалить библиотеку",
    "core.library.deleteLibDesc": "Удалить эту библиотеку? Всё её содержимое будет удалено безвозвратно.",
    "core.library.deletedLib": "Библиотека удалена",
    "core.library.unmountTitle": "Отключить символическую ссылку",
    "core.library.unmountNameFallback": "эту символическую ссылку",
    "core.library.unmountDesc": "«{name}» будет удалена из списка; файлы на диске не будут удалены.",
    "core.library.unmount": "Отключить",
    "core.library.unmounted": "Отключено",
    "core.library.singleFile": " (один файл)",
    "core.library.symlink": "Символическая ссылка",
    "core.library.pluginBadge": "Плагин",
    "core.library.emptyLibraries": "Пока нет библиотек. Нажмите «Импорт» в правом верхнем углу или создайте новую библиотеку.",
    "core.library.noSymlinks": "Нет символических ссылок: добавьте локальную папку или файл справа",
    "core.library.collectionCount": "{count} наборов документов",
    "core.library.searchPlaceholder": "Поиск наборов документов...",
    "core.library.gridView": "Сетка",
    "core.library.listView": "Список",
    "core.library.unitChapter": "Глава",
    "core.library.unitCanvas": "Канвас",
    "core.library.unitDoc": "Документ",
    "core.library.noSearchResults": "Нет подходящих наборов документов.",
    "core.library.emptyCollections": "В этой библиотеке ещё нет наборов документов: импортируйте пакет курса или создайте новый.",
    "core.library.selectPlaceholder": "Выберите библиотеку или символическую ссылку, чтобы просмотреть содержимое.",
    "core.library.newLibTitle": "Новая библиотека",
    "core.library.namePlaceholder": "Например: профильный курс",
    "core.library.descriptionOptional": "Описание (необязательно)",
    "core.library.descPlaceholder": "Что будет храниться в этой библиотеке",
    "core.library.createdLib": "Библиотека создана",
    "core.library.newCanvas": "Новый канвас",
    "core.library.newCanvasTitle": "Новый канвас",
    "core.library.newCanvasPlaceholder": "Название канваса",
    "core.library.newCanvasDefault": "Канвас без названия",
    "core.library.createdCanvas": "Канвас создан",
    "core.library.newDoc": "Новый документ",
    "core.library.newDocTitle": "Новый документ",
    "core.library.newDocPlaceholder": "Название документа",
    "core.library.newDocDefault": "Документ без названия",
    "core.library.createdDoc": "Документ создан",
    "core.library.import": "Импорт",
    "core.library.importFailed": "Не удалось импортировать",
    "core.library.importedCourse": "Импортирован курс «{names}»",
    "core.library.importedNote": "Импортирована заметка ({count} разделов)",
    "core.library.importWarning": "Некоторые блоки импортированного содержимого зависят от плагина «{names}»: при его отключении они будут показаны как исходные данные.",
    "core.library.importedCanvas": "Импортирован канвас «{name}»",
    "core.library.importedContent": "Содержимое импортировано",
    "core.library.importTitle": "Импорт содержимого",
    "core.library.importDesc": "Поддерживаются файлы MetaPilot (.mpf/.canvas, единый формат: doc — содержимое курса, canvas — диаграмма), пакеты курсов (zip) и заметки Markdown.",
    "core.library.tabMpf": "Файлы MetaPilot",
    "core.library.tabCourse": "Пакет курса",
    "core.library.mpfLabel": "Файлы MetaPilot (.mpf / .canvas)",
    "core.library.mpfHint": "Файлы типа doc распознаются как курс/документ; файлы .canvas (Obsidian Canvas) автоматически преобразуются в диаграммы.",
    "core.library.courseGateHint": "Импорт пакета курса (zip)",
    "core.library.courseFileLabel": "Файл пакета курса (.zip, с manifest.json)",
    "core.library.noteGateHint": "Импорт заметки Markdown",
    "core.library.noteFileLabel": "Файл Markdown / Obsidian (.md)",

    # ---- 编辑页 ----
    "core.edit.block.markdown": "Отображение (Markdown)",
    "core.edit.block.single_choice": "Одиночный выбор",
    "core.edit.block.multiple_choice": "Множественный выбор",
    "core.edit.block.fill_blank": "Заполнение пропусков",
    "core.edit.block.short_answer": "Краткий ответ",
    "core.edit.block.interactive": "Интерактивный блок",
    "core.edit.block": "Блок",
    "core.edit.collectionInfo": "Информация о курсе",
    "core.edit.summary": "Краткое описание",
    "core.edit.newDocName": "Новая глава",
    "core.edit.newSectionName": "Новый пункт знаний",
    "core.edit.deleteDocTitle": "Удалить главу",
    "core.edit.deleteDocDesc": "Удалить эту главу? Все её разделы и содержимое будут удалены безвозвратно.",
    "core.edit.deleteSectionTitle": "Удалить раздел",
    "core.edit.deleteSectionDesc": "Удалить этот раздел?",
    "core.edit.deleteBlockTitle": "Удалить блок",
    "core.edit.deleteBlockDesc": "Удалить этот блок?",
    "core.edit.newFolderTitle": "Новая папка",
    "core.edit.newFolderDesc": "Введите название новой папки.",
    "core.edit.newFolderPlaceholder": "Например: конспекты главы",
    "core.edit.renameFolderTitle": "Переименовать папку",
    "core.edit.deleteFolderTitle": "Удалить папку",
    "core.edit.deleteFolderDesc": "Удалить эту папку? Все вложенные папки и документы будут удалены безвозвратно.",
    "core.edit.createFailed": "Не удалось создать",
    "core.edit.renameFailed": "Не удалось переименовать",
    "core.edit.deleteFailed": "Не удалось удалить",
    "core.edit.moveFailed": "Не удалось переместить",
    "core.edit.docSettings": "Настройки главы",
    "core.edit.docNameLabel": "Название главы",
    "core.edit.docTypeStudy": "Учебная глава",
    "core.edit.docTypeQuiz": "Глава-тест",
    "core.edit.moveDocLabel": "Папка назначения (перемещение документа)",
    "core.edit.rootFolder": "Корневая папка",
    "core.edit.docTypeHint": "Учебные главы и главы-тесты можно свободно сочетать, разделяя обучение и проверку.",
    "core.edit.sectionSettings": "Настройки пункта знаний",
    "core.edit.sectionNameLabel": "Название пункта знаний",
    "core.edit.refDocLabel": "Ссылка на другой документ (цитирование в разделе)",
    "core.edit.noRef": "Без ссылки",
    "core.edit.refDocHint": "При установке ссылки на странице обучения появится карточка цитаты с переходом к целевому документу.",
    "core.edit.addBlockLabel": "Добавить блок",
    "core.edit.backToSection": "Вернуться к разделу",
    "core.edit.blockSaved": "Блок сохранён",
    "core.edit.addSectionTitle": "Новый раздел",
    "core.edit.noBlocks": "Нет блоков",
    "core.edit.noSections": "Нет разделов",
    "core.edit.subFolder": "Подпапка",
    "core.edit.emptyFolder": "Пустая папка",
    "core.edit.mode": "Режим редактирования",
    "core.edit.dirty": "Есть изменения",
    "core.edit.saved": "Сохранено",
    "core.edit.newDoc": "Глава",
    "core.edit.newFolder": "Папка",
    "core.edit.done": "Готово",
    "core.edit.markdownContent": "Содержимое Markdown",
    "core.edit.markdownPlaceholder": "# Заголовок\n\nОсновной текст: поддерживаются Markdown, таблицы и списки задач GFM",
    "core.edit.question": "Вопрос",
    "core.edit.options": "Варианты (по одному в строке)",
    "core.edit.optionsPlaceholder": "Вариант A\nВариант B\nВариант C",
    "core.edit.correctIndex": "Индекс правильного ответа (начиная с 0)",
    "core.edit.correctIndexes": "Индексы правильных ответов (через запятую)",
    "core.edit.blanksAnswers": "Ответы для пропусков (один на строку)",
    "core.edit.blanksPlaceholder": "Ответ 1\nОтвет 2",
    "core.edit.reference": "Эталонный ответ",
    "core.edit.keywordsLabel": "Ключевые слова (через запятую, для справки ИИ)",
    "core.edit.keywordsPlaceholder": "ключевое_слово1,ключевое_слово2",
    "core.edit.aiGraded": "Оценка ИИ (для открытых вопросов)",
    "core.edit.title": "Заголовок",
    "core.edit.assetFile": "Файл ресурсов (путь относительно interactives/ пакета курса)",
    "core.edit.iframeHeight": "Высота iframe (px)",
    "core.edit.explanationLabel": "Разбор / подсказка (необязательно)",

    # ---- 图表画布 ----
    "core.canvas.saved": "Канвас сохранён",
    "core.canvas.saveFailed": "Не удалось сохранить",
    "core.canvas.doubleClickEdit": "Двойной клик — редактирование текста",
    "core.canvas.notCanvas": "Этот набор документов — не канвас.",
    "core.canvas.backToLibrary": "Вернуться в библиотеку",
    "core.canvas.badge": "Канвас",
    "core.canvas.dirty": "Есть несохранённые изменения",
    "core.canvas.unsavedTitle": "Есть несохранённые изменения",
    "core.canvas.unsavedDesc": "На канвасе есть несохранённые изменения. Сохранить перед закрытием?",
    "core.canvas.discardAndLeave": "Не сохранять и выйти",
    "core.canvas.saveAndLeave": "Сохранить и выйти",
    "core.canvas.newTextNode": "Новый текстовый узел",
    "core.canvas.help": "Перетаскивайте узлы для перемещения; рамка на пустом месте — выделение, Shift — множественный выбор, Delete — удаление, Ctrl+C/V — копирование/вставка, Ctrl+Z — отмена; двойной клик по тексту — редактирование; перетащите точку соединения на краю узла к другому узлу, чтобы создать связь; колесо мыши — панорамирование, Ctrl + колесо — масштаб, удерживайте пробел и перетаскивайте для панорамирования.",
    "core.canvas.undo": "Отменить (Ctrl+Z)",
    "core.canvas.redo": "Повторить (Ctrl+Shift+Z)",
    "core.canvas.zoomOut": "Уменьшить",
    "core.canvas.zoomIn": "Увеличить",
    "core.canvas.fitView": "Вписать в холст",
    "core.canvas.empty": " (пусто)",
    "core.canvas.group": "Группа",
    "core.canvas.deleteNode": "Удалить узел",
    "core.canvas.dragLink": "Перетащите, чтобы соединить",
    "core.canvas.emptyBoard": "Пустой холст: нажмите «Новый текстовый узел» в правом верхнем углу, чтобы начать",
    "core.canvas.stats": "Узлов: {nodes} · Связей: {edges}",
    "core.canvas.exportMpf": "Экспорт .mpf",
    "core.canvas.exportCanvas": "Экспорт .canvas",
    "core.canvas.export": "Экспорт",
    "core.canvas.center": "По центру",
    "core.canvas.alignLeft": "По левому краю",
    "core.canvas.alignCenter": "По центру",
    "core.canvas.alignRight": "По правому краю",
    "core.canvas.edgePath": "Стиль связи",
    "core.canvas.pathSmooth": "Плавная кривая",
    "core.canvas.pathStraight": "Прямая линия",
    "core.canvas.pathSquare": "Прямые углы",
    "core.canvas.resize": "Изменить размер",
    "core.canvas.groupSelection": "Сгруппировать",
    "core.canvas.dragAddCard": "Перетащите, чтобы добавить карточку",
    "core.canvas.dragAddNote": "Перетащите, чтобы добавить заметку",
    "core.canvas.dragAddNoteVault": "Перетащите заметку из библиотеки",
    "core.canvas.dragAddMediaVault": "Перетащите медиафайл из библиотеки",
    "core.canvas.paste": "Вставить",
    "core.canvas.toggleNav": "Развернуть/свернуть навигацию",
    "core.canvas.noCanvases": "Нет канвасов",
    "core.canvas.edgeStart": "Начало",
    "core.canvas.edgeEnd": "Конец",
    "core.canvas.arrow": "Стрелка",
    "core.canvas.toggleStartArrow": "Переключить стрелку в начале",
    "core.canvas.toggleEndArrow": "Переключить стрелку в конце",
    "core.canvas.edgeLabel": "Метка",
    "core.canvas.colorTitle": "Цвет {color}",
    "core.canvas.clearColor": "Убрать цвет",
    "core.canvas.deleteEdge": "Удалить связь",
    "core.canvas.addNode": "Новый узел",
    "core.canvas.addNodeText": "Текст",
    "core.canvas.addNodeFile": "Файл",
    "core.canvas.addNodeLink": "Ссылка",
    "core.canvas.addNodeGroup": "Группа",
    "core.canvas.addFileTitle": "Путь к файлу",
    "core.canvas.addFileDesc": "Относительный путь в библиотеке, например notes/пример.md, images/рисунок.png (совместимо с Obsidian)",
    "core.canvas.addLinkTitle": "URL ссылки",
    "core.canvas.addGroupTitle": "Метка группы",
    "core.canvas.groupName": "Название группы",

    # ---- 统计页 ----
    "core.stats.intro": "Официальное ядро предоставляет базовые виджеты статистики, а плагины (например, «Курс») могут добавлять свои; перетаскивайте карточки для изменения порядка, изменяйте размер в правом верхнем углу, а на странице настроек можно включить «Отмечать источник компонентов».",
    "core.stats.resize": "Изменить размер (сейчас: {size})",
    "core.stats.hide": "Скрыть виджет",
    "core.stats.manage": "Управление виджетами",
    "core.stats.hiddenCount": "Скрыто: {count}",
    "core.stats.manageDesc": "Скрывайте виджеты во вкладке «Отображаемые» или возвращайте их на панели «Скрытые»; перетаскивание карточек на странице статистики изменяет их порядок.",
    "core.stats.none": "Пока нет доступных виджетов статистики",
    "core.stats.visibleCount": "Отображаемые ({count})",
    "core.stats.hiddenTab": "Скрытые ({count})",
    "core.stats.noHidden": "Скрытых виджетов нет: все виджеты отображаются",
    "core.stats.resetLayout": "Восстановить стандартную раскладку",
    "core.stats.showAll": "Показать все",
    "core.stats.restore": "Восстановить",
    "core.stats.noVisits": "Нет записей о посещениях",
    "core.stats.noStayTime": "Нет записей о времени на странице",
    "core.stats.visits": "{count} раз",
    "core.stats.wordUnit": "слов",
    "core.stats.unknownWidget": "Неизвестный виджет",
    "core.stats.heatmap3m": "Тепловая карта посещений за 3 месяца",
    "core.stats.heatmapTooltip": "{day}.{month} · {count} посещений",
    "core.stats.heatmapLess": "Меньше",
    "core.stats.heatmapMore": "Больше",
    "core.stats.hourly": "Посещения по часам",
    "core.stats.hourTooltip": "{hour}:00 · {count} раз",
    "core.stats.hourLabel": "{hour}:00",
    "core.stats.monthLabel": "{month}",
    "core.stats.weekdays": "Пн,Вт,Ср,Чт,Пт,Сб,Вс",
    "core.stats.courseDisabled": "Зависит от плагина «Курс», не включён",
    "core.stats.totalStudy": "Всего изучено",
    "core.stats.chartMinutes": "мин",
    "core.stats.noStudyRecords": "Нет записей об обучении",
    "core.stats.providedBy": "Предоставлено плагином «{name}»",
    "core.stats.providedByTooltip": "Плагин «{name}»",

    # ---- 通用弹窗 / toast ----
    "core.dialog.selectPlaceholder": "Выберите…",
    "core.toast.copied": "Скопировано в буфер обмена",

    # ---- AI 用量 ----
    "core.widget.aiUsage": "Использование ИИ",
    "core.stats.rangeToday": "Сегодня",
    "core.stats.rangeWeek": "Эта неделя",
    "core.stats.rangeMonth": "Этот месяц",
    "core.stats.rangeAll": "Всё время",
    "core.stats.aiCalls": "Число вызовов",
    "core.stats.aiTokens": "Использование токенов",
    "core.stats.aiCost": "Стоимость",
    "core.stats.aiTokensDetail": "Вход {in} / кэш {cached} / выход {out}",
    "core.stats.aiCallsShort": "Вызовов: {n}",
    "core.stats.aiTokensShort": "{n} токенов",
    "core.stats.aiUsageEmpty": "Нет записей об использовании ИИ (вызовы плагинов через единый шлюз записываются здесь).",

    # ---- course 域 ----
    "course.exportFailed": "Не удалось экспортировать",
    "course.pluginDisabledWarning": "Этот документ зависит от плагина «Курс»: прогресс обучения и интерактивные задания недоступны. Включите плагин на странице «Плагины».",
    "course.backToLibrary": "Вернуться в библиотеку",
    "course.noDescription": "Нет описания",
    "course.authorLabel": "Автор: {author}",
    "course.export": "Экспорт",
    "course.continueLearning": "Продолжить обучение",
    "course.learningProgress": "Прогресс обучения",
    "course.progressCount": "{completed} / {total} пунктов знаний",
    "course.lastLearned": "Последний изученный: {name}",
    "course.progressRequiresPlugin": "Прогресс обучения зависит от плагина «Курс»: после его включения можно отмечать изученное и отслеживать последнее место обучения.",
    "course.quiz": "Тест",
    "course.noSectionsInChapter": "В этой главе пока нет разделов",
    "course.noChapters": "В этом курсе ещё нет глав: нажмите «Редактировать» в правом верхнем углу, чтобы создать их.",

    # ---- course 库页集合创建/转换 ----
    "course.library.newCourse": "Новый курс",
    "course.library.newCourseTitle": "Новый курс",
    "course.library.newCoursePlaceholder": "Название курса",
    "course.library.newCourseDefault": "Курс без названия",
    "course.library.createdCourse": "Курс создан",
    "course.library.createCourseFailed": "Не удалось создать курс",
    "course.library.toCourse": "Преобразовать в курс",
    "course.library.toCourseTitle": "Преобразовать в курс",
    "course.library.toCourseDesc": "Преобразовать «{name}» в курс? Курс — это документ с дополнением (патчем), включающим прогресс обучения, оценку ответов, интерактивные блоки и другие функции курса; без плагина «Курс» эти функции недоступны.",
    "course.library.toCourseConfirm": "Преобразовать в курс",
    "course.library.convertedCourse": "«{name}» преобразован в курс",
    "course.library.convertCourseFailed": "Не удалось преобразовать в курс",

    # ---- insight 域 ----
    "insight.pageTitle": "AI-аналитика",
    "insight.intro": "Выберите документы или библиотеки, создайте индекс и передайте их ИИ: он изучит связи между материалами и по четырём режимам сформирует ответы, рекомендации, диаграммы или курсы.",
    "insight.introWithSymlink": "Выберите документы, библиотеки или локальные папки, создайте индекс и передайте их ИИ: он изучит связи между материалами и по четырём режимам сформирует ответы, рекомендации, диаграммы или курсы.",
    "insight.stepIndex": "Шаг 1 · Создание индекса",
    "insight.stepAsk": "Шаг 2 · Вопрос к ИИ",
    "insight.stepIndexQuoted": "«Шаг 1 · Создание индекса»",
    "insight.mustIndexBefore": "Сначала создайте индекс, затем задавайте вопросы; если задать вопрос без индекса, он будет создан автоматически (с индикатором прогресса).",
    "insight.noIndexedBefore": "Индексированных источников ещё нет. Сначала перейдите к ",
    "insight.noIndexedAfter": ", создайте векторный индекс для выбранного содержимого и затем задайте вопрос.",
    "insight.noIndexedAfterWithSymlink": ", создайте векторный индекс для выбранных документов или локальных папок и затем задайте вопрос.",
    "insight.vectorModelTitle": "Векторная модель и локальный сервис",
    "insight.embeddingRunning": "Работает",
    "insight.embeddingNotReady": "Не готово",
    "insight.selectModelPlaceholder": "Выберите модель embedding",
    "insight.stopService": "Остановить сервис",
    "insight.startService": "Запустить сервис (при первом запуске модель будет загружена автоматически)",
    "insight.modelDownloadHint": "Загрузка модели пробуется по нескольким каналам автоматически; при первой загрузке дождитесь готовности модели — статус на странице обновится сам. Конкретные источники загрузки и список моделей задаются конфигурацией серверной части.",
    "insight.selectSourcesTitle": "Выберите источники данных (можно несколько)",
    "insight.indexIntro": "Можно выбирать по библиотеке, отдельному набору документов или документу; индекс хранится отдельно для каждого источника.",
    "insight.indexIntroWithSymlink": "Можно выбирать по библиотеке, набору документов или документу, а также целую локальную папку или любой путь внутри неё; индекс хранится отдельно для каждого источника.",
    "insight.indexing": "Индексация...",
    "insight.indexingProgress": "Проиндексировано {done}/{total} фрагментов",
    "insight.indexQueued": "Индексация запущена, прогресс можно посмотреть ниже",
    "insight.buildVectorIndex": "Создать векторный индекс",
    "insight.noSources": "Нет доступных источников: сначала создайте библиотеку в разделе «Моя библиотека».",
    "insight.noSourcesWithSymlink": "Нет доступных источников: сначала создайте библиотеку в разделе «Моя библиотека» или подключите локальную папку.",
    "insight.askSourcesTitle": "Выберите источники для анализа (можно несколько, поиск объединяется)",
    "insight.askTitle": "Анализ ИИ (в ответах будут указаны источники)",
    "insight.askPlaceholder": "Задайте вопрос ИИ, например: «Какая связь между этими материалами?»",
    "insight.refSources": "Источники",
    "insight.sourceRef": "[Источник {n}]",
    "insight.asking": "Идёт поиск и подготовка ответа...",
    "insight.inputPlaceholder": "Введите ваш вопрос или направление размышлений...",
    "insight.askButton": "Спросить",
    "insight.groupLibrary": "Документы библиотеки (библиотека / набор / документ)",
    "insight.groupSymlink": "Локальные папки",
    "insight.indexedCount": "Проиндексировано фрагментов: {count}",
    "insight.notIndexed": "Не проиндексировано",
    "insight.pluginHint": "AI-аналитика: анализ связей между материалами и генерация контента",
    "insight.loadResourcesFailed": "Не удалось загрузить источники данных",
    "insight.startServiceToast": "Сервис запускается (при первом запуске модель будет загружена автоматически)",
    "insight.startFailed": "Не удалось запустить",
    "insight.serviceStopped": "Сервис остановлен",
    "insight.indexDone": "Индексация завершена: {ok}/{total} источников",
    "insight.indexFailed": "Не удалось создать индекс",
    "insight.askFailed": "Не удалось получить ответ",

    # ---- 思考模式 ----
    "insight.modeTitle": "Режим размышления",
    "insight.modeIntro": "Выберите способ размышления: ИИ изучит выбранные материалы в этом режиме и сформирует контент.",
    "insight.modeAssist": "Помощь в размышлении",
    "insight.modeAssistDesc": "Находит связи между материалами, даёт ответы и рекомендации",
    "insight.modeWander": "Свободные ассоциации",
    "insight.modeWanderDesc": "Соединяет материалы с вашим направлением размышлений, генерирует ассоциации",
    "insight.modeReflect": "Рефлексия и обобщение",
    "insight.modeReflectDesc": "Обобщает связи и слепые зоны, которые вы могли не заметить",
    "insight.modePlan": "Планирование на основе инсайтов",
    "insight.modePlanDesc": "Многоэтапные рассуждения: создаёт диаграмму или мини-курс, чтобы обучить вас",

    # ---- 洞察规划 ----
    "insight.planOutputTitle": "Тип результата",
    "insight.planOutputCanvas": "Карта знаний (канвас)",
    "insight.planOutputCourse": "Мини-курс (документ)",
    "insight.planLibraryTitle": "Сохранить в библиотеку",
    "insight.planLibraryAuto": "Библиотека по умолчанию (первая)",
    "insight.planGoalPlaceholder": "Опишите цель, например: выделите ключевые понятия и связи этих материалов и помогите понять их за минимальное время",
    "insight.planButton": "Начать планирование",
    "insight.planning": "ИИ анализирует связи материалов в несколько этапов и генерирует результат. Может занять 1–2 минуты...",
    "insight.planDone": "Создано: «{name}»",
    "insight.planOpenCanvas": "Открыть диаграмму",
    "insight.planOpenCourse": "Открыть курс",
    "insight.planSummary": "Итоги планирования",
    "insight.planFailed": "Не удалось выполнить планирование",

    # ---- 洞察规划执行路线 ----
    "insight.planRoadmap": "План действий ИИ",
    "insight.planThinking": "Ход рассуждений ИИ",
    "insight.planStep.retrieve": "Поиск материалов",
    "insight.planStep.plan": "Анализ тем и связей",
    "insight.planStep.review": "Критическая рефлексия",
    "insight.planStep.generateCanvas": "Создание карты знаний",
    "insight.planStep.generateCourse": "Создание мини-курса",
    "insight.planStep.save": "Сохранение в библиотеку",
    "insight.planStepRunning": "Выполняется…",
    "insight.planConnecting": "Подключение к ИИ и составление плана…",

    # ---- 自动建索引 ----
    "insight.autoIndexing": "Для выбранных источников нет индекса: создаю автоматически ({done}/{total})...",
    "insight.autoIndexDone": "Индекс создан, продолжаю генерацию...",
    "insight.autoIndexFailed": "Не удалось создать индекс автоматически: создайте его вручную на шаге 1",
    "insight.symlinkBrowse": "Обзор папок",
    "insight.treeEmpty": " (пусто)",

    # ---- 数据检索库 ----
    "insight.kbTitle": "База для поиска данных",
    "insight.goAsk": "К вопросам",
    "insight.selectedCount": "Выбрано: {count}",
    "insight.kbIndexed": "Проиндексировано источников: {count}",
    "insight.collapsePanel": "Свернуть панель базы поиска",
    "insight.expandPanel": "Развернуть панель базы поиска",
    "insight.kbHint": "Отметьте библиотеки / наборы / документы как область поиска: можно создавать индекс или сразу задавать вопросы; для непроиндексированных источников индекс создаётся автоматически.",
    "insight.kbHintWithSymlink": "Отметьте библиотеки / наборы / документы или локальные папки как область поиска: можно создавать индекс или сразу задавать вопросы; для непроиндексированных источников индекс создаётся автоматически.",
    "insight.buildIndexTitle": "Создать векторный индекс",
    "insight.buildIndexHint": "Выбрано источников: {count} (можно изменить в «Базе для поиска данных» слева); для непроиндексированных также будет создан индекс.",

    # ---- symlink 域 ----
    "symlink.fileBrowser": "Обозреватель файлов",
    "symlink.symlinkPlugin": "Плагин символических ссылок",
    "symlink.pluginHint": "Просмотр и чтение/запись локальных папок",
    "symlink.linkLocalDoc": "Подключить локальный документ (символическая ссылка)",
    "symlink.addMountDesc1": "Подключается содержимое на локальном диске — ",
    "symlink.addMountDesc2": "или",
    "symlink.addMountDesc3": " — исходные файлы не копируются и не перемещаются; после подключения их можно просматривать, читать и редактировать в обозревателе файлов как документы.",

    # ---- 挂载 ----
    "symlink.mounts": "Подключения",
    "symlink.mount": "Подключить",
    "symlink.thatMount": "это подключение",
    "symlink.unmount": "Отключить",
    "symlink.unmountSymlink": "Отключить символическую ссылку",
    "symlink.unmountConfirmDesc": "«{name}» будет удалена из списка; файлы на диске не будут удалены.",
    "symlink.noMounts": "Нет подключений: добавьте локальную папку или файл в правом верхнем углу",
    "symlink.currentMountRoot": "Корень текущего подключения: {root}",
    "symlink.pleaseMount": "Сначала подключите локальную папку или файл",
    "symlink.mountSuccess": "Подключено успешно",
    "symlink.mountFailed": "Не удалось подключить",
    "symlink.displayName": "Отображаемое имя",
    "symlink.namePlaceholder": "Например: мои заметки",
    "symlink.localPathLabel": "Локальный путь (папка или файл)",
    "symlink.pathPlaceholder": "Нажмите «Обзор» для выбора или введите вручную (поддерживаются Windows/Linux)",
    "symlink.collapse": "Свернуть",
    "symlink.browse": "Обзор",
    "symlink.afterMountHint": "После подключения текстовые файлы в папке можно просматривать, читать и редактировать в обозревателе файлов (доступ ограничен корнем подключения).",

    # ---- 目录 / 文件 ----
    "symlink.directory": "Каталог",
    "symlink.folder": "Папка",
    "symlink.file": "Файл",
    "symlink.singleFile": "Один файл",
    "symlink.singleFileNote": " (один файл)",
    "symlink.singleFileMount": " (подключение одного файла)",
    "symlink.rootDir": " (корневая папка)",
    "symlink.noSubfolders": "Нет подпапок",
    "symlink.emptyDir": "Пустой каталог",
    "symlink.expandDir": "Развернуть каталог",
    "symlink.collapseDir": "Свернуть каталог",
    "symlink.newFolder": "Новая папка",
    "symlink.newFolderDesc": "Введите название новой папки.",
    "symlink.newFolderPlaceholder": "Например: конспекты главы",

    # ---- 工具栏 ----
    "symlink.searchPlaceholder": "Поиск…",
    "symlink.gridView": "Сетка",
    "symlink.listView": "Список",
    "symlink.backToList": "Назад к списку",
    "symlink.reveal": "Показать в обозревателе",
    "symlink.revealInFileManager": "Показать в файловом менеджере",
    "symlink.openWithDefault": "Открыть программой по умолчанию",
    "symlink.editing": "Редактирование: {path}",

    # ---- 操作结果 / toast ----
    "symlink.saved": "Сохранено",
    "symlink.saveFailed": "Не удалось сохранить",
    "symlink.createFailed": "Не удалось создать",
    "symlink.deleteFile": "Удалить файл",
    "symlink.deleteConfirmDesc": "Удалить «{target}»?",
    "symlink.deleteDirWarning": "Папка будет удалена рекурсивно, безвозвратно.",
    "symlink.deleteFailed": "Не удалось удалить",
    "symlink.openedWithDefault": "Открыто программой по умолчанию",
    "symlink.openFailed": "Не удалось открыть",
    "symlink.readFailed": "Не удалось прочитать",
    "symlink.noInlinePreview": "Для этого типа файлов встроенный предпросмотр не поддерживается",
    "symlink.noInlinePreviewHint": "Для этого типа файлов встроенный предпросмотр не поддерживается: используйте контекстное меню — «Открыть программой по умолчанию»",
    "symlink.noMatch": "Нет подходящих элементов.",

    # ---- 本机路径选择器 ----
    "symlink.goUp": "На уровень выше",
    "symlink.myComputer": "Мой компьютер",
    "symlink.reading": "Чтение…",
    "symlink.emptyFolder": "Пустая папка",
    "symlink.selectedFolder": "Папка: {path}",
    "symlink.selectedFile": "Файл: {path}",
    "symlink.selectHint": "Один клик — выбор папки или файла, двойной клик по папке — вход в неё",
    "symlink.selectThisFolder": "Выбрать эту папку",
    "symlink.selectThisFile": "Выбрать этот файл",

    # ---- sys 域 ----
    "sys.title": "Настройки",
    "sys.subtitle": "Управление уведомлениями, связанными с плагинами. MetaPilot — это библиотека документов: документы всегда можно открыть, а неотрендеренные части показываются как исходные данные; уведомления лишь напоминают и не прерывают работу.",
    "sys.language": "Язык",
    "sys.languageDesc": "Язык интерфейса: применяется сразу после переключения и сохраняется локально (localStorage).",
    "sys.appearance": "Оформление",
    "sys.appearanceDesc": "Тёмный / светлый режим можно переключать в любой момент; фирменные темы предоставляет плагин «Темы» (после включения на странице управления плагинами).",
    "sys.pluginWarnings": "Предупреждения о плагинах",
    "sys.pluginWarningsDesc": "При открытии документа, зависящего от отключённого плагина (например, курса или базы знаний), вверху появляется предупреждение: «Этот контент зависит от плагина xx, некоторые блоки могут не отрендериться».",
    "sys.pluginErrors": "Сообщения об ошибках плагинов",
    "sys.pluginErrorsDesc": "Если операция завершается ошибкой из-за отключённого плагина (например, оценка ИИ или вопросы к базе знаний), вверху появляется сообщение; после его закрытия такие ошибки игнорируются без уведомления.",
    "sys.componentSource": "Отмечать источник компонентов",
    "sys.componentSourceDesc": "При включении на страницах библиотеки и статистики компоненты и контент от плагинов помечаются значком этого плагина (имя видно при наведении); официальное ядро (сам MetaPilot) не помечается. При выключении метки источников не показываются.",
    "sys.localOnly": "Настройки сохраняются только локально в браузере (localStorage) и не влияют на другие устройства.",

    # ---- 插件管理页 ----
    "sys.plugins.title": "Управление плагинами",
    "sys.plugins.headerPrefix": "Плагины делятся на пользовательские, официальные и ядро. Плагин — это независимый функциональный пакет в каталоге ",
    "sys.plugins.headerSuffix": " на серверной части: его можно установить из «Магазина плагинов» или загрузить собственный.",
    "sys.plugins.tabLocal": "Локальные плагины",
    "sys.plugins.tabStore": "Магазин плагинов",
    "sys.plugins.filterByTag": "Фильтр по тегам: ",
    "sys.plugins.sourceUser": "Пользовательские плагины",
    "sys.plugins.sourceUserDesc": "Можно разработать самостоятельно, установить из магазина или загрузить zip; такие плагины можно отключать и удалять.",
    "sys.plugins.sourceOfficial": "Официальные плагины",
    "sys.plugins.sourceOfficialDesc": "Практичные плагины от разработчиков MetaPilot: их можно включать и отключать, но нельзя удалять.",
    "sys.plugins.sourceCore": "Ядро",
    "sys.plugins.sourceCoreDesc": "Сам MetaPilot: просмотр библиотеки документов и чтение Markdown. Отключение и удаление запрещены.",
    "sys.plugins.enabledToast": "Плагин включён",
    "sys.plugins.disabledToast": "Плагин отключён",
    "sys.plugins.opFailed": "Операция не удалась",
    "sys.plugins.deleteTitle": "Удалить плагин",
    "sys.plugins.deleteDesc": "Удалить плагин «{name}»? Каталог backend/plugins/{id} будет удалён с диска безвозвратно.",
    "sys.plugins.deletedToast": "Плагин «{name}» удалён",
    "sys.plugins.deleteFailed": "Не удалось удалить",
    "sys.plugins.idLabel": "id: ",
    "sys.plugins.dependsOn": "Зависит от плагинов: ",
    "sys.plugins.missingDeps": "Отсутствуют зависимости (включите сначала): ",
    "sys.plugins.featureCourseImport": "Импорт / экспорт пакетов курсов",
    "sys.plugins.featureCourseFlow": "Изучение по главам и пунктам знаний (поток блоков)",
    "sys.plugins.featureCourseProgress": "Прогресс обучения и статистика времени",
    "sys.plugins.featureCourseGrading": "Оценка открытых вопросов ИИ",
    "sys.plugins.featureCourseInteractive": "Рендер интерактивных блоков",
    "sys.plugins.featureInsightIndex": "Векторный индекс источников разной детализации (библиотека/набор/документ/локальная папка)",
    "sys.plugins.featureInsightModes": "Четыре режима размышления (помощь / ассоциации / рефлексия / планирование)",
    "sys.plugins.featureInsightPlan": "Многоэтапные рассуждения для создания диаграмм и мини-курсов (.mpf)",
    "sys.plugins.needEnablePrefix": "Необходимо включить плагин «",
    "sys.plugins.needEnableSuffix": "», чтобы использовать",
    "sys.plugins.thisFeature": "эту функцию",
    "sys.plugins.goEnable": "Включить на странице управления плагинами",
    "sys.plugins.uploadTitle": "Загрузить плагин (локальная установка)",
    "sys.plugins.uploadDescPrefix": "Выберите zip-архив плагина, упакованный по спецификации (с корневым каталогом ",
    "sys.plugins.uploadDescSuffix": "; см. спецификацию разработки плагинов §3). После установки плагин появится в списке ниже: его можно отключить или удалить.",
    "sys.plugins.uploadInstall": "Установить локально",
    "sys.plugins.uploadSuccess": "Плагин установлен",
    "sys.plugins.uploadFailed": "Не удалось установить",

    # ---- 插件商店 ----
    "sys.store.storeUnavailable": "Нет доступа к магазину плагинов",
    "sys.store.installedToast": "Плагин «{name}» установлен",
    "sys.store.installFailed": "Не удалось установить",
    "sys.store.localInstalledToast": "Плагин установлен локально",
    "sys.store.publishedToast": "Опубликовано в магазине плагинов",
    "sys.store.uploadFailed": "Не удалось загрузить",
    "sys.store.headerPrefix": "Просматривайте, фильтруйте и устанавливайте плагины из магазина (адрес магазина задаётся в конфигурации ",
    "sys.store.headerSuffix": " серверной части).",
    "sys.store.checkUpdates": "Проверить обновления",
    "sys.store.emptyFiltered": "В магазине нет подходящих плагинов.",
    "sys.store.installed": "Установлено",
    "sys.store.install": "Установить",
    "sys.store.uploadTitle": "Загрузить плагин",
    "sys.store.uploadDescPrefix": "Выберите zip-архив плагина, упакованный по спецификации (с корневым каталогом ",
    "sys.store.uploadDescSuffix": "; см. спецификацию разработки плагинов §3): можно установить локально или опубликовать в магазине.",
    "sys.store.uploadLocal": "Установить локально",
    "sys.store.uploadPublish": "Опубликовать в магазине",

    # ---- 主题 ----
    "sys.theme.mode": "Тёмный / светлый режим",
    "sys.theme.light": "Светлый",
    "sys.theme.dark": "Тёмный",
    "sys.theme.featured": "Фирменные темы",
    "sys.theme.pluginDisabled": "Темы предоставляет плагин «Темы»; сейчас он не включён.",
    "sys.theme.defaultName": "По умолчанию",
    "sys.theme.defaultDesc": "Следует за оформлением системы",
    "sys.plugins.changelogBtn": "История обновлений",
    "sys.plugins.changelogTitle": "{name} · История обновлений",
    "sys.plugins.changelogDesc": "Установленная версия: v{version}; история обновлений показана по версиям в обратном порядке.",
    "sys.plugins.changelogEmpty": "У этого плагина пока нет истории обновлений.",
    "sys.plugins.currentVersion": "Текущая версия",

    # ---- AI 统一网关 ----
    "sys.ai.title": "AI-сервис (единый шлюз)",
    "sys.ai.desc": "Все AI-вызовы плагинов проходят через MetaPilot; ключи и адреса хранятся только в .env на серверной части, плагины и фронтенд не видят их в открытом виде.",
    "sys.ai.loadFailed": "Не удалось загрузить конфигурацию AI",
    "sys.ai.provider": "API-провайдер",
    "sys.ai.providerOpenai": "OpenAI-совместимый (включая MiniMax / DeepSeek и др.)",
    "sys.ai.providerAnthropic": "Anthropic",
    "sys.ai.providerLocal": "Локальная модель (встроенная)",
    "sys.ai.providerNone": "Отключить облачный AI",
    "sys.ai.chatModel": "Чат-модель",
    "sys.ai.baseUrl": "Адрес API",
    "sys.ai.apiKey": "API-ключ",
    "sys.ai.apiKeyPlaceholder": "Уже задан (оставьте пустым, чтобы сохранить)",
    "sys.ai.embeddingTitle": "Векторизация (embedding)",
    "sys.ai.embeddingProvider": "Векторный сервис",
    "sys.ai.embeddingLocal": "Локальный встроенный (нужна загрузка)",
    "sys.ai.embeddingOpenai": "Облачный (через указанный выше адрес API)",
    "sys.ai.embeddingNone": "Отключить векторизацию",
    "sys.ai.embeddingModel": "Векторная модель",
    "sys.ai.embeddingUrl": "Адрес локального векторного сервиса",
    "sys.ai.prices": "Цены моделей (за миллион токенов)",
    "sys.ai.pricesHint": "Используется для оценки стоимости на странице статистики; цены за кэш / вход / выход; валюта $ или ¥",
    "sys.ai.priceModel": "Модель",
    "sys.ai.priceInput": "Вход",
    "sys.ai.priceCached": "Кэш-хит",
    "sys.ai.priceOutput": "Выход",
    "sys.ai.addPrice": "Добавить цену модели",
    "sys.ai.currency": "Валюта по умолчанию",
    "sys.ai.save": "Сохранить конфигурацию",
    "sys.ai.saved": "Конфигурация AI сохранена (записана в .env)",
    "sys.ai.saveFailed": "Не удалось сохранить",
    "sys.ai.test": "Проверить соединение",
    "sys.ai.testing": "Проверка...",
    "sys.ai.testOk": "Соединение успешно: {model} (вход {in} / выход {out} токенов)",
    "sys.ai.testFailed": "Соединение не установлено",
    "sys.ai.localTitle": "Встроенные локальные модели",
    "sys.ai.localDesc": "Скачиваются одним нажатием при необходимости (автоматически пробуются несколько зеркал); после загрузки можно запускать",
    "sys.ai.downloaded": "Загружено",
    "sys.ai.notDownloaded": "Не загружено",
    "sys.ai.downloading": "Загрузка...",
    "sys.ai.download": "Скачать",
    "sys.ai.start": "Запустить",
    "sys.ai.startFailed": "Не удалось запустить",
    "sys.ai.stop": "Остановить",
    "sys.ai.running": "Работает",
    "sys.ai.notRunning": "Не запущено",
    "sys.ai.modelKindEmbedding": "Векторизация",
    "sys.ai.modelKindLlm": "Диалог",
    "sys.ai.modelKindRerank": "Ранжирование",
    "sys.ai.localOnlyHint": "Эти настройки хранятся только в локальном .env и не отправляются ни в один сервис.",
    # ---- 库操作（其他 agent 新增 core.library 域） ----
    "core.library.addSymlink": "Добавить символическую ссылку",
    "core.library.defaultLib": "По умолчанию",
    "core.library.defaultSet": "Установлено как библиотека по умолчанию",
    "core.library.menuMore": "Другие действия",
    "core.library.pin": "Закрепить",
    "core.library.pinned": "Закреплено",
    "core.library.pinnedLib": "Закреплено сверху",
    "core.library.renameLib": "Переименовать",
    "core.library.renameLibTitle": "Переименовать библиотеку",
    "core.library.renamedLib": "Библиотека переименована",
    "core.library.setDefault": "Установить по умолчанию",
    "core.library.unpin": "Открепить",
    "core.library.unpinnedLib": "Откреплено",
}
